CMakeLists.txt
lisp/cc.carp
lisp/gl.carp
shared/platform.h

The lastest version would fail to compile on Linux, but with a few tweaks, as you can see in the pull request, it runs now. We should then add / mention in the Installation manual, that for Linux clang must be installed. This isn't the default compiler as it is for OSX.

added some fixes so that carp compiles for linux and spin runs

---

RESEARCH.md

Markdown will squash adjacent lines into a single sentence/paragraph, blank lines between them will prevent this.
See the current formatting of
https://github.com/eriksvedang/Carp/blob/master/RESEARCH.md
which often has multiple links on the same line, and with word-wrapping.
and compare it to
https://github.com/mkfifo/Carp/blob/research-markdown-formatting/RESEARCH.md
which has a single link per line.
We could alternatively add in some html `<br />`, or format it as a mark-down list by prefixing each line with ` -`.
But this proposed solution has the advantage of the file still being easy to treat as plain-text.

adding blank lines in RESEARCH.md for better markdown formatting

---

lisp/boot.carp

Loading builtins before core means that the core.lisp implementation can use builtins.

changing boot.lisp order - builtins before core

---

src/repl.c

Something like `(println "test \" test")` compiled fine when the code was in a file, but in the repl, it mistakenly thought that a string was not terminated because it didn't interpret the `\`.
This pull request fixes that issue, and thereby enables one to have a `"` inside a string in the repl.

Fix backslashes in strings in the repl

---

lisp/core.carp

This 1. makes mkdir and touch safe against shell injection vulnerabilities,
and 2. still allows the user to create any kind of file or directory.
This would fix my #33 I think.

Make mkdir and touch safe and without surprises

---

lisp/ast.carp
lisp/compiler_helpers.carp
lisp/core.carp
lisp/core_tests.carp
lisp/structs.carp

`all?` and `any?` should be named similarly with a `?`.

renaming core.any to core.any? to match similar functions (like core.all?)

---

lisp/gl.carp

this gets `./bin/carp examples/spin.carp` working for me under linux

load dylib libGL.so under linux and use for gl functions, otherwise continue using glfw

---

CMakeLists.txt
INSTALL.md

The previous cmake included hard-coded paths to libffi which looked like paths on a mac.
This pkg-config version should work on any system as long as 'pkg-config' is installed and working correctly.
What are your thoughts?

updating cmake libffi to use pkg-config - now builds under linux cleanly

---

lisp/cc.carp
shared/platform.h

These changes fixes a compilation error and several linking errors on Ubuntu 14.04, when running `(bake-exe ...)` to build a program. On my setup I have installed all dependencies (libffi, libfw3, rlwrap) using `apt-get`.
On this operating system definition of `RTLD_DEFAULT` is protected by `__USE_GNU` so it is added as definition.
In addition, `m`, `pthread` and `dl` need to be linked in order to build successfully.

Fix build errors on Linux (Ubuntu 14.04)

---

.gitignore
CarpHask.cabal
app/Main.hs

This PR introduces Haskeline, a pure Haskell implementation fo editline, into Carp’s REPL. This means we have regular editline capabilities now, including history. Should we want to tweak the settings, we will have to move from `defaultSettings` to something more advanced, but I suggest we stick to this for now, as it is already better than what we used to have.
Cheers

Use haskeline for REPL

---

CarpHask.cabal
app/Main.hs

This PR adds simple completion and a history file to carp. The completion is purely for keywords–and the list is currently hardcoded—, and the history file is assumed to be `"~/.carp_history"`.
Cheers

Added simple completion and history file

---

app/Main.hs
core/Double.carp
core/Test.carp
core/Vector.carp
core/geometry.carp
core/prelude.h
examples/vector.carp
src/ArrayTemplates.hs
src/Obj.hs
test/vector2.carp
test/vector3.carp
test/vectorn.carp

This PR adds a Vector module. Vectors come in the flavors `Vector2`, `Vector3` and `VectorN`. 2- and 3-dimensional vectors are structs with special fields, whereas n-dimensional arrays are basically just arrays on which we can perform vector operations.
The following functions are included:
- Arithmetic operations: i.e. `+`, `-`, `*`, and `/`
- Logic operations: i.e. `=`, `/=`, and `approx` (which checks whether the vectors are identical except for negligible rounding errors)
- `mag` to get the magnitude of a vector
- `mag-sq` to get the squared magnitude of a vector
- `normalize` to normalize a vector
- `dist` to get the distance between two vectors (only 2D)
- `heading` to get the direction of the vector (only 2D)
- `rotate` to rotate a vector (only 2D)
- `dot` to get the dot product of …

Vector module

---

app/Main.hs
core/Array.carp
core/Statistics.carp
src/ArrayTemplates.hs
test/statistics.carp

This PR adds a statistics module and a few required changes to the core to make this work. All statistical functions operate on doubles, because we need functions like `sqrt` to work. If you want to use this library with any other numerical type, you will have to cast it first.
The API is fairly minimal, because I’m not sure I’d be the right person to implement fancier statistical functions.
The following functions are included:
- `sum`, a helper function to sum an Array
- `mean` calculates the mean of an Array
- `min` gets the minimum element in an Array
- `max` gets the maximum element in an Array
- `median`, `low-median`, and `high-median` calculate various flavors of the median
- `grouped-median` calculates another flavor of the median. You need to specify the interval size for it to …

Statistics: add module

---

app/Main.hs
core/Bench.carp
core/Double.carp
core/Long.carp
core/Statistics.carp
core/bench.h
core/prelude.h
src/Deftype.hs
src/Emit.hs

This PR adds a first draft for a benchmarking module. A few miscellaneous bugfixes that are required to make this work are included as well.
The functions in the benchmarking library work as follows:
- the `bench` function takes a function `f` and will profile it. It is a transliteration of [this](https://github.com/rust-lang/rust/blob/master/src/libtest/lib.rs#L1607-L1671) Rust code with the addition that if we cannot stabilize the test we will print a failing message, no test results.
- also included is a `benchn` macro that will benchmark a given form `n` times. It is thus slightly different in its workings and will report different characteristics as a result. Caveat mergor.
- The actual `bench` function and `benchn` macro are not nice to look at. I already compromised by sacrificing …

Add a Benchmarking module

---

core/Double.carp
core/Statistics.carp
core/prelude.h
test/statistics.carp

This PR introduces the missing tests from #87, where the statistics module was extended but never got the love it needed. In the course of that, I also added the function `Double.abs` for taking the absolute value of a `Double`, and fixed a bug in `median-abs-dev`, which failed to adhere to its promise of taking said absolute value.
Cheers

Statistics, revisited

---

core/Char.carp
core/String.carp
core/prelude.h

This PR adds the functions `Char.from-int` and `Char.to-int`. They are useful for things like `(Array.range \a \z (Char.from-int 1))` (this will generate the letters a-z).
While debugging this, I also found a bug in `String.from-chars`. It allocated enough elements to hold the arrays contents, but not for the null terminator. This means that the last letter was always missing.<sup>1</sup>
Cheers
1. I should really start to write a test suite for the core libraries

Additions to Char

---

core/Int.carp
core/Long.carp
core/prelude.h
test/safe_artihmetic.carp

This PR introduces the functions `safe_add`, `safe_sub`, and `safe_mul` to the `Int`/`Long` types. It uses `__builtin_<type-shorthand><op>_overflow()` internally, which is a compiler builtin that has been supported by major compilers—at least Clang and GCC—for quite some time. I’m not sure whether it is perfectly portable, but it is hugely beneficial to correct software. The interface is always:
```
(safe-fun op1 op2 &res); => returns boolean saying whether op overflowed
```
You can thus write software like this:
```
(let [res 0]
(if (safe-add possibly-huge-number another-huge-number &res)
(IO.println "It overflowed! Oh no")
(IO.println &(String.append @"Result: " (Int.str res)))))
```
which is obviously good for error handling.
I personally consider it to be a huge win, but compatibility …

RFC: safe arithmetic

---

core/Int.carp
core/Long.carp
core/prelude.h
test/int_math.carp
test/long_math.carp

This PR is the third and last installment in our beloved series “Math functions”. It adds a few functions for Ints and Longs, namely `min`, `max`, and `abs`. I feel like math on integers is and should be restricted, but if you’re missing any functions, please let me know!
As always, a test suite is included.
Cheers

Math functions, Vol. III: Math for Ints and Longs (Closer)

---

src/Concretize.hs
src/TypeError.hs

This PR introduces a crude (?) checker that validates the contract of the main function: no arguments, and a return type of either `Int` or `()`. It introduces two custom error messages to accomplish that.
Cheers

Added special cases to typecheck main function

---

core/Test.carp

This PR introduces a change to the `with-test` macro that makes it return the number of failed tests, making it easy for e.g. a bash script to check whether anything has failed in the test suite.
Cheers

Tests return non-zero on failure

---

core/Double.carp

This PR improves the precision of π and e. While working on the physics library I realized that the low-precision versions we had degraded the precision of my calculations.
Cheers

Improve precision of π and e

---

src/Eval.hs

This PR adds a function `macro-error` to `Eval`. This function provides a mechanism to abort compilation from a macro, and is intended to be used when the macro occurs an unfixable error during expansion, i.e. was called with the wrong arguments.
```
(defmacro one-arg [:rest args]
(if (= (count args) 1)
(car args)
(macro-error "one-arg needs to be called with exactly one argument.")))
```
Cheers

Added macro-error function

---

core/sdl.carp

Hi,
I use Ubuntu16.04 to build examples/game.carp, but I got the following error message:
```
Welcome to Carp 0.2.0
This is free software with ABSOLUTELY NO WARRANTY.
Evaluate (help) for more information.
./out/main.c:3:10: fatal error: 'SDL.h' file not found
#include <SDL.h>
^
1 error generated.
carp: callCommand: clang ./out/main.c -o ./out/a.out -D_THREAD_SAFE -I/usr/local/include/SDL2 -fPIC -lSDL2_image -lSDL2 -L/usr/local/lib -lm -I/home/tamamu/Carp/core/  -g  (exit 1): failed
```
On my Ubuntu (and other typical Linux OSes), SDL has been installed under `/usr/include/`, so I added the path to `core/sdl.carp`.
Thanks.

Add CFLAG to build on typical Linux OSes

---

core/Test.carp
core/Vector.carp
examples/test.carp
test/double_math.carp
test/float_math.carp
test/int_math.carp
test/long_math.carp
test/safe_artihmetic.carp
test/statistics.carp
test/vector2.carp
test/vector3.carp
test/vectorn.carp

This PR simplifies the Test module. Specifying which `=` and `str` functions to use is not necessary anymore. If you do want to use your own comparison operation, this PR also introduces a new function called `assert-op`, which is similar to `assert-equal` but takes another argument that is a function, like so:
```
(assert-op my-test-state
1.0
1.0000000000001
"1.0 and 1.0000000000001 are approximately equal"
Double.approx)
```
Cheers

Simplify Test module

---

core/Long.carp
core/core.h

This PR adds `to-int` and `from-int` to the `Long` module. These operations are not safe, i.e. you might lose precision—it is just casting after all.
Cheers

Added int conversion to long module

---

core/Array.carp
core/Char.carp
core/Int.carp
core/Long.carp
core/Macros.carp
core/core.h
test/array.carp
test/int_math.carp
test/long_math.carp

This PR introduces... Well, I’m running out of catchy descriptions. Basically I was doing some Project Euler problems with Carp and noticed a few missing functions.
This PR introduces:
* `Array.first`: get the head of an `Array`
* `Array.last`: get the last element of an `Array`
* `Char.=`: I can’t believe this wasn’t there already
* `Int.even?`/`Int.odd?`: tests whether number is even or odd (also introduced to `Long`)
* `swap!`: a macro that swaps two values in place, compiles to this:
```
; if called as (swap! a b)
(let [tmp b]
(do
(set! &b a)
(set! &a b)
)
)
```
That’s all! A few tests are also included.
Cheers
PS: This will most likely conflict with #116. I’ll resolve that conflict after you’ve figured out what you want to merge first.

Miscellaneous fixes

---

core/Interfaces.carp
core/Vector.carp
examples/vector.carp
test/vector2.carp
test/vector3.carp
test/vectorn.carp

This PR adds arithmetic functions and reference arithmetic functions. This required that we rename the arithmetic functions in the Vector modules, because `*` and `/` don’t adhere to the interface.
I also took the liberty of fixing the tests and examples.
Cheers

Arithmetic interfaces

---

core/Macros.carp
test/control_flow.carp

This PR adds the macros `when` and `unless`. Those are single-branch alternatives to `if` that are of type `()` and thus only make sense when they’re side-effectual.
```clojure
(let [x 0]
(when true
(set! &x 1))) ; x will be 1
(let [x 0]
(unless false
(set! &x 1))) ; same
```
Cheers

Add when and unless macros

---

core/Macros.carp
core/Statistics.carp
test/macros.carp
test/statistics.carp

This PR introduces a few useful macros to the standard library. It also changes the behavior of `cond`.
- `do-let`: combines `let` and `do`.
- `defn+`: combines `defn` and `do`.
- `comment`: comments a block of code by ignoring the forms passed into it.
- `forever`: runs a sequence of forms forever.
- `case`: simple equality matching, similar to `case` in Scheme.
I took the liberty of changing the definition of `cond` to expand into a last `if` statement if the number of forms  is even. That way it might still fail when type-checking, but not silently remove the last conditional clause. This is a net positive, but maybe using `macro-error` instead would be even better.
Some test cases are attached, although many of these macros are hard to test.
Cheers

Add useful macros to the standard library

---

src/Eval.hs

This PR fixes the section in `commandProjectSet` that was marked as `TODO`. It checks the return value of the call to `eval`, and prints appropriate error messages when something goes wrong.
Cheers

Fix error conditions on project-set!

---

examples/benchmark_mandelbrot.carp
examples/benchmark_n-body.carp

These are benchmark tests from [benchmarksgame.alioth.debian.org](http://benchmarksgame.alioth.debian.org/).
This is not an attempt at making it the fastest, only to port the simple C code to Carp.

Added Mandelbrot and N-body bechmarking examples 

---

core/core.h

When reading a non-existing file using `read-file`, currently a segfault happens.
This is more of a hack though. Maybe this function could return a `Maybe` type?

Fixed segfault in read-line when file doesn't exist.

---

core/sdl.carp
src/Eval.hs

This PR introduces a few fixes to problems that I ran into while working on anima.
1. `SDL_Renderer` was used as a type, but never registered. This seems to be possible when registering functions, but it’s not great.
2. `=` in macros wasn’t able to compare symbols. This is useful when rewriting expressions conditionally, though.
I also found that there is a certain lack of operators. `>`, `<`, `and`, `or`, and `not` should IMO be implemented. I could do that. What do you think?
Cheers

anima fixes

---

src/Eval.hs
test/macros.carp

This PR introduces `>`, `<`, `and`, `or`, and `not` to the macro system. It also generalizes `=` to work on all numeric types. This was discussed in #142.
A test suite is attached.
Cheers

Add logic and arithmetic macros

---

core/Float.carp
core/core.h

This PR adds `Float.from-int`, which was notably absent from conversions between numeric types. It also fixes the signature of `Float.to-int`, which claimed it took a `Double` as argument.
Cheers

Add Float.from-int

---

app/Main.hs

Hi Erik, please do check this work a bit extra if you dont mind. I checked with the repl that core.h is not included anymore, but sadly I'm not a Haskell wizard (yet) :-) 
Merry Christmas.

Fix for --core-flag

---

core/Macros.carp
test/macros.carp

This PR (re-)introduces the varargs macros `and*`, `or*`, `str*`, and `println*`. `str*`/`println*` produces pretty ugly strings for now, because it calls `str` on Strings (you can observe that behavior in the last included test case, "str* macro works as expected".
Cheers

Add varargs macro

---

app/Main.hs
core/Bool.carp
core/Char.carp
core/Double.carp
core/Dynamic.carp
core/Float.carp
core/Format.carp
core/Int.carp
core/Interfaces.carp
core/Long.carp
core/String.carp
core/core.h
src/Commands.hs
src/Eval.hs
test/format.carp

This PR fixes #108 and adds formatted strings. It is fairly big and introduces a breaking change, so review with caution!
It adds the dynamic functions `+`, `-`, `*`, and `/` and the dynamic module `String` containing the functions `char-at`, `index-of`, `substring`, and `count`. I refrained from making `count` generic, but that could be discussed as well.
I also made registering new commands more convenient, with an arity that then gets checked at dispatch time, which is a little more convenient than writing an error branch for every function. Multi-arity commands are TBD.
I also added the interface `format`, which takes a string and a thing and returns the string representation of that thing (so its `sprintf` with one argument). This is used in the `fmt` macro, which splits …

Add formatted string output

---

core/Format.carp
test/format.carp

This PR fixes printing `%` in `format`.
Tests were updated.
Cheers

Fix printing percent in format

---

core/Array.carp
core/Char.carp
core/Macros.carp
core/String.carp
test/array.carp
test/string.carp

This PR adds a whole bunch of functions to the standard library:
- `(aupdate a i f)`: like `aset`, but with an update function being applied to the old element instead of overwriting it
- `(aupdate! a i f)`: the same, but in-place.
- `(swap a i j)`: swaps the array elements at indices `i` and `j`.
- `(swap! a i j)`: the same, but in-place.
- `/=`: Add not equal to Char. Refactor in the future to make `/=` a macro.
- `c[ad]{2,4}r`: the deeper friends of `car` and `cdr`, as dynamic functions.
`update!`: same as `set!`, but with a function updating the old value instead of plainly overwriting it.
- `(substring s i j)`: get the substring of s from index i to j
- `(prefix-string s j)`: get a prefix string from s to index j.
- `(suffix-string s i)`: get a suffix string from s from index i …

Add a few more functions to stdlib

---

src/Commands.hs
src/Util.hs

- `AddIfNotPresent` should append to list (or at least in this case), so `cflag` & `libflag` are in the right order.
- Fix: `libflag` should fill `projectLibFlags`, instead of `projectCFlags`.

Small project cflag/libflag fix

---

test/array.carp

This PR adds a test case for `sort`.
I also want to start a conversation around whether we should have a generic function `cmp` or make it an interface. A problem with the current implementation of `sort` is that `cmp` takes refs, and that might require us to copy things. There are a few different strategies with which we could avoid this; for instance, we could change `sort` not to work with refs. That would only defer the problem of copying, though. If we made `cmp` an interface, we would have to copy a lot of code, except in the places where we wouldn’t, with strings for example.
I’m not entirely sure how to go about this.
Cheers

Add test case for sort

---

core/Format.carp

This PR fixes a code generation/macro expansion bug in `fmt`, and removes an unnecessary check.
Cheers

Fix bugs and unnecessary check in fmt

---

core/Array.carp
core/Double.carp
core/Float.carp
core/Int.carp
core/Interfaces.carp
core/Long.carp
core/Statistics.carp
src/ArrayTemplates.hs
test/array.carp

This PR canges the interface of `sort` from `Ref Array` to `Array`. We also introduce a function `cmp` that returns `0` when both of its arguments are equal, `-1` when the first is smaller than the second, and `1` otherwise. For this to work we also have to define `=`, `<`, and `>` for references to numeric types. In the long run, we should also implement `<` and `>` for other types (e.g. characters), in which case we should then also backport this change.
Cheers

Better sort

---

examples/sorting.carp
run_carp_tests.sh

This PR fixes the sorting example after our API change and simplifies the `run_carp_tests` script.
Cheers

Misc fixes

---

src/Obj.hs

This PR fixes the dependency depth of interrelated types by adding a bit of weight (`1`, to be precise) for types that depend on others.
Cheers

Fix dependency depth calculation

---

examples/benchmark_mandelbrot.carp

Small cleanup: this replaces the local string-append macro with the stdlib string-join macro in the mandelbrot benchmark.

Use stdlib's string-join instead of custom macro in mandelbrot benchmark

---

core/Macros.carp

Running this:
```
(use IO)
(defn main []
(for [x 0 10]
(println "test")
(println "other")))
```
Prints lots of (10) `test`s, but **no** `other`: the rest of the for "body" is ignored in the macro.
I feel that `for` should be a `do` by default, though.

Print macro error (warning) when using more then one expression in body

---

app/Main.hs
core/Array.carp
src/ArrayTemplates.hs
test/array.carp

This PR addresses #125 by rewriting `repeat`, `replicate`, and both flavors of `map` in Carp. It also introduces `allocate` to obtain a fixed size array.
Cheers

Array allocation

---

src/Concretize.hs
src/TypeError.hs

This PR makes failed concretization a little more readable. It’s still a pretty obscure error, but at least it’s not as scary anymore.
Cheers

Better error on failed concretization

---

core/Array.carp

This PR fixes the loop start point for `Array.max` and `Array.min`. The loop used to start at `0`, but we already take the head of the array as a start point for the accumulator, so we don’t have to visit it again.
Cheers

Better loop start for Array.max/min

---

.gitignore
src/Commands.hs

This PR changes the commands to actually honor the project title. This means that compilates will now not be named `a.out` or `lib.so` anymore, but will actually be called the project title.
I also simplified the handling of the `out/` directory in .gitignore. Because `keep.txt` is already part of the repository, that won’t change anything.
Cheers

Honor project title

---

src/Commands.hs

This PR introduces the capability of building projects with spaces in the title. Before it, this failed both in the build and run steps.
Cheers

Allow executables with spaces

---

src/Parsing.hs

This PR fixes two bugs in the pattern parser.
The first bug is that the main parser of bracket classes was allowed to parse empty sequences infinitely (fixed by making the `many` catch-all parser a `many1`).
The second error was that within the escapes, I forgot to add a few characters that are allowed to be escaped.
Cheers

Fix errors in pattern parsing

---

README.md

This PR updates the license notice to 2018. We’re in March already! 😸 
Cheers

Update license notice

---

core/Pattern.carp
core/carp_pattern.h
test/string.carp

This PR adds a few useful string functions, as asked for in #94. It is not a complete port of the Emacs string library, but we’re getting there.
This PR introduces:
- `(in? s sub) : (Fn [&String &String] Bool)`: checks whether `sub` is contained in `sub`
- `(upper? s) : (Fn [&String] Bool)`: checks whether `s` only contains upper-case characters (or rather, anything but lower-case).
- `(lower? s) : (Fn [&String] Bool)`: checks whether `s` only contains lower-case characters (or rather, anything but upper-case).
- `(num? s) : (Fn [&String] Bool)`: checks whether `s` is numerical.
- `(alpha? s) : (Fn [&String] Bool)`: checks whether `s` is alphabetical.
- `(alphanum? s) : (Fn [&String] Bool)`: checks whether `s` is alphanumerical.
- `(hex? s) : (Fn [&String] Bool)`: checks whether `s` is …

Add useful string functions

---

core/Pattern.carp
core/String.carp
test/string.carp

This PR simplifies `split-by`. To that end, it introduces the function `Pattern.from-chars`.
Cheers

Simplify split-by

---

core/carp_pattern.h

See lines `626-629`. [Related StackOverflow question](https://stackoverflow.com/questions/1973572/can-the-input-and-output-strings-to-sprintf-be-the-same#1973595) 
Should fix #203.
Also, minor formatting.

Pattern.substitute sprint src & dest overlap = undefined behavior

---

core/carp_bench.h

Under POSIX clock_gettime and timespec are defined in time.h
I don't think we need sys/time.h

Adding time.h header to carp_bench.h to resolve bug #208

---

core/System.carp
core/carp_system.h
src/Emit.hs
test/args.carp

**This should be considered a WIP/RFC.**
This PR adds `System.args`, which is a Carp version of C’s `argc`/`argv` pair.
The system with which these are injected are pretty shoddy and rely on handrolled C, because I wasn’t entirely sure how to reuse the array templates here. It also relies on `Array_delete__String`, but doesn’t require it (again because I’m not sure how to do that when we’re emitting C).
Another open question for now: this requires us to readd a `malloc` dependency in `main`. We explicitly removed this a while ago to make it possible to rewrite a bunch of `core` for embedded systems if desired. How can we make sure this doesn’t break then? We could wrap it in an `ifdef` or such...
Cheers

Add System.args

---

core/core.h

Fixing build & test on Linux.
These headers are required as part of POSIX, so it is surprising it ever worked on Mac.
This built and passed all tests on my Travis for Linux and Mac.

Adding missing includes headers for POSIX wait and signals

---

CarpHask.cabal
docs/core/Array.html
docs/core/Bench.html
docs/core/Bool.html
docs/core/Char.html
docs/core/Debug.html
docs/core/Double.html
docs/core/Dynamic.html
docs/core/Float.html
docs/core/Geometry.html
docs/core/IO.html
docs/core/Int.html
docs/core/Long.html
docs/core/Map.html
docs/core/Pattern.html
docs/core/Statistics.html
docs/core/String.html
docs/core/System.html
docs/core/Test.html
docs/core/V2.html
docs/core/V3.html
docs/core/VN.html
docs/core/Vector2.html
docs/core/Vector3.html
docs/core/VectorN.html
docs/core/carp_style.css
docs/core/core_index.html
src/RenderDocs.hs

This PR replaces `lucid` by `blaze-html` to leverage its pretty printer. This leads to pretty HTML, which is a bit nicer to deal with. This is per request from @bjorn3 in #268.
It also means that this diff is super huge, sorry about that!
Cheers

docs: Change to pretty rendering

---

src/RenderDocs.hs

I introduced a bit of extra debug output in #269. This PR removes it.
Cheers

Remove debug output from render docs

---

core/Color.carp
docs/core/String.html

This refactors the `Color` module to actually use a `Map` instead of an association list. This simplifies the lookup algorithm.
Cheers

Colors: use map

---

src/Commands.hs

This PR introduces escaping of `\` in macro stringification, because otherwise the C compiler will complain about invalid escape sequences. For an example, try: `(assert (= \. \+))`.
Cheers

Escape chars in macro stringification

---

examples/parse_me.h
headerparse/Main.hs

This PR extends the parts of the header parser that deal with macros. It allows for function-like macros (i.e. macros that take arguments), and multi-line macros.
“Test” cases are included in `examples/parse_me.h`.
Cheers

Headerparser: Parse function-like macros and multiline macros

---

headerparse/Main.hs

This PR removes an unnecessary import of `Debug.Trace` that I introduced into `headerparse` (oops).
Cheers

headerparse: remove unnecessary import of Debug.Trace

---

bench/map.carp
core/Map.carp
docs/core/Map.html

This PR adds a few changes to map that make it simpler and more performant:
- remove the `Entry` type, as it is equivalent to `Pair`
- add a `SetBucket` type to avoid carrying around useless values in hashsets
- Fix a few docstrings
- Add benchmarks
Cheers

Simplify map

---

src/Scoring.hs

This PR fixes #281 by adding 1 to the scoring of aliases. `deftype` generates function aliases that depend on the type being defined, so they need to come after. The increment expresses this dependency.
A similar comment was added above the change.
Cheers

compiler: fix #281

---

src/ColorText.hs

This PR fixes #283. The original reset in `strWithColors` was ANSI code `37`, which is `white`. It should’ve been `0`, which is `reset`.
Cheers

Fix discoloration on reset

---

docs/LanguageGuide.md

This PR adds the `Map` type to the types introduced in the Language Guide.
Cheers

Add map to std types in docs

---

test/short_circuiting.carp

When running the carp test suite, I noticed that the results were not being printed at the end of this test. I Implemented this change and the results printed upon re-running the tests.

Print short-circuiting test results

---

src/Commands.hs
src/StartingEnv.hs
test/macros.carp

This PR adds `Project.get-config`, the getter alternative to `Project.config`. This is there to simplify use cases like in #270 where you might want to fing out values like `output-directory` from within the program.
Cheers
PS: I noticed that a few properties of `Project` are missing in `Project.config`. WIll add those in a separate PR.

add Project.get-config

---

core/Test.carp
docs/core/Test.html
test/array.carp
test/char.carp
test/control_flow.carp
test/double_math.carp
test/float_math.carp
test/format.carp
test/heap.carp
test/int_math.carp
test/long_math.carp
test/macros.carp
test/map.carp
test/memory.carp
test/nested.carp
test/pattern.carp
test/random.carp
test/safe_arithmetic.carp
test/short_circuiting.carp
test/sort.carp
test/statistics.carp
test/string.carp
test/vector2.carp
test/vector3.carp
test/vectorn.carp

As discussed in #290, this change moves the printing of test results to the `with-test` macro. Additionally, I renamed the misspelled `test/safe_arithmetic` file.
Tested using the `run_carp_tests.sh` script and observing that the results are the same as before the change.

Print results as part of test macro

---

src/Concretize.hs
test/fixture_foo.h
test/regression.carp

This PR fixes mode resolution for multisymbols during concretization, by which I mean it fixes #288.
A test case is included. It’s in a file called `text/regression.carp`, in which I intend to test for any regressions for fixes like this one.
Cheers

Fix mode resolution for multisymbols

---

core/Char.carp
docs/core/Char.html
test/char.carp

This PR adds the functions `Char.upper-case` and `Char.lower-case` to test whether a character is upper or lower case. It will only return `true` for characters that are actually alphabetical, which means that e.g. `!` is neither upper nor lower case.
Cheers

Add Char.upper-case and Char.lower-case

---

core/Array.carp
core/Filepath.carp
core/Vector.carp
docs/core/VectorN.html
src/Types.hs

This PR changes the core/stdlib to use closures instead of helper functions for `map` et al.
This uncovered a bug in emitting closures: there was a stray `.` in the name that was passed into the emitter (e.g. `_Lambda_VectorN.mag-sq_17`). This is probably due to `Emit.hs:188`, where we mangle any old name as if it was a single name. The simple fix for this was to add a new mangle rule that substitutes `.` by `_`. This is maybe a little hacky, but it works and is unintrusive. Maybe someone else has a better suggestion?
Cheers

Use closures in core

---

test/args.carp

Thanks for the project!
This PR just adds a couple of tests for `args.carp`, it assumes they are run with:
`carp -x test/args.carp`
or through the provided script:
`./run_carp_tests.sh`

Add tests for args

---

lines_of_code.sh

This PR adds the `headerparse` directory to the script `lines_of_code.sh`.
Cheers

Add headerparse to lines_of_code.sh

---

core/Random.carp
core/System.carp
core/carp_system.h
docs/core/IO.html
docs/core/System.html
examples/basics.carp
examples/guessing.carp
examples/updating.carp
test/random.carp

This PR changes the API of `Random.seed` to not take an argument, and instead use a good default (`System.nanotime`, another function that is new). If you really want to do seed yourself, use `Random.seed-from`, which is equivalent to the old version of `Random.seed`.
Cheers

Better random

---

CarpHask.cabal
src/ColorText.hs

This PR adds a check for output coloring that restricts colors to TTY devices (i.e. terminals). This prevents files from being clobeered with ANSI escape codes.
One downside of this is that it depends on the `unix` package, which is kind of a bummer, but seems to be the only way.
Cheers

Compiler: only use colored errors on ttys

---

CarpHask.cabal
docs/core/Array.html
docs/core/Bench.html
docs/core/Char.html
docs/core/Debug.html
docs/core/Double.html
docs/core/Float.html
docs/core/Geometry.html
docs/core/IO.html
docs/core/Int.html
docs/core/Map.html
docs/core/Pattern.html
docs/core/Statistics.html
docs/core/String.html
docs/core/System.html
docs/core/Test.html
docs/core/Vector2.html
docs/core/Vector3.html
docs/core/VectorN.html
src/RenderDocs.hs

This PR adds support for Markdown (more specifically, CommonMark) to docstrings in Carp. This should simplify generating rich, good documentation.
This is a proposal and should be treated as such. If people have strong feeling for or against this, I’d like to hear it and why!
Cheers

Add suport for markdown in docstrings

---

core/Array.carp
core/Map.carp
core/Vector.carp
docs/core/Array.html
docs/core/Map.html
examples/basics.carp
examples/bugs.carp
examples/map.carp
test/map.carp
test/memory.carp

This PR adds `Map.put!`, `Map.remove!`, `Set.put!`, and `Set.remove!`. They avoid copying the map/set, but also take ownership over the data.
It also changes the type signature of `Array.reduce` to take ownership of the accumulator to reduce the need for copying there as well.
Test are included, examples are fixed.
Cheers

Add performance-oriented patches

---

core/Pattern.carp
core/String.carp
core/carp_pattern.h
test/pattern.carp

This PR adds `Pattern.find-all`, which behaves similarly to `Pattern.find`, but instead of only finding the index of the first occurrence, it will return an array of all occurrences within the provided source string. It also updates to `String.lines` to use this algorithm, which speeds up `String.split-by` by almost an order of magnitude because it reduces the number of Array allocations to one.
Of note is that this introduces the function `Pattern_internal_update_int_array`, which is extremely similar to what `Array_push_back__int` would generate (but with C in-place updates).
Test cases are included!
Cheers

Add Pattern.find-all

---

src/Eval.hs

This PR introduces an error case to `load` that gives a good error message if it is handed the wrong type. The compiler used to die before that.
I also took the liberty to remove a bunch of dead branches that checked the arity of commands (they are dead, because the arity is already checked before by the closure generated by `addCommand`).
Cheers

Error if load gets handed the wrong type

---

examples/life.carp

Found a typo in the game of life example causing it to not compile under Linux (due to case sensitivity).

Fixed SDL import capitalization in Life example

---

core/Heap.carp
core/Sort.carp
docs/core/Array.html
test/sort.carp

This PR adds `Array.sort-by`, `Array.sorted-by`, and `Array.sort-by!`, which are generalized versions of the `sort` versions that take custom comparator functions.
I think @chrisosaurus wante to add this anyway.
Test cases are included!
Cheers

Add sort flavors with custom comparators

---

core/carp_bool.h
core/carp_char.h
core/carp_double.h
core/carp_float.h
core/carp_int.h
core/carp_long.h
core/carp_memory.h
core/carp_safe_int.h
core/carp_stdbool.h
core/core.h

This PR adds our own version of `stdbool.h` to remove the C99 dependency. This should solve #332.
Cheers

Remove stdbool dependency

---

core/Map.carp
core/Tuples.carp
test/map.carp

Some additions I think would fit the standard library.
Had to add the Pair equality to be able to write the tests for to-array :)

Map.to-array and Set.to-array functions, equality for non-ref Pairs

---

LUA_LICENSE

This PR fixes #370 by changing the referred file from `src/carp_regex.h` to `core/carp_pattern.h`. The file was renamed early on, and the directory path was just wrong!
Cheers

lua license: fix referenced file

---

core/Vector.carp
docs/core/Array.html
docs/core/Bench.html
docs/core/Bool.html
docs/core/Char.html
docs/core/Debug.html
docs/core/Double.html
docs/core/Dynamic.html
docs/core/Float.html
docs/core/Geometry.html
docs/core/IO.html
docs/core/Int.html
docs/core/Long.html
docs/core/Map.html
docs/core/Pattern.html
docs/core/Statistics.html
docs/core/String.html
docs/core/System.html
docs/core/Test.html
docs/core/Vector2.html
docs/core/Vector3.html
docs/core/VectorN.html
docs/core/core_index.html
docs/core/generate_core_docs.carp
examples/reptile.carp

This PR refactors the Vector module to pull the types out of the module and rename them to the module they belong in. It also “generifies” the type, so that they’re not bound to the `Double` type. This means we can now also have `Int` vectors and such! Yay!
Cheers

core: refactor the vector module; generic types and use module system

---

src/Parsing.hs
test/regression.carp

This PR fixes the issue that we encountered in #358 where the parser for escaped quotes was just a little too greedy. This PR special-cases this a bit more, which sadly makes the string parser a little more complex. Do tell me if there is a better way to do this!
I also added a test case!
Cheers

Fix string escaping of backslashes (#358)

---

test/memory.carp

This PR changes one of the filter memory tests so that we test the shrinking. It’s very basic and there a re probably more complex examples that are more likely to contain a memory bug, but this should be useful as a first smoke test.
Cheers

memory test: test shrinking

---

app/Main.hs
docs/core/core_index.html
docs/core/generate_core_docs.carp
src/Commands.hs
src/Obj.hs
src/RenderDocs.hs

This PR adds properties to customize a bunch of properties about documentation generation, namely:
- the logo
- the prelude
- the URL
- the styling (CSS) URL
It doesn’t do everything described in #374, most notably it doesn’t allow for customized sections, but it’s a start!
Cheers

Make some properties about the documentation generator configurable

---

src/Parsing.hs
test/pattern.carp

The patterns parser currently disallows escaped `.` and `*`. They should be allowed, because otherwise they cannot be used as literals in a pattern!
Cheers

Add two special symbols to patterns parser

---

CarpHask.cabal
core/core.h
src/ColorText.hs
stack.yaml

I think this is the minimal set of changes that were needed to build Carp on Windows. These changes will at least allow one to compile on Windows using gcc. Compiling with the Windows compiler (cl.exe) still doesn't work due to some specific Posix functions that are used in some carp header files, specifically carp_system.h's clock_gettime usage. There may be other's, too, that will prevent compilation on Windows using cl.exe.

Build Carp on Windows

---

src/Eval.hs

When we `load` a Git repository, we should execute `git fetch --all --tags` instead of just `git fetch`, because that way we get all of the tags as well (which is great for versioning)!
Cheers

Fetch everything from git when loading

---

core/Int.carp
core/carp_int.h
test/regression.carp

This PR makes `Int.MAX` and `INT.MIN` variables (aka proper rvalues), so we can take their references. This fixes #381!
Cheers

core: fix Int.MAX and Int.MIN references

---

core/Char.carp
docs/core/Char.html
test/char.carp

This PR adds the utility functions `alpha?`, `num?`, and `alphanum?` to the `Char` module. Test cases are included.
Cheers

Add Char.alpha?, Char.num?, and Char.alphanum?

---

src/Commands.hs

This PR adds `docs-styling` to the list of settable project properties, because I forgot to add them in #377!
Cheers

Add docs-styling to project config setters

---

src/Concretize.hs
src/Constraints.hs
src/GenerateConstraints.hs
src/TypeError.hs

This PR introduces context for type errors and it makes the array error messages especially nice. Here is an example error message for heterogenous types within an array:
```
I can’t match the types 'Int' and '&String' within `[1 2 "lol"]`.
I inferred the type of the array from the first element of the array 1 : Int
At line 1, column 9 in '/Users/veitheller/Documents/Code/Github/carp/carp/t.carp'
Whereas the third element in the array is "lol" : &String
At line 1, column 13 in '/Users/veitheller/Documents/Code/Github/carp/carp/t.carp'
```
I hope this makes for a better experience!
Cheers

Provide more context for error messages on type errors

---

CarpHask.cabal
src/Commands.hs
src/Emit.hs
src/Eval.hs
src/Expand.hs
src/GenerateConstraints.hs
src/InitialTypes.hs
src/Lookup.hs
src/Obj.hs
src/TypeError.hs
test/output/test-for-errors/no_forms_in_match.carp.output.expected
test/output/test-for-errors/type_mismatch.carp.output.expected
test/output/test-for-errors/uneven_nr_of_forms_in_match.carp.output.expected

This PR adds some more better error messages and, as such, build on #394 and #395.
Some highlights:
```
Invalid type definition for 'x':
The number of members and types is uneven: 'a' at line 1, column 13 in '/Users/veitheller/Documents/Code/Github/carp/carp/t.carp'.
Because they are pairs of names and their types, they need to be even.
Did you forget a name or type?
```
```
I didn’t understand the `defn` at line 1, column 1 in '/Users/veitheller/Documents/Code/Github/carp/carp/t.carp':
(defn x [a b c d] a b c)
Is it valid? Every `defn` needs to follow the form `(defn name [arg] body)`.
```
```
I couldn’t find the symbol 'Array.ast' at line 15, column 12 in '/Users/veitheller/Documents/Code/Github/carp/carp/t.carp'.
Maybe you wanted one of the following?
Array.aset
Array.aset!
Array.last …
```

Better error messages (2/?)

---

docs/LanguageGuide.md

Based on the docs, I expected that `defdynamic` would allow me to define and use a function at the REPL. Instead I got the following error:
```
> (defdynamic square [x]
(* x x))
Invalid args to `defdynamic`: (defdynamic square [x] (* x x))
(did you try to define a dynamic function - use 'defndynamic' instead) at REPL:1:1.
```
Definitely props on the helpfulness of the error message, which makes this an easily overcome issue. However, I'd like to propose this change to the guide so that any other newcomers don't hit a bump the first time they try something.

Change "defdynamic" to "defndynamic" in guide

---

src/Parsing.hs

This PR fixes the problem discovered by @cnasc in #398; it simplifies the parser and doesn’t accept `-` as valid numbers anymore.
Cheers

Simplify digit parser, correct `-` parse

---

core/Array.carp
core/Int.carp
core/Interfaces.carp
core/Random.carp
docs/core/Array.html
docs/core/Int.html
docs/core/Statistics.html
test/array.carp

This PR generalizes `Array.range`. Prior to this change, `Array.range` assumed that we could use some `Int` functions on the input that prevented it from being generalized. By using `to-int` and making `to-int` and `from-int` interfaces, we can use other types in the function as well, and do cool stuff like `(Array.range 0.0 10.0 0.5)`!
A test case is included.
Cheers

Make `Array.range` more general

---

app/Main.hs
src/Lookup.hs
src/Repl.hs

This PR injects the starting environment into the REPL autocompletion. This means that all standard functions can now be autocompleted.
You can try this out by typing `In` in your REPL, having it autocomplete (by hitting TAB) to `Int.`, and then, if you hit TAB again, see a list of functions defined in the `Int` module!
Cheers

REPL: better autocompletion based on starting environment

---

docs/core/Dynamic.html
src/Commands.hs
src/StartingEnv.hs
test/macros.carp

This PR adds the dynamic function `Symbol.join`. It can be used to prefix or suffix symbols inside dynamic functions or macros, for instance.
A test case is included.
Cheers

core: add Symbol.join

---

core/System.carp

I was running through the docs and it seemed like get-arg was incorrectly documented based on the signature. It looks like the doc for get-args-len was reassigned to get-arg.

Fix doc for get-args-len

---

core/carp_int.h
core/core.h

This PR removes some headers—or makes them conditional—that are either unnecessary or only needed under certain circumstances (like `assert`, which is only used for unoptimized builds).
The test cases still compile and run, so this should be fine.
Cheers
CC @mathk

Remove headers that are problematic for embedded applications

---

src/Eval.hs

Function definition identifiers cannot begin with digits. This PR contains changes to ensure identifiers (in defn, def, etc.) can only begin with valid characters (symbol Xobjs).
resolves #414

Return errors on non symbol identifiers

---

src/Eval.hs

This PR follows up on #419 and makes sure that all symbols put in the head of `defn`s are unqualified.
Cheers
CC @scolsen

Require defn symbols to be unqualified

---

src/Eval.hs
src/Expand.hs

This PR fixes #421 by returning an error on invalid `the` expressions instead of trying to expand them.
`the` expressions with invalid bodies are now detected everywhere, and appropriate error messages are returned.
Cheers

Return an error on invalid the expression

---

src/Eval.hs
src/Obj.hs

I've added a few more checks to `Eval.hs` to ensure the identifiers passed to `def` and `deftype` members (e.g. `(deftype Name <[members Int]>)`) are unqualified symbols. This prevents the evaluator from allowing instances in which, for example, Nums are passed to defs, `(def 4 5)`, resulting in invalid C. 
@eriksvedang @hellerve Let me know what you think!
...also, let me know if there are other cases we should catch with this. If not, we can probably close up #414 once this looks ok!

Return errors on non unqualified symbol identifiers for def and deftype

---

app/Main.hs
src/Commands.hs
src/Obj.hs
src/RenderDocs.hs

This PR introduces the Project configuration variable `docs-generate-index`, which is a boolean indicating whether the index file should be generated. I often do not want to generate it for many of my projects, so I manually have to delete the file after generation afterwards.
This PR is part of my ongoing work on #374.
Cheers

docs: Make generating index.html optional

---

core/Macros.carp
test/macros.carp

This PR adds the `while-do` macro to accompany the existing `let-do` and `defn-do`.
Cheers

Add while-do macro

---

core/Result.carp

This PR fixes a typo in the docstring of `Maybe.to-result`.
Cheers

core: typo fix in Maybe.to-result

---

core/Maybe.carp
test/maybe.carp

This PR adds `Maybe.ptr` and `Maybe.from-ptr`, which convert Maybe values to pointers (and `Nothing` to `NULL`). This shoudl fix #287, although it isn’t quite automatic conversion.
Cheers

Add Maybe.ptr and Maybe.from-ptr

---

core/Map.carp
core/Tuples.carp
docs/core/Map.html
test/map.carp
test/tuples.carp

This PR adds `Pair.reverse` and `Map.reverse`. `Pair.reverse` switches the `a` and `b` members of a pair, whereas `Map.reverse` switches keys and values.
Cheers

Add Pair.reverse and Map.reverse

---

core/IO.carp
docs/core/IO.html
test/regression.carp

This PR fixes #286 by making the result of `IO.read->EOF` a `Result` type.
A regression test case is included.
Cheers

Safe IO.read->EOF

---

core/Pattern.carp
docs/LanguageGuide.md

This PR fixes the pattern documentation. In the Language Guide it fixes a few typos, and in the docstrings, it fixes the format to fit our new documentation format.
Cheers

Fix pattern docs

---

docs/core/Dynamic.html
src/Commands.hs
src/Emit.hs
src/StartingEnv.hs
test/fixture_file.txt
test/macros.carp

This PR adds `Dynamic.read-file`, which embeds file contents into a Carp source file at compile time.
Cheers

dynamic: add read-file

---

src/Emit.hs

This PR changes the emitter to not emit empty sumtype cases. Instead, we’re emitting just a comment and keep the tag.
Cheers

Do not emit empty sumtype cases

---

src/Parsing.hs

This PR restricts the parser to only parser a form as special form when it’s unqualified. I’m quite intrigued that we haven’t seen this before, but I guess you don’t often try to define something using `String.def` or the like.
This PR fixes one of the bugs in #433.
Cheers

Restrict special forms to unqualified symbols

---

src/Eval.hs
src/InitialTypes.hs
src/Obj.hs
src/Qualify.hs
src/TypeError.hs
src/Util.hs

This change ensures let bindings cannot have invalid identifiers, such as numbers `(let [4 4] true)`. 
I've also adopted guard syntax to handle potential failure conditions.

Only allow Symbols in Let bindings

---

src/Emit.hs

This PR fixes a bug in Emit that emitted incorrect C code in the error message of unmatched sumtype cases. This is especially important on Windows, where filepaths often contain backslashes.
Cheers

Quote backslashes in file info in Emit

---

core/Macros.carp

Adds the `defproject` macro. 
This macro enables you to specify a project configuration with slightly less redundancy. Instead of writing:
```clojure
(Project.config "title" "foo")
(Project.config "docs-directory" "bar")
(Project.config "search-path" "baz")
```
users can write:
```clojure
(defproject "title" "foo"
"docs-directory" "bar"
"search-path" "baz")
```
etc.
Note that at the moment this is a fairly 'dumb (or transparent)' macro--It doesn't do any additional type checking against the configuration, so improper types will cause the typical errors, and it doesn't have any special handing for cases in which the user provides an odd number of arguments.

Macros: Add defproject macro

---

docs/Libraries.md

The syntax for loading git libraries didn't work for me on Linux. Changing it to that in this commit works.

Fix docs syntax of git url for loading libraries

---

README.md
core/Array.carp
core/Statistics.carp
core/Tuples.carp
test/array.carp
test/memory.carp

- Made Array.find wrapped in a Result (tests included, though I couldn't run it)
- Made Array.maximum and Array.minimum safe (tests included, though I couldn't run it)
- Made Array.index-of safe (tests included, though I couldn't run it)
- Added Pair.zero to maintain compatibility with Array.maximum and Array.minimum
- Also some typo fixes in Array module doc string
Please, try to run the tests on your machine

Make Array module safer

---

src/Eval.hs
src/InitialTypes.hs
src/TypeError.hs
test-for-errors/duplicate_binding.carp
test/output/test-for-errors/duplicate_binding.carp.output.expected

This PR fixes #320 by analyzing `let` bindings for duplicates and returning an error message if there are any.
A test case is included.
Cheers

Catch double definitions in let

---

core/Map.carp
test/map.carp

This PR adds `Map.put!` and `Set.put!`, which function as the normal `put` operations, but in-place and without taking ownership.
Cheers

Add Map.put! and Set.put!

---

core/Macros.carp
test/macros.carp

This PR adds `const-assert`, a dynamic function that behaves like `assert`, but gets run at compile time.
Cheers

Add const-assert

---

core/Map.carp

Map: Fix small typo in doc empty?

---

core/Pattern.carp
test/string.carp

This PR changes `String.words` to also split words on newlines, which is probably the desired behavior in most cases.
Test cases were updated.
Cheers

Also split by newline in String.words

---

headerparse/Main.hs

This PR fixes the headerparse to accept input such as:
```c
int x(); // this comment destroys headerparse
void y();
```
Inline comments made the header parser choke before because it expected the rest of the line to consist of `stringOrTab` parsemes.
Cheers

Fix headerparse for comments after decl

---

core/Bench.carp
core/Format.carp
core/Macros.carp
core/String.carp
core/Test.carp
core/carp_pattern.h
core/carp_string.h
docs/LanguageGuide.md
docs/Todo.org
examples/basics.carp
test/array.carp
test/memory.carp

This PR removes `StringCopy.append` and replaces all instances of it by `String.append`, which is always a better idea.
It also removes it from `Todo.org` and the Language Guide.
Cheers

Remove StringCopy.append

---

core/Map.carp
docs/core/Map.html
test/map.carp

This PR makes all the higher-order functions  in `Map` and `Set` be non-owning.
Test cases were updated.
Cheers

Make map’s higher order functions take refs

---

docs/Todo.org
src/Eval.hs
src/Obj.hs
test/regression.carp

This PR fixes a bug where sumtype definitions with a single case didn’t work. It works now, and a regression test has been added.
Technical aside: the problem was that the classification of “regular deftypes” and sumtypes was the number of forms in the definition, which doesn’t word. Instead, we now look at the length and if the element in question is an array. If it is, then it’s a regular type, otherwise it’s a sumtype.
Cheers

Correctly classify sumtypes with single case

---

src/Concretize.hs
src/Obj.hs
src/Util.hs

This change adjusts the way in which function nest levels are
incremented to ensure top level lambdas are assigned the correct nest
level. Top level lambdas used to use their expressions as names,
resulting in invalid c. A check on nest levels in the lambda naming code
now prevents this.
Essentially, this change makes the following sorts of definitions in the REPL ok:
```clojure
[(fn [] ())]
(deftype Foo [f (Fn [] ())])
(Foo.init (fn [] ()))
```
Note that this *doesn't* cover sumtypes, which still can't emit valid C for lambdas. Looks like there's some other portion of the compiler that needs to be modified for Sumtypes to work with lambda/function members.
Please let me know about any stylistic preferences! I just used what Haskell I know to implement this, happy to reimplement in a …

Concretize: Fix top level lambda naming

---

docs/Todo.org

With the creation of #465 to #476, a bunch of issues found a new home and are moving out of the org file. This PR reflect that.
Cheers

Remove issuified todos from Todo.org

---

core/Macros.carp
src/Emit.hs
src/Eval.hs
src/Obj.hs

This PR adds a mechanism for “annotations”, which is what I call the prefixes that are often used in C by certain libraries—`GLFWAPI` and `EMSCRIPTEN_KEEPALIVE` spring to mind—to signal some kind of special behaviour of the function.
This is important for things like #294 where we need to emit it for the compiler.
A few adjustments to the emitter needed to be made to make sure it honours these annotations, but otherwise this change is relatively trivial, and extensible too!
In pretty great news, it now enables us to do things like this:
```clojure
(system-include "emscripten/emscripten.h")
(Project.config "compiler" "emcc")
(Project.config "title" "example.wasm")
(Project.config "output-directory" ".")
(add-cflag "-s ONLY_MY_CODE=1")
(defn dosth [i z] (Int.+ i z))
(annotate dosth …
```

Add annotations

---

src/Commands.hs

This PR makes compile-time `append` work on arrays instead of just lists.
Cheers

Make compile-time append work on arrays

---

src/Commands.hs
src/StartingEnv.hs

This PR adds `Symbol.prefix`, which prefixes a symbol with a module. `(Symbol.prefix 'Maybe 'apply)` evaluates to `Maybe.apply`.
Cheers

Add Symbol.prefix

---

core/Debug.carp
core/carp_memory.h
docs/core/Debug.html
examples/check_malloc.carp
run_carp_tests.sh

This PR introduces `Dynamic.check-allocations`, which sets a flag to check all calls to `malloc` and raise `SIGABRT` if they fail.
Built in response to #498.
Cheers

Optionally check malloc

---

core/Long.carp
core/Macros.carp

This PR adds the `todo` macro, which adds, well, TODOs to bindings. This gives a semantically clean place for adding TODOs, caveat emptors, nota benes, et al.
Cheers

Add todo macro

---

core/Format.carp

This PR introduces better error messages for `fmt` by telling the user which directive needs an argument and which argument needs a directive if they don’t match.
The directive printer is a little wonky, currently we will only display the first letter (which means it works for `%s` but not for `%.2f`). If you have better ideas—short of writing a parser for all kinds of directives—, please let me know!
Cheers

Better error messages in fmt

---

src/Commands.hs
src/StartingEnv.hs

This PR fixes #528 by streamlining `macro-log` and removing the duplicate. Specifically, you can now write stuff like
```clojure
(macro-log "Hiya number " 2 "!")
```
In other words, it’s multi-arity and type-generic now!
Cheers

Streamline macro-log

---

src/Concretize.hs
test/memory.carp

Not very proud of the patch though, maybe there's something in the `concreteCopy` parameters that can be used to determine if it's a pointer?

Lambda copy generated bad code.

---

core/Macros.carp
core/SDL.carp
docs/core/Dynamic.html
examples/external_struct.carp
src/Commands.hs
src/Emit.hs
src/Obj.hs
src/StartingEnv.hs
test/regression.carp

This PR fixes #472 by removing `local-include` and prefering `relative-include` wherever possible.
It seems like, from [surveying Github](https://github.com/search?q=extension%3Acarp+local-include), the only people currently impacted by this are @timdeve (specifically his arduino project) and @titan (his palbox api client).
Cheers

Remove local-include in favor of relative-include

---

core/Macros.carp

This change adds two utility functions to the Dynamic module for
transforming list forms into arrays and array forms into lists.
Using this function, one can easily convert lists and arrays for
ease of symbol manipulation, for example:
```clojure
(Symbol.join (list-to-array (list 'a 'b 'c)))
```
This comes in handy, for instance, when defining macros, as certain
forms in Carp expect arrays in certain places while others expect
list--this enables the programmer to flexible convert between the two as
needed.

Macros: Add dynamic list to array transforms

---

core/carp_string.h

Using `strncpy` with a length depending on the source argument yields a warning on gcc 9.

Fix gcc9 warning.

---

docs/LanguageGuide.md

Replaces reference to local-include with relative-include in the language guide
local-include was removed in #543

Updates docs to reflect removal of local-include

---

src/Eval.hs

This PR fixes #571 by replacing the colon in a file path produced by a Git checkout by `_COLON_`. This should probably be generalized later on, but maybe it’s good enough for now?
@TimDeve Could you check that this fixes your problem?
Cheers

Replace colon in git path

---

src/Obj.hs

This PR unifies printing booleans in `(project)` and other commands that show the current state of the project environment. Previously, a bunch of the boolean variables were printed Haskell style (id est using `True` and `False) and other were printed Carp style (using the lower case versions).
I took the liberty of unifying this to Carp style and introducing a local function for that.
Cheers

Unify printing booleans in project

---

docs/core/Dynamic.html
src/Commands.hs
src/StartingEnv.hs

This PR removes `project-set!`, as discussed in #583. All tests and benchmarks still run on my machine.
Cheers

Remove project-set!

---

docs/core/Dynamic.html
src/Commands.hs
src/StartingEnv.hs

This PR adds the dynamic function `write-file`, which is the writing equivalent to `read-file`. It enables us to write code like this:
```clojure
(defdynamic *c-counter* 0)
(defndynamic inline-c [s]
(let [f (String.join [(Project.get-config "output-directory")
"carp_inline_c_generated" (str *c-counter*) ".h"])]
(do
(write-file f s)
(system-include f))))
(inline-c "int x() { return 1; }")
(register x (Fn [] Int))
(defn main [] (println* &(x)))
```
I hope this is useful enough to motivate why this is a good idea!
Cheers

Add write-file

---

src/Eval.hs
test/args.carp

This PR fixes a regression that was introduced by #579: we check for `https:` and `http:` after having the colon replaced, meaning this will never work. We have to check for `https_COLON_` and `http_COLON_` instead.
Cheers

Fix regression when loading via git

---

docs/LanguageGuide.md

Correct “annoted” to “annotated”

Fix typo in LanguageGuide

---

src/Eval.hs
src/Path.hs

This PR fixes #595 by ensuring that we remove the directory that we created for our Git load if we fail.
Cheers

Ccleanup path in git load if we fail

---

src/Parsing.hs

This PR adds `-` to the list of characters that we can escape. This is because `-` means `Match the previous character (or class) zero or more times, as few times as possible` in Carp patterns (as taken over from Lua patterns).
Cheers

Fix pattern escaping

---

core/IO.carp
docs/core/IO.html

This PR makes sure we actually register  `error` inside `IO`.
Thanks for @hugurp for looking at the docs with me and pointing out the `doc-stub`. :)
Cheers

Actually register error

---

core/Char.carp

This PR simplifies `Char.meaning` by removing a bunch of copies and using `case` instead of `cond`.
Cheers

Simplify Char.meaning

---

core/Heap.carp

This updates @chrisosaurus wonderful heap library by removing the copies, since we now know how to call function references!
Cheers

Reduce copies in heap

---

src/Emit.hs

This PR fixes #557 by removing unit types from calling forms. It makes programs like this work:
```
(defn f [x] x)
(defn main [] (f ()))
```
Which before errored by trying to emit a parameter of type `void` in the argument list.
Cheers

Filter out unit types from call

---

src/Eval.hs

This PR checks `fn` arguments for non-symbols and returns an error if it does. This finally accounts for all the cases and thus finally fixes #414!
Cheers

Disallow non-symbols in fn arguments

---

core/Core.carp

Looks like there was 2 missing includes on the Core.carp file, making compilation fail on systems that those are not imported by default

Add 2 missing includes on core/Core.carp

---

src/StructUtils.hs

This PR fixes #598 by not assuming that externals that don’t have `str` defined for them are pointers. It will print the opaque `<external>` instead. If we want the old behavior of printing the pointer back for certain values, we can always implement `str` for those types.
In a way, this trades robustness for clarity.
Cheers

Don’t print external unless we know we can

---

core/Macros.carp

This PR adds the `until` macro, which is the inverse of `while`.
Chhers

macros: add until

---

core/Macros.carp

This PR adds the dynamic functions `cxr`, `nthcar`, and `nthcdr`. They build on top of `car` and `cdr` to allow arbitrary accesses, like so:
```clojure
(defdynamic x '(1 2 ((3) 4) 5))
(cxr '(3 a 2 d) x) ; => 3, equivalent to caaaddr
(nthcdr 2 x) ; => (((3) 4) 5)
(nthcar 2 x) ; => ((3) 4)
```
I’m not quite sure about the naming of `nthcar`, because it suggests `n` `car` operations, when in fact it’s `n` `cdr`s followed by one `car`. In Common Lisp, this is just called `nth`, but since we already use that name, I’d like to avoid that. Any alternative suggestions are welcome!
Cheers

macros: add cxr, nthcar, and nthcdr

---

core/Macros.carp

This PR fixes a bug in the definition of `nthcdr`. As suggested by @scolsen in #622, it misbehaved by doing one less `cdr` than would be expected for reasons of symmetry and based on its definition.
Cheers

Fix nthcdr

---

core/Array.carp
docs/core/Array.html
docs/core/Maybe.html
test/array.carp

This PR adds `Array.map->`. This seems like a very useful function to me, but I may be alone with that judgement, so please tell me if you’d rather not have this in the standard library.
`map->` represents a functional generalization of looping in a `map`-like interface. To quote from its docstring:
`map->` creates an array by producing values using `step` until they no longer satisfy `test`. The initial value is `start`.
Example:
```clojure
; if we didn’t have Array.range, we could define it like this:
(defn range [start end step]
(map-> start &(fn [x] (< x (+ step end))) &(fn [x] (+ x step)))
)
```
It is thus a little hard to understand, but once you do it is fairly powerful.
Cheers

RFC: Add Array.unreduce

---

core/Core.carp
core/core.h

Can Dynamic.or be used in Core.carp like this? or will this never evaluate true on non-win systems? This could be hacky in some way, but it's small and fixed compilation on my system.

[win] attempt to fix windows compilation

---

core/Array.carp

This PR fixes #631 by adjusting the example in `Array.reduce`. Thank you @Emiluren for pointing it out!
Cheers

Fix example in Array.reduce documentation

---

core/Format.carp
src/Commands.hs
test-for-errors/char_at_index.carp
test/output/test-for-errors/char_at_index.carp.output.expected

This PR fixes #636 by checking the index of `char-at`. It also makes the same error in `fmt` more informative.
A test case is included.
Cheers

Check index in char-at

---

core/Result.carp
docs/core/Result.html
test/result.carp

This PR makes sure that `Result` functions take refs. Before, they would take ownership over the function, which we generally do not want.
Cheers

core: make result functions take refs

---

core/String.carp
core/carp_string.h
docs/core/String.html

This PR adds `String.from-cstr`. It’s a noop function that only appeases the typechecker.
Cheers

core: add String.from-cstr

---

core/Macros.carp

This PR adds `comp`, a macro that translates function composition.
Example:
```clojure
((comp inc inc) 10)
; gets rewritten to
((fn [<gensym>] (inc (inc <gensym>))) 10)
```
Cheers

Add comp macro

---

README.md

I updated the README's example to note the additional dependency required for macOS Catalina as per issue #638.

README > Update the example for macOS Catalina

---

src/ArrayTemplates.hs
src/StartingEnv.hs
test/array.carp

This PR add the function `Array.unsafe-raw` in the _ArrayTemplate.hs_ 
I included 2 test checking
This should fix #591

Add Array.unsafe-raw

---

core/Result.carp
docs/core/Result.html
test/result.carp

This PR adds `Result.map-error`, which was missing before and fills a hole that is opened by `map` on the `Success` constructor. Since `Error` and `Success` should generally have the same functionality attached to them, that’s what I settled on.
Cheers

Add Result.map-error

---

core/Map.carp

This PR increases the performance of `put!` for `Map` and `Set` in the presence of collisions by reducing indirection and allocation.
The peformance can be tested with, for instance, this program:
```clojure
(load "Bench.carp")
(add-cflag "-O3 -flto -march=native -fomit-frame-pointer")
(defn main []
(let-do [m (Set.create-with-len 16777216)
x (Bench.get-time-elapsed)]
(for [i 0 16777216] (Set.put! &m &(Int.random)))
(Bench.print "Time: " (- (Bench.get-time-elapsed) x))))
```
On my machine (a recent MacBook Pro), this prints around 7.5 seconds versus around 13 seconds before, so it’s pretty substantial.
Cheers

Better performance in Map./Set.put!

---

core/Bench.carp
core/carp_bench.h

This PR cleans up the Bench module by moving `get-time-elapsed` into the module and cleaning up the name in C.
Cheers

Move get-time-elapsed into Bench module

---

core/carp_pattern.h
core/carp_string.h
src/ArrayTemplates.hs
src/Deftype.hs
src/StructUtils.hs
src/Sumtypes.hs

This PR is basically the vanilla version of #650. We’re removing the length checks with `snprintf` when we know the size already. This avoids a few extra checks.
Cheers

Use snprintf only when checking length

---

core/Char.carp

This PR fixes the type of `Char.zero`, which was too permissive (using the generic function `from-int` without annotation).
Cheers

core: fix type of Char.zero

---

core/String.carp
core/carp_string.h
test/double_math.carp
test/float_math.carp

This PR adds `Float.from-string` and `Double.from-string`. Because of how the underlying C functions work, they both return `0` if the number could not be parsed (similar to `Int.from-string` and `Long.from-string`). We should probably fix that at some point.
Cheers

Add Float.from-string and Double.from-string

---

src/Concretize.hs

This PR makes the error message on duplicate symbols in `Concretize` more useful. This is just a band-aid, because we should introduce more principled error handling in the long run, but this is a first attempt.
Cheers

More useful error message on too many vars

---

core/carp_byte.h

On my system, Carp programs fail to compile with error messages like this:
```
In file included from out/main.c:18:
./core/carp_byte.h:1:9: error: unknown type name 'uint8_t'
typedef uint8_t byte;
```
Adding the correct include directive fixes the issue.
Additional info:
+ Compile command: `clang -fPIC -lm -g out/main.c -o "out/Untitled"  -I./core/ `
+ Clang version: 
``` 
clang version 9.0.1 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
+ OS: `openSUSE Tumbleweed 20200122`

Add missing #include <stdint.h> to carp_byte.h

---

core/Macros.carp

This PR changes `foreach` to be more hygienic. I changed the variables `len` and `xs` to `gensym`s to make sure that we don’t introduce unwanted captures. The variable `i` I deliberately left unhygienic, because it’s often useful to know the iteration number we’re on (though arguably, that’s what `for` is designed to do). I’d be happy to introduce a gensym for that as well.
Cheers

Make foreach (almost) hygienic

---

src/Eval.hs

This PR fixes an issue where the current directory wasn’t reset correctly when we tried loading a file that was already cloned.
Cheers

Rreset current work directory correctly on load

---

src/ArrayTemplates.hs
test/execute.sh

This PR makes `Array.copy` use `memcpy` if the member type isn’t managed instead of copying all the members on their own. It’s not necessarily a huge performance boost, but it leads to tighter code (and is just good practice I think).
Cheers

Use memcpy if members aren’t managed

---

src/Concretize.hs
src/Emit.hs
src/Eval.hs
src/GenerateConstraints.hs
src/InitialTypes.hs
src/Obj.hs
src/Parsing.hs
src/Qualify.hs

This PR introduces dynamic `fn` constructs, including closures. It seems to work fairly well, although I’m not quite happy with the implementation.
Eventually, while refactoring evaluation, I’d like to opt for introducing a more generic and powerful construct for this: `Closure Env Obj`. This would be part of `Obj` and able to wrap any other object with an environment that it closes over. That’s a little more principled and beautiful, but also more work that I’d hate to invest while we’re still working on a system that will get replaced.
Cheers

Introduce dynamic fns

---

core/Pattern.carp
core/carp_pattern.h
src/Parsing.hs
test/pattern.carp

This PR fixes multiple things in `Pattern`:
Firstly, this PR fixes how newlines and tabs are treated in patterns and adds carriage returns. Previously, the match was aborted on the first match of a newline due to a bug (`goto init;` wasn’t called). This PR simplifies their handler also.
Secondly, this PR fixes capture groups; there was the possibility for memory corruption if capture groups weren’t initialized, but the length calculation for the strings doesn’t need to depend on those capture groups in the first place. We also introduce `Pattern.split` and `Pattern.global-match-str`, which first triggered that bug.
Cheers

Fix multiple things in pattern

---

bench/array_subarray.carp
core/Array.carp
core/Dynamic.carp
core/Filepath.carp
core/Format.carp
core/Interfaces.carp
core/Pattern.carp
core/String.carp
core/carp_string.h
docs/core/Array.html
docs/core/String.html
examples/basics.carp
out/keep.txt
src/StartingEnv.hs
test/array.carp
test/memory.carp
test/string.carp

This PR introduces `slices` an interfaces that creates subcollections from collections. It supersedes `substring` and `subarray`. I also took the liberty of renaming `prefix-<collection>` and `suffix-<collection>` to just `prefix` and `suffix`.
Since `suffix` depends on `length` we can’t make it a generic just yet, but I hope we’ll be able to rectify that soon.
This PR breaks existing behavior, thus our libraries should be vetted for usage of these functions. Fore reference [here’s the current usage of `subarray`](https://github.com/search?q=extension%3Acarp+subarray&type=Code). Once this has been approved I’ll update all Carpentry packages accordingly.
Cheers

Introduce slice

---

core/Format.carp

This PR fixes an error in `fmt` if it’s called without arguments. It also adds another error message if there are arguments to a format string that doesn’t take any, so that we don’t try to throw those away instead.
Cheers

core: fix fmt without arguments

---

core/String.carp

This PR fixes a problem in `starts-with?` and `ends-with?`, namely they didn’t check whether the substrings were actually shorter than the strings to test against, which is a requirement.
Cheers

core: add check in starts-with?/ends-with? for string length

---

core/Long.carp

This PR makes `Long` behave more like the other numerical types by fulfilling some of the interfaces we expect from them.
Cheers

Add Long.MAX, Long.MIN, and Long.zero

---

core/Macros.carp

This PR adds custom comparators to `for`. This is necessary especially when using expressions as steps. We can implement a generic `for` loop with arbitrary numerical types like so, for instance:
```clojure
(for [(zero) n (one) <] (IO.println &(str n))
```
`n` is the only thing that determines which numerical type to use here, which is pretty cool.
But we can also use more advanced comparators, if we really want to.
Cheers

Add additional custom comparator to for

---

core/Macros.carp

This PR readds the old implementation of `foreach` as `doall`, a kind of side-effecting version of `map`.
Cheers

Readd old foreach as doall

---

core/Core.carp
core/Map.carp
core/StdInt.carp
core/carp_stdint.h
test/int16.carp
test/int32.carp
test/int64.carp
test/int8.carp
test/uint16.carp
test/uint32.carp
test/uint64.carp
test/uint8.carp

As discussed in #683, this PR adds the stdint module into the core of Carp proper. I expect that we can add even more functions to the mix, but this should be a solid base for having a set of integers with predictable widths.
Cheers

core: add stdint types

---

core/Array.carp
core/Binary.carp
core/Core.carp
core/StdInt.carp
core/carp_binary.h
scratch
test/binary.carp

This PR adds a binary module for converting byte sequences to and from commonplace int encodings (16, 32, 64). 
1. *Do we need a new module for this?* We could simply add this functionality to the `Byte` module (which inspired this module)--my original reason for separating the two is that the `Byte` module is currently nice and small, and while these modules are interrelated, their functionality is separable. That said, it might be nice to keep it all in one place--I'm open to suggestions on this point.
2. *Is there a way we can use the `Byte` functions directly to implement this?* I couldn't figure out how. Seems like we need to do the type conversion (and unfortunately thus the actual bit twiddling in C to make it work). If that is the case, this might be one argument for merging this …

Add Binary module

---

core/Core.carp
core/carp_byte.h
core/carp_stdint.h

This PR fixes #688 by using the formatting macros in `inttypes.h` for printing `stdint` types. This is part of the C99 standard, and thus should work reliably.
Cheers

Using formatting macros for stdint

---

core/carp_binary.h

In the spirit of other reformatting PRs, this PR reformats `carp_binary.h` using `clang-format`.  Sorry I didn’t catch that earlier.
Cheers

Reformat carp_binary.h

---

examples/life.carp

This PR fixes the example `life.carp`, which was detected by @pluckyporcupine!
It’s a simple API change that went undetected.
Cheers

Fix life example

---

core/Binary.carp
test/binary.carp

This PR contains a temporary fix for the issue described in #698--it doesn't resolve the underlying issue, defining types in modules, and setting their doc meta still results in "too many functions" errors on reload, but this at least fixes the problem temporarily for the Binary module.﻿

Temporarily fix reloading errors related to the Binary module

---

test/args.carp

This PR fixes a bug discovered by @TimDeve. One of the tests in `test/args.carp` constructed the path to the executable erroneously when there was no trailing path separator.
Cheers

Fix args test

---

test/args.carp

As pointed out by @TimDeve we should also include `mingw32` in the test for a Windows system in `test/args.carp`.
Cheers

Fix args test for windows (again)

---

core/Test.carp

Context: https://github.com/carp-lang/Carp/pull/244#issuecomment-391382849
As there is no script to run the test suite in windows, is it alright to remove these assert until there is a window implementation (if that is possible)?

Doesn't compile assert-exit and assert-signal on windows

---

.github/workflows/carp.yml

This is a follow up to https://github.com/carp-lang/Carp/pull/706, it wasn't included then because some of the tests failed when running `stack test`, now that https://github.com/carp-lang/Carp/commit/f616945ebd2f699d53ac7a3b86bfc1bd0b6c8b10 has happened we should be able to run `stack test` in the CI.

Adds stack test to CI

---

docs/core/Pointer.html
src/StartingEnv.hs
test/pointer.carp
test/unsafe.carp

Adds two functions:
Pointer.to-value turns a Ptr into an owned value
Unsafe.leak consumes a value and prevents it from being freed by Carp
This is a draft because there isn't any tests yet and I'm not sure this is something that people want.
Combining the two allows to extract values out of a struct without copy.
Example:
```clojure
(defn to-ptr [r] (the (Ptr a) (Unsafe.coerce (the (Ref a) r))))
(defn unsafe-value [a] (Pointer.to-value (to-ptr a)))
(defn main []
(let [p (Pair.init @"Hello" @"Sup")]
(let [a (unsafe-value (Pair.a &p))
b (unsafe-value (Pair.b &p))
_ (Unsafe.leak p)]
(println* (String.concat &[a b])))))
```

Add functions to: turn Ptr into value & prevent destructor from being run 

---

.github/workflows/windows.yml
run_carp_tests.ps1

This PR creates a Powershell script so that the test suite can be run on Windows.
It's just a draft for now to get some feedback.
Aside from the issues in https://github.com/carp-lang/Carp/pull/705 and https://github.com/carp-lang/Carp/pull/704 the only failing tests seems related to int64 and uint64 probably because of https://github.com/carp-lang/Carp/pull/577, should these tests be skipped on Windows for now?
The script also doesn't include the output checks for errors and the examples, I'm looking at adding this later.
My goal with this script is to hopefully get Windows CI running similar to https://github.com/carp-lang/Carp/pull/706 so that regressions on Windows can be detected earlier.

Create CI for Windows

---

docs/Macros.md

This PR enumerates all special forms in the documentation, since they are kind of “magical”.
Cheers

docs: enumerate special forms

---

src/Eval.hs

This PR emits the dependencies of our autogenerated `main` function in `Eval` and thereby fixes #714. This was a remnant of #695.
Cheers

Generate dependencies of autogenerated main function

---

src/Eval.hs

This PR fixes #713 by adding a check to calling a function at the REPL: if that function is `main`, we emit an error.
Cheers

Guard against calling main directly

---

app/Main.hs
src/Commands.hs
src/Obj.hs
src/Parsing.hs
src/Repl.hs

This PR is an effort to clearer communicate what needs to be closed in multiline input (which led to e.g. #729 being opened).
We already match unclosed brackets, parens, and quotes. All we need to do is display them. A simple way to do that would be something like what I added:
What do y’all think? (Pinging especially @sdilts, since he got confused by this)
Cheers

Proposal show unbalanced elements in the prompt

---

src/Qualify.hs
test/sumtypes.carp

Previously, we'd stopped doing this, but it leads to issues with matches
on functions, e.g.
```
(deftype A (F [(Fn [] Int)]))
(defn m [a]
(match a
(A.F f) (f)))
(defn main []
(println* (m (A.F (fn [] 123)))))
```
Will result in a runtime error if the environment isn't extended.
Fixes #731

Extend inner environments with lhs case bindings

---

src/Commands.hs
src/StartingEnv.hs

This PR adds the command `bit-width`, which  gives you the integer/pointer width of the platform (usually 32/64 bits on modern systems).
This could be a dynamic global variable, but since we currently do not have a good mechanism for adding variables like that I added this as a command. I’d also be open to change this to a variable and build some plumbing for that.
Cheers

Add bit-width command

---

core/Array.carp
core/StaticArray.carp
docs/core/Array.html
docs/core/StaticArray.html
test/array.carp
test/static_array.carp

This PR tries to get StaticArray to parity with Array function wise where possible. Functions that creates a new array were skipped. Also adds test where they were missing in `test/array.carp`.
Adds these functions:
- `Array.from-static`
- `StaticArray.reverse!`
Copies the following functions from Array to ArrayStatic:
- `empty?`
- `any?`
- `all?`
- `find`
- `find-index`
- `first`
- `unsafe-first`
- `last`
- `unsafe-last`
- `minimum`
- `maximum`
- `sum`
- `index-of`
- `element-count`
- `predicate-count`
- `aupdate!`
- `swap!`
- `nth`
- `contains?`

Adds functions to operate on StaticArray

---

src/Primitives.hs

Make invalid usages of `register-type` to gracefully errors out.

---

core/Core.carp
core/Macros.carp
docs/Macros.md
docs/core/Dynamic.html
src/Emit.hs
src/Eval.hs
src/Obj.hs
src/Primitives.hs
src/StartingEnv.hs
test/args.carp
test/macros.carp

This PR fixes #719 by making primitives less magical. Because of current limitations of name resolution, this also means that dynamic `or` and `and` have to be renamed, which is a bummer. I settled on `dynor` and `dynand`, but I’m not really happy with those, so if you have suggestions, let me know!
Cheers

Make primitives proper AST objects

---

app/Main.hs
src/Concretize.hs
src/Emit.hs
src/InitialTypes.hs
src/Lookup.hs
src/Obj.hs
src/Primitives.hs
src/Scoring.hs

Implements #741.
As I'm very new to Haskell, I assume most of the things could be done in a better way but I really want to contribute.
To do:

Registered type aliasing

---

docs/Macros.md

This PR mentions that you have to wire up primitives and commands in the starting environment. Thanks to @linkpy for pointing that out!
Cheers

Mention environment in macro docs

---

core/Int.carp
src/Primitives.hs
src/TypeError.hs
src/Types.hs
src/Validate.hs

This commit adds basic kinds checking on interfaces, such that an
interface that takes a type constructor (f a) can't be implemented by a
function using a concrete type like `Int` in that position.
It also adds checks on deftypes to ensure uninhabited type constructors can't be set as members:
```
(deftype (Foo a) [pos Maybe])
Invalid type definition for 'Foo':
Can't use an uninhabited type constructor (Maybe a) as a member type at line 1, column 23 in 'REPL'. The type constructor (Maybe a) expects 1 arguments but got 0
Traceback:
(deftype (Foo a) [pos Maybe]) at REPL:1:1.
```
Fixes #561

Add kinds checking

---

src/Sumtypes.hs
src/Validate.hs

This commit does two things:
- Update validate to permit type defintions like:
`(deftype (Higher (f a)) (Obj [(f a)]))`
- Replace all type vars in such cases so that we generate the correct C
code.
**Previous Behavior:**
```
(deftype (Higher (f a)) (Obj [(f a)]))
Invalid type definition for 'Higher':
I can’t use the type `a` as a member type at line 1, column 25 in 'REPL'.
Is it defined and captured in the head of the type definition?
Traceback:
(deftype (Higher (f a)) (Obj [(f a)])) at REPL:1:1.
```
Or, once we accept that syntax:
```
(defn obj [x] (Higher.Obj x))
:i obj
obj : (λ [(a b)] (Higher a b)
(obj (Maybe.Just 3))
out/main.c:2196:41: error: unknown type name 'f__int'
Higher__Maybe_int Higher_Obj__int_Maybe(f__int member0);
^
out/main.c:6344:41: error: unknown type name 'f__int' …
```

Support sumtypes with higher-kinded members

---

docs/core/Dynamic.html
src/Commands.hs
src/Primitives.hs
src/StartingEnv.hs

This PR adds documentation capabilities to commands and enforces creating docs during registration. It also documents all of them.
It will probably lightly interfer with #751, because it changes `addCommand` a bit, but it hopefully does not generate too much work.
Cheers

Document and enforce documentation on registration

---

docs/Embedded.md

This PR adds a first version of an `Embedded.md` doc. While I am one of the more qualified people to speak about the Carp compiler per se, I’m one of the less qualified people to speak about embedded development, to say the least. As such, please review  what I have written fairly carefully.
I’ve tried to keep the information topical while still being general enough.
Cheers

Add embedded doc

---

docs/core/Dynamic.html

This PR adds the docs for `deftemplate` which probably weren’t generated for #751.
Cheers

Add deftemplate docs

---

src/Types.hs

This commit makes function types unifiable to *only* polymorphic
constructors (`StructTy` with a `VarTy` name). This enables one to implement
interfaces defined against constructors against functions so long as:
- The number of function arguments match the number of type constructor
arguments.
Thus, one can define:
```
(definterface constructor (Fn [(f a b)] (f a b)))
(defmodule Test (defn constructor [f] (the (Fn ([a b] a) f))))
```
But how is this useful?
Here's one scenario this corrects in practice. In Haskell, the `some`
function is typed generically as `some :: f a -> f [a]`. `some` takes a
type and successively  applies it until it returns an empty value, then
it returns a list of results of the applications. This is great for
types that actually have state, such as parsers, but …

Make polymorphic struct types and functions unifiable

---

src/Eval.hs
src/Lookup.hs
test/regression.carp

This PR fixes the behavior of bot `set!` and `let` in dynamic contexts. It turns out that both of them had subtle bugs that interplay in a fun way. Consider this piece of code
```clojure
(let-do [x 1]
(let-do [y 2]
(set! x 2)
(macro-log x))
(macro-log x))
```
Before this PR, the first `macro-log` would print `2`, the second one `1`. That is because `set!` actually updated the wrong internal environment, namely the one closest. I added a new environment function `envReplaceBinding` that will go up the environment chain and search for a binding to replace. It does not currently work for prefixed names and if it doesn’t find a value it does nothing. For `set!` this is fine, but it might not be generally desirable behavior.
This is not all we needed to fix, though, because it turns out that …

Make dynamic set! and let interplay nicely

---

src/Eval.hs
src/Primitives.hs

Before :
```
> (defmodule)
carp: src/Eval.hs:(515,1)-(555,48): Non-exhaustive patterns in function primitiveDefmodule
> (defmodule "abc")
carp: src/Eval.hs:(515,1)-(555,48): Non-exhaustive patterns in function primitiveDefmodule
> (defmodule 1)
carp: src/Eval.hs:(515,1)-(555,48): Non-exhaustive patterns in function primitiveDefmodule
```
After : 
```
> (defmodule)
`defmodule` requires at least a Symbol, received none. at dummy-file:0:0.
Traceback:
(defmodule) at REPL:1:1.
> (defmodule "abc")
`defmodule` expects a Symbol, got '"abc"' instead. at REPL:1:12.
Traceback:
(defmodule) at REPL:1:1.
> (defmodule 1)
`defmodule` expects a Symbol, got '1' instead. at REPL:1:12.
Traceback:
(defmodule 1) at REPL:1:1.
```

Graceful handling of invalid usages of `defmodule`.

---

core/Macros.carp

The title says it all. Tiny fix for `inline-c`.

Fix the `inline-c` macro to avoid using a reserved keyword as parameter.

---

core/Pattern.carp
docs/core/Pattern.html

As came up in the chat, the docs for `Pattern.substitute` did not mention the possibility to reference match groups. This PR fixes that.
Cheers

Mention backreferences in docs for Pattern.substitute

---

core/Array.carp
test/array.carp

This is a work around for https://github.com/carp-lang/Carp/issues/776 the proper fix would be to allow range to take `(range 0 0 1)` inputs but the decision about what the correct behavior should be hasn't been made.

Makes enumerated work with empty arrays

---

core/Test.carp
docs/core/Test.html
test/array.carp
test/binary.carp
test/io.carp
test/static_array.carp
test/vectorn.carp

As promised in #691, I pulled out the new `assert` primitives and used them all over the test suite.
Cheers

Add assert-ref-equal, assert-just, and assert-nothing

---

core/String.carp
core/carp_pattern.h
docs/core/String.html
docs/core/System.html
docs/sdl/IMG.html
docs/sdl/Mixer.html
docs/sdl/SDL.html
docs/sdl/TTF.html
test/execute.sh

This PR adds `str` for references on numeric types to make things like `(Double.+ 2.0 3.0)` work on the REPL, which implicitly call `str` on the `ref` of the result.
Cheers

Add str on refs for numeric types

---

core/Float.carp
core/String.carp
core/carp_pattern.h
core/carp_string.h
docs/core/Byte.html
docs/core/Double.html
docs/core/Float.html
docs/core/Int.html
docs/core/Long.html
examples/guessing.carp
test/double_math.carp
test/float_math.carp

This PR changes `from-string` for all the number types to actually fail when the string is not a valid number. This means that all of them return a `Maybe` now. Under the hood this is achieved by checking whether the `endptr` argument to `strto*` is `\0`, which means that we reached the end of the string after parsing.
Of note: these functions will still consume any leading whitespace, which is the behavior of `strto*`.
Cheers

Make Num.from-string better

---

core/Generics.carp

This PR fixes a typo in the docs for `Generics.approx`.
Cheers

Fix typo in docs for Generics.approx

---

core/Core.carp
core/Macros.carp
src/Util.hs
test/double_math.carp

This commit adds FreeBSD as a supported platform. I understand that this may not be as easy as just adding it to the list, but if can point me at things that I should test, I can do that.
Tests (on FreeBSD 12.1-RELEASE, amd64)

Add FreeBSD as a supported platform

---

carp.sh
default.nix
haskell-flamegraph.sh

Generate flamegraphs for the compiler.
```
$ nix-shell --arg profiling true
$ ./haskell-flamegraph.sh -b test/carp.sh
```
Generates the attached carp.svg.
[carp.svg.zip](https://github.com/carp-lang/Carp/files/4618746/carp.svg.zip)

Flamegraph for the haskell side.

---

core/Macros.carp

This macro adds implements forms for functions with the same name as a
given list of interfaces in a given module.

Add an implements-all macro

---

core/Debug.carp

This PR fixes `Debug.trace` for the new evaluator. In the old evaluator `file`, `line`, and `column` were commands that evaluated their argument before it was passed in. Now they are primitives, and passing in a macro symbol will result in the information on the macro symbol being returned. We often do not want that, and that’s why we have to wrap it in an `eval` to make sure the symbol gets resolved first before passing it in.
Cheers

Fix Debug.trace for new evaluator

---

src/Parsing.hs
test/char.carp

This PR fixes #812 by introducing more special characters: `\return`, `\backspace`, `\formfeed`, and `\uNNNN` unicode literals.
Cheers

Add \return, \backspace, \formfeed, and \u unicode literals

---

core/Maybe.carp
src/StartingEnv.hs

This PR fixes #802 by making `NULL : (Ptr a)`. This requires a tiny change in `Maybe.unsafe-ptr`, which makes the function more principled anyway.
Cheers

Make NULL Ptr a instead of a

---

core/Long.carp

This PR adds missing `implements` annotations to `LongRef`.
Cheers

Add missing longref implements annotations

---

core/Macros.carp
core/Tuples.carp
src/Lookup.hs
src/Primitives.hs

This PR bundles a few small improvements to our handling of interfaces and implementations:
Before `meta` use to fail to find its argument binding in cases
like this one:
```
(defmodule Foo (hidden bar) (meta Foo.bar "hidden"))
```
This is because `meta` used to cons path strings to the path even if
the path was already qualified with a module name as in the example
above. We now treat these cases separately, and instances like the
above work.
This makes sense since functions could implement multiple generic
interfaces. An example of the new behavior:
```
(implements inc foo)
(implements dec foo)
(meta foo "implements")
=> (dec inc)
```
```
鲤 (implements inc foo)
鲤 (implements dec foo)
鲤 (eval (implements? 'inc foo))
=> true
鲤 (eval (implements? 'dec foo))
=> true
鲤 (eval (implements? '+ …
```

Interface Implementation improvements

---

core/Macros.carp

This PR fixes the dynamic checkers `hidden?`, `private?`, and `annotate?` for the new evaluator API.
Cheers

macros: fix hidden?, private?, and annotate?

---

core/Core.carp
core/Introspect.carp
src/Primitives.hs
src/StartingEnv.hs

This PR adds an `s-exp` primitive, which returns the s-expression or form associated with a binding. It's similar to the default behavior of dynamic xobjs, but it does some extra checking on receiving module xobjs to return the original deftype forms whenever the modules are generated from a type.
`s-exp` is the backbone of a new `Introspection` module, which contains predicates about bindings and their associated forms. One can use this module in a dynamic context to determine if a binding is a function, struct, sumtype, interface, it's arity, etc.
Here are a few examples of `s-exp`:
```clojure
鲤 (def foo 3)
鲤 (s-exp foo)
=> (def foo 3)
鲤 (defn bar [x] x)
鲤 (s-exp bar)
=> (defn bar [x] x)
鲤 (deftype Foo [x Int])
鲤 (s-exp Foo)
=> (deftype Foo [x Int])
鲤 (deftype (Bar a) (Baz [a])) 
鲤 …
```

Add `s-exp` primitive and Introspection module

---

.gitignore
CarpHask.cabal
app/Main.hs
src/Commands.hs
src/Concretize.hs
src/Deftype.hs
src/Emit.hs
src/Eval.hs
src/Expand.hs
src/GenerateConstraints.hs
src/Info.hs
src/InitialTypes.hs
src/Obj.hs
src/Parsing.hs
src/Primitives.hs
src/Qualify.hs
src/StartingEnv.hs
src/Sumtypes.hs
src/Template.hs
src/TypeError.hs

This PR moves `Info` and related functions into its own module in `Info.hs`.
`Obj.hs` is quite large at this point and contains functions that have a wide variety of responsibilities. I think it's worthwhile to try and separate concerns a bit more and simplify the `Obj.hs` code. Unfortunately, there are mutually recursive dependencies between most of the key types in `Obj` which makes it difficult to move them into isolated modules. `Info` however is less problematic, and it's straightforward to port it into its own module.

Info Refactor

---

CarpHask.cabal
app/Main.hs
carp.sh
core/SafeInt.carp
core/carp_long.h
core/carp_safe_int.h
default.nix
examples/basics.carp
headerparse/Main.hs
src/Emit.hs
src/Eval.hs
src/Repl.hs
stack.yaml
test/init_global.carp

This is a more flexible alternative to #803. Implements `--eval-preload` and `--eval-postload` with the intention of changing compiler and flags, but could be useful for other purposes.

Command line switches to evaluate code

---

CarpHask.cabal
app/Main.hs
carp.sh
core/SafeInt.carp
core/carp_long.h
core/carp_safe_int.h
default.nix
examples/basics.carp
headerparse/Main.hs
src/Emit.hs
src/Eval.hs
stack.yaml
test/init_global.carp

Not sure if this is the best approach. Maybe we should just read a `CC` environment variable?
Timings on some very old hardware:
- `CARP_OPTS=--compile-fast ./run_carp_tests.sh --no_sdl`: 2m:51
- `./run_carp_tests.hs --no_sdl`: 8m58

Added --compile-fast to compile with tcc.

---

src/Primitives.hs
src/StartingEnv.hs

Add info about specifying c names in the `register-type` doc string.

Improve register-type documentation

---

core/Introspect.carp
src/Primitives.hs

Previously, introspecting an interface only returned `definterface` and
its name. We now return the form corresponding to the interface's types
signature, which enables us to introspect more effectively; e.g.
returning the appropriate arity of an interface.
For example:
```
鲤 (s-expr inc)
=> (definterface inc (Fn [a] a))
(arity inc)
=> 1
```

Improve introspection support for interfaces

---

core/Array.carp
core/ArrayExt.carp
core/Core.carp
docs/core/Array.html
examples/lambdas.carp
test/array.carp
test/heap.carp
test/memory.carp

This PR makes `Array.range` safe. I first wanted to make the error case return a `String`, but `String.copy` is not yet available in the `Array` module. It fixes #776 
Cheers

Make Array.range safe

---

core/Macros.carp
docs/LanguageGuide.md

This PR updated the documentation of `cond`, based on the work @mitchell-frost has done (thanks again!).
Specifically, it adds a docstring to `cond` so that inspecting the value lets the programmer see it.
Cheers

Update doc of cond

---

examples/nested_lambdas.carp
run_carp_tests.sh
src/Concretize.hs
src/Emit.hs
src/Obj.hs
src/Qualify.hs

This should be fixing #805 
The solution I went for is to modify the `CaptureMode` datatype. The `Capture` constructor now takes an int which indicates the "Capture Distance" that is the number of lambdas between the binding of the variable and its usage (this is easy to calculate during Qualification).
This allows to differentiate between a variable bound by the last encountered lambda, and one which is present in its environment, and can be used to fill the next environment.

Fixed the issue with nested capture and nested lambdas

---

CarpHask.cabal
src/Commands.hs
src/Emit.hs
src/Eval.hs
src/Interfaces.hs
src/Lookup.hs
src/Meta.hs
src/Primitives.hs
src/RenderDocs.hs
src/Template.hs

**N.B. this PR includes changes from #866 and #867 ** 
This PR moves interface handling code out of Primitives.hs and into its
own module. The actual primitives user's rely on to define and implement
interfaces still live in Primitives.hs, but now all the
registration/internal context mgmt code related to interfaces lives in
its own module.
Hopefully this will make it easier to modify and extend!

Move interfaces code into its own module

---

CarpHask.cabal
src/Commands.hs
src/Emit.hs
src/Eval.hs
src/Lookup.hs
src/Meta.hs
src/Primitives.hs
src/RenderDocs.hs
src/Template.hs

**N.B. this also contains changes from PR #866 **
This PR mostly just factors out case statements from a variety of
functions using two useful utilities `maybe` and `either`.
Essentially, these functions enable you to express a case against a
Maybe or Either in terms of a function and default value, and generally
help readability. In our case they:
- Allow us to remove tons of repetitive return statements.
- Allow us to remove do's.
- Eliminate some cases and simplify the code structure.
In total, it eliminates about 66 loc
This PR contains no behavioral changes

Refactor Primitives.hs

---

CarpHask.cabal
src/Commands.hs
src/Emit.hs
src/Eval.hs
src/Lookup.hs
src/Meta.hs
src/Primitives.hs
src/RenderDocs.hs
src/Template.hs

This change introduces a `Meta` module to abstract away the underlying `Data.Map` representation. Where we previously modified `MetaData` using `Map`, we can now use `Meta` module functions, to ensure caller's manipulation of metadata isn't dependent on the underlying representation.
This should also make it possible to swap out `Data.Map` for some other representation easily (should we ever have to do that, likely not).

Meta Refactor 

---

src/Emit.hs
test/regression.carp

I am new to Haskell. Just met @hellerve at ZuriHac today and they pointed me to this issue: https://github.com/carp-lang/Carp/issues/843. My solution appears to fix 843 from the perspective that the example code provided in the issue now runs without exception (the generated C code no longer contains a call to `Example_delete` in the catch all block of code generated for `Match`), however I don't really understand why a deletion was taking place to begin with. I am trying to understand why a deletion may have made sense at this point... not sure if my fix breaks another test case. Thanks!
Related commit (which added the delete call): https://github.com/carp-lang/Carp/commit/c80d6429202f8437445afded85b4fafa0997b461

Attempt at fixing #843

---

examples/nested_lambdas.carp
src/Concretize.hs

This should be fixing #879 
As described, my changes in #850 didn't support implict environments, causing error in the calculation of the set of captured variables for a lambda.
To fix this issue, I have added a special case in `collectCapturedVars`; when encountering a `Let` construct, we filter the identifiers defined in the bindings out of the variables captured by the body, as well as the following bindings (where they could be used).

Fixed lambda capture in presence of let bindings

---

core/GLFW.carp

I started playing around with OpenGL. As I'm a beginner, my main goal is to implement [this tutorial](http://www.opengl-tutorial.org/) in Carp.
As this tutorial is using GFLW, I have quickly realised that none of the constants defined in *gflw3.h* have bindings in the GFLW module.
I have started adding some of these missing constants (mainly the one I needed to be honest). Would you like me to add the rest ?

Added some of GLFW constants

---

src/Eval.hs
src/Obj.hs

Once again trying to fix the evaluation issue outlined in #850.
After the mistake made in #858, I tried to generalize the current "static evaluation", rather than change it completely. The results fixes the example shown in #850, but there is still a few issues that I would like to discuss before implementing a definitive solutions.
The current push code does evaluate correctly the following example:
```
(defn ident [x] x)
((ident (fn [x] x)) 1)
```
which was not the case before this PR. However I have found 2 categories of bug this does not fix:
* consider `(+ (ident 2) (ident 2)` which should evaluate to `4`. With the current code, the evaluator returns an error, as it tries to apply the primitive `+` to `((defn ident [...]) 2)`. 
* I think this could be solved by checking …

Generalization of the evaluation of static defn

---

core/Format.carp
src/Eval.hs
src/Expand.hs
test-for-errors/private-bindings.carp
test/output/test-for-errors/private-bindings.carp.output.expected

This implements private by adding a simple check to the evaluator and expander. If a
binding is found in the global context, we check if it's marked as
private. If so, we inform the user that it can't be called from outside
of its module.
Note that we don't perform this check if the binding is found in the
internal env, since that means it's a function called within the same
module and thus is ok (even if marked as private).
After this change, something like the following works, granting us
proper encapsulation:
```
;; File Foo.carp
(deftype Foo [bar Int])
(private Foo.bar)
(defmodule Foo
(defn get [foo]
(Foo.bar foo))
)
;; Enter REPL
(load "Foo.carp")
(Foo.bar &(Foo.init 1))
The binding: Foo.bar is private; it may only be used within the module
that defines it. at REPL:1:2.
@(Foo.get …
```

Implement Privacy Checking 

---

src/RenderDocs.hs

Previously, some of the documentation generations specific to Carp's
core library doc generation were hardcoded in renderdocs, thus, even
though users could set their own logo and url, these weren't honored
during the generation of module documentation, resulting in a bunch of
docs pointing to logos and urls that weren't intended.
This change updates the rendering code to honor the url and logo set in
the user's Project config.

Honor project logo and url during module doc gen

---

src/Commands.hs

The `last` command relies on Haskell's `Prelude.last`--which will crash
on an empty list input. We report an error for incorrect input to last,
but we didn't handle the empty list case. This small change to our
pattern match ensures errors in carp code produce Carp's last command
error rather than causing `Prelude.last` to throw an error on empty list
input.
fixes #897

Ensure command last calls handle empty lists

---

core/Introspect.carp
core/Macros.carp
src/Commands.hs
src/Concretize.hs
src/Eval.hs
src/Interfaces.hs
src/Obj.hs
src/Primitives.hs
src/Util.hs
test/introspect.carp

It's a fairly common pattern in Carp to call a higher-order function on
some structure of values, such as an Array. However, these structures,
and their members, all have lifetimes under Carp's memory management
model, which means they expect functions that are mapped over them to
take *a reference to a value* rather than a pure value. Array.reduce is
one example of such a "referential" higher-order, the type of its
function argument is:
```
(Fn [a, (Ref b c)] a)
```
That is, this function takes some pure initial value, then expects to be
called against the members of an array, which are *references* to the
values that are alive throughout the Array's lifetime.
However, one often wants to use a function that operates on pure values
in such contexts, such as +, which forces the programmer …

Add a `with-copy` macro

---

core/Macros.carp
core/carp_string.h
test/macros.carp

This PR adds `doto` and `doto-ref`, which are imperative versions of `->`.
Example:
```clojure
(doto-ref @\"hi\"
(string-set! 0 \o)
(string-set! 1 \y)) ; => "oy"
```
Cheers

Add doto and doto-ref

---

src/Obj.hs

getPath returns the path of a form. The DefDynamic case was missing from
the function's definition, resulting in failures when calling functions
such as the meta set primitive on dynamic defs. This change fixes such
issues.
Fixes #936

Add DefDynamic to getPath

---

core/Macros.carp

Carp preserves tabulation and other whitespace in strings, as it should.
This sometimes results in awkward code indentation when it comes to long
doc strings that exceed 80 characters. Often, one has to continue the
string on a newline, but needs to avoid adding tabs to prevent Carp from
rendering them in the output.
This change alters the behavior of doc to take a series of strings as a
rest parameter instead, allowing for neater organization in the source,
for example, after this change the following long doc string for
compose:
~~~
"Returns the composition of two functions `f` and `g` for functions of any
arity; concretely, returns a function accepting the correct number of
arguments for `g`, applies `g` to those arguments, then applies `f` to the
result.
If you only need to compose …

Make `doc` take a rest parameter of strings

---

src/Commands.hs

This PR adds a few comparable classes to dynamic `=`: arrays, non-empty lists, and all AST types without arguments (because they’re trivially comparable).
Cheers

Expand comparables in dynamic =

---

CarpHask.cabal
docs/core/Dynamic.html
headerparse/Main.hs
src/Commands.hs
src/Concretize.hs
src/Obj.hs
src/Primitives.hs
src/Reify.hs
src/StartingEnv.hs
src/Types.hs

Extends Carp's support for type reflection by returning types for
values as well as bindings.
`type` now also returns a valid Carp expression/s-expression and so its
output can be used as input to dynamic functions and macros (prior to
this commit, `type` printed the type to the REPL but did not return a
meaningful expression in Carp).
Here are a few illustrations of the behavior:
```clojure
(def x 1)
;; type now returns an s-expression/symbol
(type x)
=> Int
;; It also works on values
(type 1)
=> Int
(type 2b)
=> Byte
(type "foo")
=> (Ref String <StaticLifetime>)
;; It works on more complex values as well
(type Maybe)
=> Module
(type Maybe.Just)
(Fn [a] (Maybe a) <StaticLifetime>)
;; reports honestly about polymorphism
(type (Maybe.Nothing))
=> (Maybe a)
(type (Pair.init 1 2))
=> (Pair …
```

Enhance type reflection

---

core/Macros.carp
docs/core/Dynamic.html

This PR fixes a typo in the docs for `curry*`.
Cheers

macros: fix typo in curry* docs

---

src/Eval.hs

Previously, `expand` only printed the results of a macro expansion to
the console. However, there are legitimate use cases for having expand
return the expanded form, particularly, when nested macro calls should
be expanded but not evaluated. Consider the following:
```clojure
(defmacro reff [] '(Ref Int <q>))
(defndynamic lt [x]
(last x))
(defmacro wrapped [x] (lt x))
```
The above, when called with the `reff` macro as an argument, won't work
as expected, since macros don't evaluate their arguments:
```clojure
(wrapped (reff))
=> reff
```
Currently, the solution is to wrap the `lt` argument in `eval`, but this
won't work, since even though it will expand the macro, it will try to
evaluate `Ref` after the expansion!
```clojure
(defmacro wrapped [x] (lt (eval x)))
(wrapped (reff))
=> Can't …
```

Eval: Make expand return the expanded form

---

core/SDLHelper.h

This PR fixes #943 by using the technique described by @jacereda, using `define` and `undef`.
Cheers

Fix SDL for newer versions

---

core/Macros.carp

It seems at some point inline-c became a noop (I believe when the way macros are evaluated has changed), this PR restores the functionality.
It also makes the last argument optional as, looking through the original PR, it seems that was the original intent.

Fixes inline-c and makes last argument optional

---

core/String.carp
core/carp_string.h
docs/core/Pointer.html
src/Validate.hs

This PR fixes `deftype` and `register-type` for `(Ptr ())`, which is a special case. It also adds `Pointer.str` and `Pointer.prn`. @Kampouse reported this bug in #534.
Cheers

register-type: fix for void

---

src/Eval.hs

This PR fixes an error in `eval` that would lead to a confusing error message being spit out: basically, if a `HasStaticCall` exception was raised, the evaluator would try again, and the error message would be that `eval` is not defined, because it isn’t, in the static context. This PR fixes the error message to actually say what the user might think.
This also means that if I define my own static function called `eval` in the REPL it will no longer be chosen as a backup, but I think this rarely happens and it would go through the primitive first, anyway, leading to confusing behavior.
Cheers

eval: catch static call error

---

.github/workflows/carp.yml
.github/workflows/linux.yml
.github/workflows/osx.yml
.github/workflows/windows.yml
README.md

Both set-env and add-path are being deprecated as they are security vulnaribilities, see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Removes usage of set-env & add-path from Github Actions workflows

---

core/StaticArray.carp
docs/core/StaticArray.html
test/static_array.carp

Adds `unsafe-raw` to StaticArray.
Allows to use a StaticArray when interfacing with C.

Adds unsafe-raw to StaticArray module

---

src/Primitives.hs

This PR fixes a bug found by @TimDeve and @kampouse: `use` didn’t react well when fed a non-symbol. Now it prints a proper error message.
Cheers

Fix use when its not a symbol

---

.github/workflows/linux.yml

We seem to have had a regression (#956) without noticing because we don't run the SDL examples/tests in the CI.
This PR enables them in the Linux CI.
#958 fixes #956, will rebase this PR once it is merged.

Run SDL tests on linux CI

---

scripts/run_carp_tests.sh

Makes it easier to see which file failed in case of errors.

Echoes examples path when running run_carp_tests.sh

---

.github/workflows/osx.yml

Like #959 this PR enables the building the SDL example in the MacOS CI.

Enables SDL tests in MacOS CI

---

src/Deftype.hs
src/Emit.hs
src/Obj.hs
src/Sumtypes.hs
src/Types.hs
src/Validate.hs

This commit enables support for using values of type () (Unit) in
user-defined types such as product and sumtypes. After this commit,
types such as:
(deftype Units [action-one () action-two ()])
Are valid, and can be instantiated in the obvious way:
(Units.init (IO.println "foo") ())
Some important things to note about the implementation:
- The C structs emitted for types containing Unit members *completely
omit all unit members*. If a type in Carp has N members, the
corresponding C struct will have (N-U) members where U is the number of
members with the type `Unit`.
For example, this type:
(deftype (Foo [one Unit two Int]))
will produce the following typedef in C:
typedef struct {
int two;
} Foo;
As a special case, types that *only* have Units as members are represented and
initialized …

Allow Unit to be used as a member type in deftypes

---

.github/workflows/osx.yml

For some reason it was not pulling the latest actions/setup-haskell@v1.1.x with the fix for `add-path`. Set actions/setup-haskell@v1 instead.

Simplifies MacOS CI by removing custom version in setup-haskell

---

src/Reify.hs

Unit's show implementation defaults to the empty list `()`--this
presents problems when validating types, since generic type members are
replaced by the reification (a type literal) of their arguments. In the
`Unit` case, `()` yields some surprising invalid types.
So, we reify UnitTy as `Unit` instead to ensure consistency. This
permits using  Unit as a member in generic types like Result.

Reify: Add Unit as a special case

---

examples/mutual_recursion.carp

Updates the example so it can be executed without blowing the stack.
Made it slightly closer to what an actual usage of mutual recursion would look like.

Updates mutual recursion example

---

core/Core.carp
core/Unit.carp
src/Deftype.hs
src/Emit.hs
src/StructUtils.hs
src/Types.hs

- Specialize generic setter functions against Unit members
- Specialize calls to str/prn against Unit members in StructUtils
(rather than accessing the struct member, which doesn't exist in the
Unit case, we simple call Unit's prn function.)
- Don't bind references to Unit values to variables. This fixes an error
whereby a reference to a Unit would generate invalid C such as:
`void* _9 = &;`
Likewise, we omit references to Units from function arguments just as
we omit Unit values.
- Add `prn`, `copy`, and `zero` implementations for `Unit`

More Unit type member enhancements

---

core/Core.carp
core/Function.carp
test/function.carp

I'm not sure if this the best way to go at it. This PR is more of a request for feedback.
Enables to bind to callback based API, like `pthread_create`:
```clojure
(register create-c (Fn [(Ref Thread) (Ptr ()) (Ptr ()) (Ptr ())] Int) "pthread_create")
(sig create-from-handle (Fn [(Ref Thread) (Ref (Fn [] ()))] (Result () Int)))
(defn create-from-handle [thread fun]
(let [error-code (create-c thread
NULL
(Pointer.from-fn fun)
(Pointer.env-from-fn fun))]
(if (= 0 error-code)
(Success ())
(Error error-code))))
```

Adds functions to help with callbacks based C interop

---

core/Pointer.carp
core/System.carp

This commit adds a few more utility functions to `Pointer.carp`.
- Pointer.set-unsafe: Sets the value of a pointer to some arbitrary Carp
value, without type checking. Users need to ensure this operation is
safe.
- Pointer.set: Sets the value of a pointer to a value of type t to a
value that has the same type.
- Pointer.unsafe-alloc: Copies a Carp reference to a new pointer to the same
value. This creates a leak since Carp will not automatically clean up
this memory.
- Pointer.free: Frees a pointer p. Users need to ensure calls to this
function are safe and do not produce errors like a double free.
Intended for use with leak.
Here's an example of some of these functions in action:
```
(defn foo []
(let-do [p (Pointer.leak "leaky")] ;; create a new pointer
(ignore (Pointer.set p @"foo")) …
```

Pointer: Add utility functions

---

app/Main.hs
scripts/carp.sh
src/ColorText.hs
src/Commands.hs
src/Eval.hs
src/Interfaces.hs
src/Primitives.hs

This PR fixes #1002 by adding checking for `CARP_DIR` being set. If it’s not set, it will emit a warning. If it isn’t set and `--no-core` isn’t set either, it will also emit an error and exit.
While @TimDeve and I were at it, we also refactored the error printing to make it a little more ergonomic.
Cheers

Refactor error reporting and add CARP_DIR check

---

CarpHask.cabal
src/ArrayTemplates.hs
src/AssignTypes.hs
src/Commands.hs
src/Concretize.hs
src/Constraints.hs
src/Deftype.hs
src/Emit.hs
src/Eval.hs
src/Expand.hs
src/GenerateConstraints.hs
src/InitialTypes.hs
src/Interfaces.hs
src/Lookup.hs
src/Obj.hs
src/Parsing.hs
src/Polymorphism.hs
src/Primitives.hs
src/Qualify.hs
src/RenderDocs.hs
src/Repl.hs
src/Scoring.hs
src/Sumtypes.hs
src/TypeError.hs
src/Types.hs
src/Validate.hs

There are some bits here  I'm not sure about. I'll try to spot them tomorrow.l

Address name shadowing

---

core/Function.carp
docs/CInterop.md
docs/core/generate_core_docs.carp

The PR enables html docs generation for the `Function` module as well as expand the docs around its usage.

docs: Expands docs around C function pointers

---

scripts/commit-msg-hook.sh

We had some trouble with previous implementation of the git hook because of differences between BSD awk and GNU awk.
This PR uses sed instead and has been tested both with BSD sed and GNU sed.

chore: Makes the commit message hook more portable

---

src/InitialTypes.hs
src/Obj.hs
src/TypeError.hs

This PR adds better error messages for invalid AST objects by introducing `InvalidObjExample`, which is a type error that carries an example invocation with it. It also improves `InvalidObj` by calling `pretty` on the code inside it instead of `show`.
Cheers

feat: better error messages for invalid objects

---

src/ArrayTemplates.hs
src/Emit.hs
src/Template.hs
src/ToTemplate.hs

Units may be used as members in arrays just like any other type,
however, the array templates (which are specific to arrays) hadn't been
updated to handle this. This commit makes the necessary updates and adds
some utility functions in efforts to make using templates in the
compiler easier.
After this commit, the following functions should work correctly on
(Array Unit):
- endo-map
- endo-filter
- copy
- aset!
- aset-uninitialized!
- aset
- pop-back!
- pop-back
- push-back
- push-back!
Just like other types with Unit members, the only value that is stored
in the resulting type is the terminal value of Unit `()` or unit. Any
side effects are run during evaluation of arguments and emitted prior to
any structure manipulations.
Because Unit is a terminal type (contains a single value) it …

fix: Handle unit members correctly in array templates

---

src/Validate.hs

Previously, this function missed a case, namely, one where the head of a
type definition contains a concrete struct, like `Maybe` with a variable
argument, `a`. That is,
```
(deftype (Foo (Maybe a)) [x (Maybe a)])
```
Would throw a type error. This commit fixes that issue.

fix: handle unhandled case in isCaptured

---

src/Eval.hs
src/StartingEnv.hs

This PR extends `load` by allowing a second argument to selectively load a specific file from a repository, instead of requiring `main.carp` or `<repo-name>.carp`.
It probably conflicts with #1063, and I’d happily amend my PR once it is merged.
Cheers

Allow for repository files to be loaded selectively in load

---

CarpHask.cabal
src/Lookup.hs
src/Obj.hs
src/PrimitiveError.hs
src/Primitives.hs
src/Reify.hs

This commit is the first in what will hopefully be a series of helpful
primitive refactors. To start, we:
- Move some inline `evalError` strings into a `PrimitiveError` module,
(similar to the `TypeError`/`Types` module relationship
- Add `Reifiable` instances for String and Int types to take these
types to their XObj representation.
- Add info utility functions for converting Info data to an XObj
- Refactor the `info` primitive:
- Use monadic combinators + `maybe` instead of nested cases.
- Use helper lookup functions that take a *context*--nearly *all*
lookup calls currently extract some env, typically without doing
anything to it, to pass it to lookup. This is a sign the boundary is
incorrect and lookups should take the context instead--this will allow
us to eliminate a ton of local …

Primitive refactors

---

app/Main.hs
test/execute.sh

This PR uses `--eval-preload` to make sure the output directory in test is as expected when running the test script. This makes sure that having a different config set in `profile.carp` doesn’t conflict with running the tests.
Cheers

Make sure output directory is right in test

---

src/Commands.hs
src/StartingEnv.hs

This PR adds the command `parse` which takes in a string and returns an expression. Please note that empty strings and strings containing multiple expressions will result in an error.
Cheers

feat: Add parse command

---

src/Eval.hs
src/Obj.hs

This PR changes the default behavior in the REPL from printing symbol info to evaluating that symbol. In order to do this, we needed to add a few special cases to the symbol lookup in `eval` for `def`s, `defn`s, and `external`s.
Please note that that makes a weird problem that we have even weirder. Consider this program:
```clojure
(def x 1)
x
(defn main [] x)
```
Currently, this will print the information of `x` during compilation. Now, this compiles another program and prints `1` before compiling the actual `main` program. This is a somewhat unrelated bug that should probably be fixed—global symbols should probably just be an error in a file—, but it is existing behavior that changes.
Cheers

feat: Evaluate symbols for statics in REPL

---

src/Primitives.hs

This PR fixes the `members` primitive, which has to implement custom lookup logic to get to the type by looking at modules.
Cheers

fix members primitive

---

docs/LanguageGuide.md

Fixed a mistake and clarified how structs are defined and used in Carp.

Documentation on Structs

---

core/Macros.carp

This PR fixes `defdynamic-once` by `eval`ing its result.
Cheers

Try fixing defdynamic-once

---

src/Eval.hs

(Sorry for the lingo in the title of this PR, I really don’t know how to write a title for this)
This PR fixes an issue where arguments to top-level dynamic calls were not classified as top-level, leading to static calls being undetected in the REPL.
Example:
```clojure
> (load "SDL.carp")
> (= SDL.Keycode.return SDL.Keycode.return)
```
Cheers

Fix resolve semantics for successive evaluation

---

src/Eval.hs

This PR fixes the closure history for dynamic evaluation. Since the history is only used for tracebacks, it wouldn’t make much sense to use the original history—which tells us where the closure was created—to report errors, but rather the history of the call, to tell us where the closure was actually used.
NB: Maybe the history of the closure creation could also be interesting in some cases, though, to trace back where it’s coming from?
Cheers

Fix closure history on dynamic eval

---

src/Concretize.hs

An older version of Carp only allowed users to implement interfaces by
defining a function of the same name. Since PR 769 and roughly commit
040e9e4 however, this was no longer the case, since we added a primitive
for implementing interfaces, allowing users to implement interfaces
using functions with whatever name they want.
When this happened, the function lookups that happen during
concretization were never updated to reflect the fact that interface
implementations might have different names than their corresponding
interfaces. It's rare, but this can lead to errors for template
functions in the compiler.
For example, registered types automatically get an implementation of
`prn` with the same name. This function takes a ref to the registered
type as an argument. If a user wants to use …

fix: account for interfaces in function lookups

---

src/Eval.hs
src/Map.hs
src/Obj.hs
test/closure.carp
test/dynamic-closures.carp

This PR does two things:
1. Adds `Semigroup` instances for `Env` and `Context` to offer a way to combine each of these types, respectively. Envs are combined using the left-biased union of the maps containing their bindings.
2. Updates our handling of closures to evaluate them under the *semigroup combination* of the context captured during their creation and the context under which they are evaluated, biasing toward the creation-context. This allows us to ensure closures have access to the latest global definitions, fixing #1101, while also ensuring that, in the case of conflicts, they prefer the local definitions captured during the creation context.

fix: Closure context

---

src/Eval.hs

This fixes a bug whereby closures would mistakenly capture bindings of
other scopes because they'd combine internal environments.
In particular:
```
(defndynamic sum-with [f]
(fn [] (reduce (fn [acc m] (+ acc (* m f))) 0 [1 2 3])))
((sum-with 10))
```
Would lead to `f` in the function passed to reduce being bound to the
function itself, instead of the expected `10` since reduce *also*
defines an `f` as an argument, and these would collide when combining
the internal envs.
We now keep internal envs separate, which prevents this issue. The
combination of type and global envs is retained, ensuring closures have
access to the latest global values.

fix: don't combine internal envs in closures

---

src/Commands.hs

This PR makes dynamic `=` more permissive, allowing equality on everything. This might seem "unsafe" to some of you, but is useful in dynamic contexts and macros: if I traverse a form, for instance, I might need to compare a list to a number and such things. They are not equal, and they never should be, but I need `=` to not throw an error in such cases.
Cheers

refactor: make dynamic equality more permissive

---

core/List.carp
test/macros.carp

This PR adds the `walk*` dynamic forms for traversing data structures and applying functions to them, e.g. for rewriting.
It depends on #1132 and #1131.
Cheers

feat: add walk*

---

core/Float.carp

This PR correctly marks `Float.pi` as an implementor of the `pi` interface. It must have gotten lost when we moved towards `implements`.
Cheers

fix: mark Float.pi as implementor of pi

---

core/Array.carp
core/Interfaces.carp
core/Map.carp
core/StaticArray.carp
core/String.carp
test/string.carp

This PR makes `empty?` an interface.
Cheers

feat: make empty? an interface

---

core/Vector.carp

This PR uses `derive` in `Vector.carp` for `=` and `zero`.
Cheers

refactor: use derive in Vector modules

---

core/Array.carp
core/Bench.carp
core/Core.carp
core/Debug.carp
core/Format.carp
core/IO.carp
core/Quasiquote.carp
core/StaticArray.carp
core/String.carp
core/Test.carp
core/Tuples.carp

This PR changes the standard library to use quasiquoting where applicable, and fixes a problem where we didn’t go through arrays inside quasiquotes.
Cheers

refactor: use quasiquoting in STDLIB and go through array in quasiquote

---

src/Emit.hs
src/Eval.hs
src/Obj.hs
test/regression.carp

Like `let` before it, we used to bind function arguments to their values
only, which wasn't accounted for in `set!` such that one could not
`set!` `i` in `defndynamic [i] ...`. To fix this for let bindings we
introduced a `LetDef` form for consistency with Def forms. This commit
renames `LetDef` to `LocalDef` and uses it as a value for function
arguments in addition to let bindings, ensuring `set!` works on function
arguments too. Big thanks to @hellerve for the suggestion!
Fixes #1144

fix: make set! work with dynamic args (thanks @hellerve)

---

src/Expand.hs
test/output/test/test-for-errors/match-literals.carp.output.expected
test/test-for-errors/match-literals.carp

This PR fixes #1113 by adding an analysis into `expand` that checks whether anything other than lists and symbols are used in the left hand side of a `match`. The code is quite inelegant; if anyone has any ideas on how to make it better, I’d love to hear it!
I also added a test case for the new error message.
Cheers

fix: deal with literals in match

---

core/Dynamic.carp
core/List.carp
src/Commands.hs
src/Obj.hs
src/StartingEnv.hs
src/Types.hs
test/macros.carp

The following things were changed and/or added:
- `Dynamic.neg` was added
- `Dynamic.mod` was changed to work on float values
- `Dynamic.cxr` was changed to work with `0` instructions
- `Dynamic.=` was changed to ignore the type of the number
- `Dynamic.round` was added
- dynamic arithmetic was changed to respect the numeric type tower
- the instances of `Eq` and `Ord` for `Number` are no longer derived, so that they work across numeric types
- the instance of `Num` for `Number` was changed to work across numeric types
- `promoteNumber` was added as a type function to implement the numeric tower.
The numeric tower is as follows:
```
Byte -> Int -> Long -> Float -> Double
```
Cheers

feat: a proper dynamic numeric tower

---

docs/Format_Strings.md

This PR fixes [the recent docs build failure](https://github.com/carp-lang/carp-docs/runs/1767071759) that was caused by an interplay of our escaping syntax and Jekyll’s templating language Liquid.
Reading up on Liquid, you can mark blocks as needing no templating by using `{% raw %}` blocks. Sadly, those also get rendered in Markdown.
Cheers

docs: don’t confuse liquid

---

core/ControlMacros.carp
core/Macros.carp
docs/core/carp_style.css
src/Primitives.hs
src/RenderDocs.hs

This PR adds the `meta` form `deprecated`. It will be rendered in HTML (see the screenshot below) and in the REPL, like so:
```
> :i =>
=> : Macro
Defined at line 27, column 3 in '/Users/veitheller/Documents/Code/Github/carp/carp/core/ControlMacros.carp'
Deprecated: true
```
Cheers

feat: add deprecation meta

---

src/Primitives.hs
test/output/test/test-for-errors/qualified-register.carp.output.expected
test/test-for-errors/qualified-register.carp

This PR fixes #1031 by enforcing that the symbol argument to `register` is unqualified.
Tests are included.
Cheers

fix: register should only take unqualified symbols

---

core/Derive.carp

This PR fixes a typo in the example for `Derive.make-deriver` and adds a note for future maintainers at the top of the page to save them time.
Cheers

docs: fix typo in make-deriver and add implementor note

---

src/Eval.hs
test/regression.carp

This PR fixes an issue where quoted macros would be expanded still because the expander didn’t actually stop when it encountered a quote.
Cheers

fix: respect quotes in macro expand

---

src/Commands.hs
src/Eval.hs
src/StartingEnv.hs

This PR fixes #779 by hiding the compile information on an implicit compile (for instance, when typing `(Int.+ 1 2)` in the REPL) and letting it return `nil` instead of `0`, avoiding a print.
To this end, it also extends `build` by adding an optional boolean argument that specifies whether build information should be printed.
Cheers

refactor: don’t print compilation info on implicit compile

---

src/Eval.hs
src/Expand.hs
test/output/test/test-for-errors/address-of-nonsymbol.carp.output.expected
test/output/test/test-for-errors/multiarg-ref.carp
test/output/test/test-for-errors/multiarg-ref.carp.output.expected
test/test-for-errors/address-of-nonsymbol.carp
test/test-for-errors/multiarg-ref.carp

This PR fixes #806 by checking the calls to `address` and `ref` statically as to whether they make sense.
Cheers

fix: check calls of address and ref

---

core/Random.carp
src/Eval.hs
test/random-seed.carp
test/regression.carp

**Note**: *this PR depends on #1160.*
This PR makes reseeding the random number generator in `Random` at startup configurable.
It adds the following functions:
- `Random.startup-reseed` will enable reseeding at startup. **This is the default**.
- `Random.no-startup-reseed` will disable reseeding at startup.
- `Random.startup-reseed?` can be called to check whether `Random` was reseeded at startup.
- `Dynamic.Random.startup-reseed?` can be called to check whether `Random` will be reseeded at startup.
An open question remains whether we need two functions to enable and disable reseeding to make the intent clear, or whether one function with a boolean argument—e.g. `(Random.startup-reseed true)`—would be enough.
Cheers

feat: make reseeding of Random at startup configurable

---

docs/Drop.md
docs/Memory.md
examples/drop.carp
src/Concretize.hs
src/Emit.hs
src/Info.hs

his PR adds support for a `drop` interface, i.e. an interface that gets run before a value is deleted. It should not do any memory cleanup, but other cleanup, like closing OS handles, can be done here. It fixes #954.
Cheers

feat: Add drop interface

---

src/Concretize.hs
src/Emit.hs

This PR fixes #1052 by fixing up `break` statements with the context of which resources need to be released.
This is achieved by descending from any `let` and `while` statement into an enclosed `break` and adding any variables that need to be freed in that scope to its deleters.
Cheers

fix: release resources on break

---

core/Dynamic.carp
core/Introspect.carp
test/introspect.carp

This PR adds `Introspect.arguments`, which largely does the same thing as `Introspect.arity`, but without calling `length` but instead returning the argument array as-is.
Because it’s thus a  generalization of `Introspect.arity` that function was refactored to use `Introspect.arguments`.
Cheers

feat: add Introspect.arguments

---

core/carp_stdint.h

This PR removes unused variables from `carp_stdint.h` that prevented `-Wall` form working. As a side note, this line also makes `-Wall` fail:
https://github.com/carp-lang/Carp/blob/59d43abf74cbdba77914312e0d714d92267e1dfb/src/Emit.hs#L420
Because it turns out that this variable is only used when a member of the sumtype is used in the right hand side of match. Since this was not a quick fix, and not necessarily a terrible bug (it’s just an unused variable) I didn’t bother to fix it for now.
Cheers

fix: remove unused vars in carp_stdint.h

---

examples/benchmark_mandelbrot.carp
examples/benchmark_n-body.carp
scripts/run_carp_tests.ps1
scripts/run_carp_tests.sh

This PR fixes #1000 by re-adding (and fixing) the previously broken benchmarks. They are also added to `scripts/run_carp_tests.*`.
Cheers

fix: re-add benchmarks

---

core/System.carp

This PR fixes the type of the registered function `carp-init-globals`, which was `(Fn [Int Int] ())` but should be `(Fn [Int (Ptr (Ptr  CChar))] ())`, as pointed out by @TimDeve.
Cheers

fix: correct the type of carp-init-globals

---

core/Dynamic.carp
core/List.carp
core/Macros.carp
core/Map.carp
core/Test.carp
src/Eval.hs
src/Obj.hs
src/Parsing.hs
test/dynamic_map.carp
test/map.carp

This PR implements a dynamic hashmap datatype in Carp, based on assoc lists and hashing. It uses the same algorithms as the static `Map` type under the hood.
This is a draft, and it’s pretty much in prototyping state. Getting, setting, and updating works, but there are a few unimplemented features and open questions.
To do:
Open questions:
- Currently, just returning a map will result in having a massive assoc list printed to the REPL. Wrapping that in `Dynamic.Map.str` works, but it’s still somewhat unexpected. How should we make this work automatically?
- ~~Similarly, how do we make literals work? Presumably we can build `from-array`, and it shouldn’t be too hard and then “just” work when dynamic bindings are preferre, but that needs to be tested and verified.~~ Literals work.
Cheers

feat: add dynamic Map type

---

core/Macros.carp
src/Commands.hs
src/Context.hs
src/Eval.hs
src/Infer.hs
src/Lookup.hs
src/Meta.hs
src/Obj.hs
src/Primitives.hs
src/Qualify.hs

This PR is on the bigger side and does a few things:
1. Augments `Context.hs` with several utility functions for managing environments and other properties of a context--this enables us to use a more abstract/opaque API and move all context updating into a single place, making it harder to get things wrong.
2. Refactors the `Qualify` module to include types for representing *fully qualified xobjs and sympaths*. While I was working through the code base I realized that we were qualifying symbols across module boundaries (for example, the xobjs passed to `define` in `Primitives.hs` are fully qualified by `annotateWithinContext` in `Eval.hs`, which is also called in a few other contexts, meanwhile, several other primitives qualified symbols themselves, using contextPaths.) The old situation …

refactor: Context and Qualify

---

src/Parsing.hs

This PR adds map literals (`{}`) to the balancing parser used in the REPL. This enables multiline map literals in the REPL.
Cheers

fix: respect maps in balancing

---

core/Macros.carp
docs/LanguageGuide.md
test/output/test/test-for-errors/def-.carp.output.expected
test/output/test/test-for-errors/defn-.carp.output.expected
test/test-for-errors/def-.carp
test/test-for-errors/defn-.carp

Adding these macros as a shortand for declaring a def or defn and making them `hidden` and `private`, useful to keep things internal to a module. Similar to Clojure's [`defn-`](https://clojuredocs.org/clojure.core/defn-).

feat: Adds `defn-` and `def-` macros

---

app/Main.hs
core/core.h
docs/CInterop.md
src/Commands.hs
src/Emit.hs
src/InitialTypes.hs
src/Obj.hs
src/Project.hs
src/StartingEnv.hs
src/Types.hs
src/TypesToC.hs

This PR introduces two new features that allow users to add arbitrary C code to the compiler's output:
Emits literal C code inline. One can use this for certain interop scenarios in which some C code *must* take e.g. a string literal as an argument. For example, the c11 `static_assert` macro *only* accepts a C string literal in the second argument position. A call to `(static-assert 0 (Unsafe.emit-c "\"foo\""))` emits the proper code `static_assert(0, "foo")`.
Two existing solutions, just using a Carp string literal and using a deftemplate (or `inline-c`, which uses deftemplate) don't work for different reasons:
1. Carp's strings are managed, so they tend to be assigned to a generated variable name, such as `_8` for this purpose. Unfortunately, that means calls to `(static-assert 0 …

feat: Add support for emitting literal C

---

src/Primitives.hs

The previous commit added qualification to paths of registered types.
However, while types defined in Carp support qualification (definition
within a module) thanks to special logic, this logic is not yet
implemented for registered types, leading to errors if their paths are
qualified in the type environment. This commit fixes the behavior and
adds a TODO to support this for registered types.

fix: don't qualify paths of registered types

---

CarpHask.cabal
src/Eval.hs
src/EvalError.hs

Following the same scheme as PrimitiveError and TypeError, this adds a
separate module for evaluation errors, removing a bunch of inline
strings in Eval.hs

refactor: Move evaluation errors into a separate module

---

src/Eval.hs
test/dynamic-closures.carp

Previously, closures could not change the global environment. As such,
calls to commands like `set!` within a closure did not update global
variables as one might expect.
This commit fixes the issue by doing two things:
- Preserve any updates to the global environment that occur when
evaluating a closure.
- Handle contexts correctly when evaluating commands.
The latter point requires a bit more explanation. At some point, we
stopped threading through the context produced after evaluating a
command's arguments, which had the unfortunate result that some commands
did not get access to the latest environment values.
Both of these fixes together fix issue 1181.
```
(defdynamic foo 0) …
```

fix: allow dynamic closures to mutate the global env

---

core/Control.carp
docs/core/generate_core_docs.carp

These functions enable users to execute some side-effecting function
(one that returns unit and take no arguments) based on the contents of a
Maybe or Result.
`when-success`: Executes a side-effect when given a `Result.Success`
`when-error`: Executes a side-effect when given a `Result.Error`
`when-just`: Executes a side-effect when given a `Maybe.Just`
`when-nothing`: Executes a side-effect when given a `Maybe.Nothing`
e.g.:
```clojure
(def suc (the (Result Int Int) (Result.Success 0)))
(def err (the (Result Int Int) (Result.Error 0)))
(when-success &(fn [] (IO.println "success!") suc))
=> "success!"
(when-success &(fn [] (IO.println "success!") err))
=>
```

feat: add 'when' functions for Maybe and Result

---

core/IO.carp
core/List.carp
test/macros.carp

Note: this PR depends on #1185 to avoid clashes.
This PR refactors the macro tests to use `assert-dynamic-equal` to remove a bunch of code.
It also fixes `cxr` and `IO.exit`, which were broken (they’re now used in the test, so we should notice if that comes up again).
Cheers

refactor: macro tests

---

core/Dynamic.carp
core/List.carp

This PR adds a few docstrings to prominent dynamic functions that weren’t documented yet.
Cheers

docs: add docstrings to some dynamic functions

---

src/Commands.hs

This PR backports a fix from #1192 for `Symbol.prefix` to use the symbol type from the prefixed symbol instead of resetting it.
Cheers

fix: use correct symbol type in Symbol.prefix

---

src/Commands.hs
src/Expand.hs
src/Obj.hs
src/Parsing.hs
src/StartingEnv.hs
test/output/test/test-for-errors/return_ref_in_do.carp.output.expected
test/output/test/test-for-errors/return_ref_to_array_literal.carp.output.expected
test/output/test/test-for-errors/return_ref_to_function_result.carp.output.expected
test/output/test/test-for-errors/wrong_sig_for_def.carp.output.expected
test/output/test/test-for-errors/wrong_sig_for_defn.carp.output.expected

This PR fixes #1189 by adding symbols for all the keywords that resolve to their special AST types. This means that we can actually treat them as symbols in metaprogramming, and as an added bonus when you use `info` on them you get regular documentation.
It also means that we need to do a bit of a dance in `expand` and `commandBuild` to make sure we don’t emit them and always resolve them. This seems brittle, and if we could get the benefits mentioned above without those drawbacks, I’d be happier. Let me know if you have any ideas!
We also had to touch a bunch of different files, but not really much has changed in the grand scheme of things.
Cheers

feat: treat keywords as symbols

---

src/TypeError.hs

This PR changes this:
```
I can’t match the types `(Prism ¤ ¥)` and `(Lens r254 —­)`. within `(Lens.get (ref  ... ata))`
```
to this:
```
I can’t match the types `(Prism pb qb)` and `(Lens r256 yb)`. within `(Lens.get (ref  ... ata))`
```
While I think using single letter Unicode is cute and all, the character set contains all sort of unprintable and hard-to-read nastiness, and a list that chooses from ASCII strings of increasing length might be more useful.
Of course, it would be  even better if we didn’t use so many type variables. In the lens code I’m working with at the moment, though, type variables are pretty prevalent, and the context of the type error contains no fewer than 272 of them. I have not found a good way to prune the list of variables to only the ones we need to display …

feat: use ascii type variables in prettify

---

core/Bench.carp
core/Random.carp

As previously discussed this PR uses the macros introduced in https://github.com/carp-lang/Carp/pull/1174
There is a surprisingly small amount of places we use hidden+private in core.

refactor: Uses def- & defn- macro in core

---

core/Array.carp

I made a mistake in the docs in #1201. Whoops.
Cheers

docs: fix order of args in map-reduce docs

---

core/Pattern.carp
test/string.carp

This PR fixes `String.words` by  ignoring empty words, i.e. multiple spaces in a row. `String-lines` remains untouched, since empty lines might be meaningful.
A test case for this behavior was included.
Cheers

fix: fix String.words for multiple word spearators in a row

---

core/Macros.carp
test/macros.carp

This PR adds capabilities for defining named simple and extended inline assembly blocks in Carp. This feature should be used with absolute caution.
A test case was included.
Cheers

feat: add Unsafe.C.asm

---

src/InitialTypes.hs

This commit fixes an issue whereby all recursive calls were given var
types, this resulted in strange behavior such as the following code:
```clojure
(defn recurse [a b]
(let [c (+ b 1)
out (recurse c)]
(+ out 1)))
(defn main []
(println* (recurse 1 2)))
```
compiling just fine and yielding runtime segfaults. Now, if a recursive
instance of a symbol was previously typed, we use that type--if not, we
assign a fresh type variable (the old behavior). This fixes code like
that above, throwing an error at compile time about an incorrect number
of arguments for `recurse`.
Fixes #348, Fixes #349

fix: properly assign types to recursive calls

---

src/Concretize.hs
src/Obj.hs

Most def forms bind values, so their types are wholly determined at
initial assignment time. However, defs that bind to lambdas may have
polymorphic types by virtue of their use of interfaces:
```
(defn duplicate-arg [f]
(fn [x] (f x x)))
(def double (duplicate-arg +))
(defn main []
(println* (double 3)))
```
Previously, the above program would yield a concretization error. This
commit adds concretization handling for def forms, and makes it possible
to call lambdas bound to defs as is done in the program above.
Fixes #364

fix: concretize def forms

---

src/Eval.hs

This is a kludgey temporary fix for #1179. The problem is that set!
occasionally receives untyped forms. In particular, this seems to happen
when the value of the form is determined by a command such as `length`.
This caused hangs when evaluating `Dynamic.mod` in particular.
For now, we just treat these like dynamic values and don't worry about
typechecking them, which seems to do the trick.

fix: don't type check untyped forms in set!

---

src/Validate.hs

This quick fix reorders the ordering of our type def validation checks
to prevent invalid types like [member []] from crashing the compiler.
fixes #1202

fix: don't crash validation on invalid types

---

src/Eval.hs
src/Expand.hs
test/output/test/test-for-errors/inner-private-bindings.carp.output.expected
test/test-for-errors/inner-private-bindings.carp

This commit changes the behavior of expansions to avoid expanding module
expressions until we're actually processing the module in question.
Previously, the following form would be entirely expanded at the time of evaluating A:
```clojure
(defmodule A <- current environment
(some-macro) <- expand
(defmodule B
(some-macro f) <- expand, current env is A, *NOT* B.
so if this expands to
(private f)
(defn f ....)
the f of the expansion is added to *A*, and we have a duplicate
ghost binder.
)
(defn foo [] B.f) <- expand, B.f does not exist yet, any meta on the
binding will be ignored, permitting privacy errors since expansion
ignores undefined bindings, instead, we'll look this up at eval time,
and not check privacy as doing so would cause problems for legitimate
cases.
)
```
This meant that if …

fix: don't expand inner module macros on first pass; privacy

---

src/Eval.hs

This fix is a close cousin of the one that allowed let bindings to
shadow global commands. We now allow function arguments to shadow
commands as well by using a local lookup preference for argument names,
making functions such as:
```
(defndynamic foo [car]
(Symbol.prefix car 'foo)
```
work as anticipated. I've also removed unused code from `apply`.
Fixes #1057

fix: allow function arguments to shadow commands

---

src/Env.hs

The recent Env refactor commits unwittingly broke the REPL's
autocompletion. This change restores the previous behavior.
Fixes #1224

fix: fix repl autocomplete

---

core/Statistics.carp
core/Test.carp
docs/core/carp_style.css
docs/sdl/carp_style.css
src/Obj.hs
src/RenderDocs.hs
src/StartingEnv.hs

This PR fixes #1235 by adding submodules to the rendered docs. It achieves this by looking at "dependencies" (i.e. inner modules) and rendering them in the HTML in two places: inside the module as a link, and in the sidebar as a submenu.
Cheers

fix: render submodules in html docs

---

src/Commands.hs

This PR fixes #1246 by inserting a few checks in `commandBuild`.
```
> (defn main [] +)
> :b
`main` was generic at build time, it must return either `Int` or `()`.
Traceback:
(build) at REPL:1:1.
> (def main 1)
[WARNING] Definition at line 1, column 2 in 'REPL' changed type of 'main' from (Fn [] (Fn [a, a] a)) to Int
> :b
`main` is expected to be a function, but was `Int`.
Traceback:
(build) at REPL:1:1.
```
Cheers

fix: check for generic main at build time

---

core/Macros.carp
core/Quasiquote.carp
examples/langtons_ant.carp
test/array.carp
test/macros.carp
test/short_circuiting.carp

So far the macros ```and```  and ```or``` expected exactly 2 parameters.
The new version - inspired by Scheme - can handle anything from 0 upwards.

(and) and (or) now handle any number of parameters

---

src/Commands.hs

This PR fixes `Dynamic.String.slice`.
```clojure
> ; before
> (String.slice  "0123456789AbCdEf" 4 6)
=> "456789"
> ; after
> (String.slice  "0123456789AbCdEf" 4 6)
=> "45"
```
Cheers

fix: Dynamic.String.slice index handling

---

core/Pattern.carp
core/carp_pattern.h
test/pattern.carp

* feat!: Pattern.match now returns start and end indizes of the first match
* feat!: matches from Pattern.find-all can no longer overlap. This fixes #1255.
* feat!: Pattern.global-match-str now returns all matches as String 
* feat!: renamed (Pattern.global-match) to (Pattern.match-all-groups) 
* feat: implemented (Pattern.match-from)
* feat: moved Pattern.match-str and Pattern.find from C to Carp code 
* fix: moved some matching code from C to Carp and removed dead C functions

reorganize Pattern library

---

core/ControlMacros.carp
core/Macros.carp

This PR fixes #1198 by making `doc` work on the top-level and documenting the macros in the standard library.
Cheers

docs: make doc work on top level and document macros

---

core/core.h

TCC is an incredibly fast C compiler.
Unfortunately on Windows the latest TCC release 0.9.27 does not work out of the box, since 2 minor definitions are missing to compile a simple HelloWorld.Carp.
* related to issue #1263, but does not generally fix it.
note: 2nd attempt cherrypicking the relevant changeset

TCC on windows 32bit

---

src/Eval.hs

This PR fixes the info set on `defmodule`.
Example:
```
> ; before
> :i Quasiquote
...
Defined at line 0, column 0 in 'dummy-file'
...
> ; after
> :i Quasiquote
...
Defined at line 5, column 12 in '/Users/veitheller/Documents/Code/Github/carp/carp/core/Quasiquote.carp'
...
```
Cheers

fix: set correct info on defmodule

---

src/Context.hs

This PR adds a few missing whitespace characters to the `Show` typeclass of `ContextError`.
Cheers

fix: whitespace in context errors

---

src/Commands.hs
src/Primitives.hs

This PR sets the `infoFile` property on commands and primitives in the compiler. This mostly means that `info` is changed:
```
> ; before
> :i Dynamic.info
Dynamic.info : Dynamic
Defined at line 0, column 0 in '<dummy file>'
[...]
> ; after
> :i Dynamic.info
Dynamic.info : Dynamic
Defined at line 0, column 0 in 'Core Primitives'
[...]
```
This is mostly so people know where things come from.
Cheers

docs: set infoFile on primitives and commands

---

core/ControlMacros.carp
core/Gensym.carp
test/macros.carp

This PR changes `case`—backwards-compatible change!—to allow for what I call multibranches, i.e. branches that are reachable by multiple values. It achieves this by using list syntax:
```clojure
(case (+ 10 1)
(11 12) (println* "its either 11 or 12")
(println* "its something else")
)
```
I also took the liberty of optimizing it—and fixing a potential problem with side effects—using `gensym`. Before, something like the above would desugar to:
```clojure
(if (or (= (+ 10 1) 11) (= (+ 10 1) 12) ; => (+ 10 1) is duplicated here, side effects would potentially be executed twice
(IO.println (ref (str "its either 11 or 12")))
(IO.println (ref (str "its something else"))))
```
Now, using `gensym` we can write:
```clojure
(let [gensym-generated1037 (+ 10 1)]
(if (or (= gensym-generated1037 11) (= …
```

feat: allow for multibranches in case

---

src/Obj.hs
src/Primitives.hs
src/StartingEnv.hs

This PR adds `machine-info`, meant as a verison of `info` for machines or programs. The name and behavior are up for debate, but I wanted to provide a prototype to get the conversation going.
A machine-readable version of the compiler-visible information associated with a symbol would be great. `machine-info` attempts to provide that by returning a list of the following form: `(type|(), info|(), metadata)`, where `type` is an S-expression of the type, `info` is a tuple of `(file, line, column)`, and `metadata` is a list of key-value pairs.
Allowing for this would, among other things, allow us to express `info` as a Carp expression. It would also allow us to inquire IDE-usable informations from within a REPL.
Of course the name and format of the return value are questions of taste. I don’t …

feat: add machine-info primitive draft

---

core/List.carp

This PR adds `List.remove-nth` which, analogous to `List.nth`, `List.update-nth` and `List.set-nth`, removes the `nth` element from a list.
Cheers

feat: add List.remove-nth

---

core/Dynamic.carp

This PR adds `Dynamic.proc?`, which checks whether its argument is callable dynamically.
Cheers

feat: add Dynamic.proc?

---

src/Context.hs
src/Eval.hs
src/Obj.hs

This PR fixes two issues. The first being that dynamic let binders were filled with an unevaluated right hand side as dummy value to enable recursion:
```clojure
; this is allowed
(let [x (fn [n] (if (= n 0) n (x (- n 1))))] (x 10)) ; => 0
; but sadly this also happens
(let [x x] x)
```
The first fix is thus to make sure that the binder trick only happens when the right hand side is a `fn`, which is the only case where recursion might make sense.
The second issue was that binders leaked out of their `let` scope in the global scope:
```clojure
(let [x 1] x) ; => 1
x ; => 1
```
This is because we replaced the internal environment with its parent when leaving the `let` block, _or with itself if it doesn’t have a parent_. The parenthetical does not make sense, especially since internal …

fix: fix dynamic let bindings recursion and binder leaks

---

src/Eval.hs
src/Parsing.hs
src/Repl.hs

This PR fixes the behavior of the REPL to respect line numbers.
Example:
```
> (def x 1)
> :i x
x : Int
Defined at line 1, column 2 in 'REPL'
> (def x 2)
> :i x
x : Int
Defined at line 3, column 2 in 'REPL' ; <= this used to say line 1 before!
```
Cheers

fix: respect line number in repl

---

src/Commands.hs

This commit makes it so that `Symbol.prefix` can take qualified symbols
as prefix arguments, e.g.
`(Symbol.prefix 'Foo.Bar 'baz) => 'Foo.Bar.baz`
Fixes #1285

fix: make Symbol.prefix work on qualified symbols

---

core/carp_string.h
test/string.carp

This PR fixes `String.prn`, escaping quotes. The function was changed in a way that should facilitate adding more escaped or specially treated character later on if desired.
Cheers

fix: escape quotes in String.prn

---

src/Concretize.hs
src/Eval.hs
src/Forms.hs
src/Obj.hs
src/TypeError.hs

This PR performs a few refactors in efforts to "cleanup" the `Concretize` module, whereby I mean it:
- Removes a bunch of local definitions to make functions easier to modify (no chance of accidentally altering function-local internal state)
- Adds an explicit export list to the module
- Tidies up some monadic usages to make them more terse and remove unneeded function calls.
I've also added some more pattern synonyms.
This is purely a refactor. This shouldn't result in any behavioral changes.

refactor: Cleanup Concretize module

---

core/ControlMacros.carp
core/Macros.carp
test/control_macros.carp

This commit adds two new ignore macros, ignore*, which wraps an
arbitrary number of forms in calls to `ignore` and ignore-do, which
wraps an arbitrary number of forms in ignore, then bundles the whole in
a do call, effectively executing each form only for side effects and
ignoring all results.

feat: Add additional ignore macros

---

src/Concretize.hs
src/Deftype.hs
src/SumtypeCase.hs
src/Sumtypes.hs
src/Validate.hs

This commit fixes issue #1302, whereby types defined in modules were not
recognized as valid member types by our validation routines.
We simply need to account for types defined in modules in the global
env, threading the global env along through validation (previously we
only passed the top-level type env, which contains no modules).
Fixes #1302

fix: Allow types defined in modules to be members

---

src/Emit.hs
test/regression.carp

This PR fixes #1296 by eliding definitions of `Unit` type. The body still gets executed for side effects, but does not get assigned to a variable.
A regression test is included.
Cheers

fix: elide definitions of type `Unit`

---

src/Constraints.hs
src/Types.hs

This commit builds on the emit-c feature by permitting C typed values to
be used anywhere in Carp code.
For example, if one wants to use the literal C macro `EDOM`:
```clojure
(register EDOM C "EDOM")
(Int.+ 1 EDOM)
=> 34
```
when compiled, this will produce the call:
```c
Int__PLUS(1, EDOM)
```
So it provides a quite flexible means of using C macros directly. It is,
of course, also radically unsafe. Anyone registering and using values of
the C type better be cautious.
One can get pretty crazy with this feature:
```clojure
(register comment-it C "// commented out;")
(Int.+ 1 comment-it)
=> int _11 = Int__PLUS_(1, // commented out;)
int* _12 = &_11; // ref
String _13 = IntRef_str(_12);
```

feat: allow C types to satisfy all type constraints

---

.github/workflows/nixpkgs.yml

Only runs when commiting to master and on pull requests, like the Windows, MacOS and Linux CI.
This workflow was inconsistent with the other CIs.

ci: Runs nixpkgs workflow only on master

---

core/IO.carp

This PR fixes our `unlink` varieties on Windows by using the non-deprecated `_unlink` function instead of `unlink`.
Cheers

fix: use non-deprecated unlink function on windows

---

src/Eval.hs
src/StartingEnv.hs

This PR adds `expand-compiled`, which expands and annotates an AST and returns the result. It can be used to inspect the result of macro-expansion, desugaring, and typechecking at the same time:
```
> (expand-compiled '(+ (* 3 4) (inc @&2)))
=> (Int.+ (Int.* 3 4) (Int.inc (Int.copy (ref 2))))
```
Cheers

feat: add expand-compiled

---

core/List.carp

This PR adds the dynamic function `List.find-index` originally from my [match-utils](https://github.com/hellerve/match-utils) library.
Cheers

feat: add Dynamic.List.find-index

---

docs/LanguageGuide.md
src/PrimitiveError.hs
src/Primitives.hs

This PR adds a compiler error and a note to the docs on the maximum constructors we currently allow in a sumtype (128).
Cheers

feat: add compiler error on maximum sumtype constructors

---

core/Macros.carp

These macros apply an operation to the current value of a variable and
then set the variable to the result of the application. They are
effectively sugar for writing `(set! <var> (<op> <var> <val>))` and
should be familiar to those who have programmed in imperative languages
like C.
In Carp, all the underlying operations these macros use are interfaces,
so one can flexibly use them for more than just numeric types.
Example usage:
```clojure
(let-do [dial 0]
;; crank it up to 11!
(while-do (< dial 12)
(++ dial))
dial)
;; expanded
(let-do [dial 0]
;; crank it up to 11!
(while-do (< dial 12)
(set! dial (inc dial)))
dial)
```

feat: add assignment operator macros

---

docs/CInterop.md
headerparse/Main.hs
src/Types.hs
src/TypesToC.hs

Adds -c|--emitcname flag to headerparse to always emit the C identifier
in `register` definitions (useful when the register will be in a
module).
Fixes a bug where the kebab case flag would not output C identifiers
making the emitted C identifiers not match with the ones in the headers.
Adds docs entry about headerparse in CInterop doc.
Makes headerparse emit `CChar` instead of `Char` when encountering a
signature containing `char`.

feat: Adds flag to always output C id with headerparse

---

CarpHask.cabal
app/Main.hs
core/Box.carp
core/Core.carp
examples/functor.carp
src/BoxTemplates.hs
src/StartingEnv.hs
src/TypesToC.hs
test/box.carp
test/memory.carp

This PR adds a Box type to Carp using the initial approach in #1337. 
One important difference is that the box is implemented as a pointer, instead of a struct. While this is simpler, it doesn't play quite as well with Carp's overall programming model, since we need to treat the type specially in `TypesToC` as a result--but then again, we already do this for some other compiler defined types so it's not too strange.

feat: add box type

---

src/Emit.hs
src/Env.hs
src/Primitives.hs
test/interop.carp
test/interop.h

Historically, we did not support calling (register-type) within a
module--while there were instances of such calls (even in our core
library!) they were not properly handled in two ways:
1. They weren't added to the right place in the type environment.
2. Their corresponding emitted code wasn't correct.
This commit enables registering types in modules by making a few fixes:
1. Fix the logic in environment mutations -- before, adding a type to an
environment would result in traversing the environment chain
incorrectly. This is now fixed (we traverse modules and retrieve a
type environment only at the end of the traversal).
2. Fix the typedef emission for registered types--it previously emitted
the C code for the type path, not for the type definition (it called
pathToC not tyToC).
This …

fix: permit registering types in modules

---

core/Pattern.carp
src/Primitives.hs

This fixes an issue where by types with fields registered in modules
weren't emitted with their module paths. This makes the behavior between
RegisterTypeWithoutFields and RegisterTypeWithFields the same. They both
account for the current module path in which the type is registered and
output the emitted typedef appropriately.
This fix also eliminates the need for a workaround in core/Pattern.carp.
We previously had to register MatchResult with an override because of
the old behavior, but now the override is no longer needed (since
MatchResult is defined as PatternMatchResult in its source header).  The
call (register MatchResult) within (defmodule Pattern) emits
"PatternMatchResult" by default since we now account for module paths
for registered types.

fix: ensure registered types with fields emit path

---

docs/Install.md

Should also update the release page with :
* For POSIX : ensure that the `LC_CTYPE` locale has an UTF-8 aware value
It would also be nice to implement something along the lines of this elisp snippet in `app/Main.hs` to warn the user. (Couldn't do it myself because I don't know haskell)
```elisp
(defun lc-ctype-is-utf8-compatible? (lc-ctype-value-str)
(when (and
;; In Unix systems LC_CTYPE has always a value,
;; but Windows 10 doesn't have value for LC_CTYPE (and doesn't need it to handle UTF-8 correctly)
lc-ctype-value-str
;; When lc-ctype-value-str has a value,
;; it is a very reliable heuristic to detect a POSIX system.
(string-match
;; regex to match
;; either “.utf8” or “.utf-8”
;; at the end of the string
"\\.utf-?8$"
;; downcase because the locale is case insensitive
(downcase …
```

docs: Instructions to ensure correct handling of utf-8

---

src/ArrayTemplates.hs

The Ref in the type signature had the array and lifetime type in the
incorrect position.

fix: fix type signature of Array.unsafe-raw

---

.github/workflows/nixpkgs.yml
default.nix

As reported by Hrafn Blóðbók, nix updated references to pkgconfig in its codebase to use the `pkg-config` spelling, this seems to break the installation of Carp using nix.
See this PR: https://github.com/NixOS/nixpkgs/commit/9bb3fccb5b55326cb3c2c507464a8a28d44d1730
The current error when installing:
```
error: anonymous function at /nix/var/nix/profiles/per-user/root/channels/nixos/pkgs/development/haskell-modules/generic-builder.nix:13:1 called with unexpected argument 'pkgconfigDepends'
at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/customisation.nix:69:16:
68|     let
69|       result = f origArgs;
|                ^
70|
```
We might need to update the nix action as well, just pushing it like this for now.

fix: Fixes nix install by using correct pkg-configDepends config key

---

src/Primitives.hs

This PR fixes #1347 by ignoring generically typed symbols when we echo C output. That should usually be safe, since the specializations will still be printed when the forms require them.
Cheers

fix: #1347 by  ignoring generically typed symbols on printing C

---

core/Format.carp
test/format.carp

The macro `fmt` had a bug that lead to the start of the string being cut off when the first formatting directive was a literal percent (as in `%%`). Example:
```clojure
> (IO.println &(fmt "hi %% bye"))
% bye
```
Now this behavior is fixed and a regression test case was added.
Cheers

fix: fix leading % format in fmt

---

src/Deftype.hs
test/regression.carp

This fixes a regression whereby the names of struct fields weren't
mangled in calls to setters/mutators, resulting in invalid C code if the
user happened to use reserved words in their struct field names such as
"short" or a disallowed character like a dash.
Fixes #1378

fix: mangle field names in setter templates

---

core/String.carp
test/macros.carp

Adds a new dynamic function that converts a string to an array of
strings, one for each character in the string. In other words, it's the
same as Dynamic.String.to-list but the result is an array structure
instead of a list.
It's also significantly faster than to-list on large inputs. The current
implementation of Dynamic.String.to-list takes long to process large
inputs, presumably because of its recursive behavior and multiple calls
to cons (I'm currently investigating this) (e.g. use read-file then try
calling to-list, you may need to wait a while). Contrarily, to-array is
nearly instantaneous even when the input string is large. This is
because it leverages Haskell's `splitOn` directly, which, when given an
empty delimiter, (which is the case for the empty string), splits the
entire …

feat: add Dynamic.String.to-array

---

.github/workflows/release.yml
.github/workflows/windows.yml

This fixes error in Windows pipelines by [forcing the scoop installer](https://github.com/ScoopInstaller/Install#for-admin) to run.
I don't believe there is much point in not-running as Admin given the environment the CI runs in.
Edit: had to upgrade the Windows version because 2016 is getting deprecated but it comes with ASAN errors we've seen before.

ci: Fixes scoop install as admin user

---

core/IO.carp

IO defined a function, fgetc (distinct from IO.Raw.fgetc) which actually
produced invalid code, since the name was not overridden and C does not
define IO_fgetc.
There was also a TODO to handle EOF conditions; so, I've implemented the
function, checking for EOF and error conditions using the Raw stdio
wrappers. IO.fgetc returns a Char in Success on success and an error
string on failure.
This PR also registers `feof` and `ferror` -- `IO.fgetc` is implemented in pure Carp by calling these wrapper functions.

feat: add IO.fgetc

---

.github/workflows/windows.yml

This PR fixes #1404, it does that by ensuring that we're using Clang/LLVM from scoop rather than the one bundled with the image or the one bundled with MSVC.

ci: Re-enable Debug.sanitize on Windows

---

src/Parsing.hs
stack.yaml
test/dynamic_map.carp

Comes with GHC 9.0.2.
Some tests in `test/dynamic_map.carp` were updated to not be order dependent.

chore: Updates Stackage version to 19.2

---

core/List.carp
core/Test.carp
test/dynamic_map.carp
test/list.carp

This adds Dynamic.sort function based on the quicksort described [here](http://learnyouahaskell.com/recursion).
It also contains a refactor of the dynamic test handles to properly display a diff of the expected Vs actual value rather than displaying "true" : "false".
Test display examples:
old:
```
Test 'Dynamic.sort sorts from higher to lower' failed:
Expected value: 'true', actual value: 'false'
```
new:
```
Test 'Dynamic.sort sorts from higher to lower' failed:
Expected value: '(4 3 3 5 1)', actual value: '(4 3 3 2 1)'
```

feat: Adds Dynamic.sort & improves output of failing dynamic tests

---

core/Double.carp
core/Float.carp
core/Int.carp
core/Interfaces.carp
core/Long.carp
core/StdInt.carp
core/carp_stdint.h
src/Concretize.hs
src/Info.hs
src/Memory.hs
test/interface.carp
test/memory.carp
test/output/test/test-for-errors/return_ref_in_let.carp.output.expected

Adds MAX and MIN for each INT<N> type and MAX for each UINT<N> type.
These are macros defined by stdint.h and are sometimes useful for bounds
determinations and conversions and such.

feat: register MAX and MIN macros for stdint types

---

docs/DynamicSemantics.md
docs/ReleaseChecklist.md
docs/Tooling.md

This is a tiny PR to ensure there is only one h1/single # per markdown document. It was throwing off some documentation generation.

docs: Updates markdown docs to only have one h1

---

core/Map.carp
test/map.carp

This PR adds a `Bag` data structure, which acts as a set (only storing each thing once) that keeps track of the number of times an item was put in the structure. It’s thus a deduplicated, unordered collection.
Cheers

feat: add bag data structure

---

src/Commands.hs

This PR extends `Dynamic.String.concat` to also work on lists.
Cheers

fix: allow String.concat to work on lists

---

core/List.carp

This PR fixes `Dynamic.List.pairs` to not depend on quasiquoting for now, because that seems to break it for some reason 😬 
Cheers

fix: quasiquoting breaks List.pairs

---

docs/Memory.md

I wanted to better understand Carp's memory management system before diving in to fix some things, so I figured I'd write about it to enhance my own understanding. First off, however, I felt it might be nice to have a general, relatively approachable introduction to the general concepts behind a linear type system for newcomers to reference. Part of this was sparked by @eriksvedang's insightful comment that lifetimes have much to do with multiple scopes and moving values across different lexical bindings.

docs: update memory.md

---

app/Main.hs

At some point (I believe version 13.0.0?) clang added a warning that catches variables that were assigned but unused. This version of clang (or later) is now bundled w/ github's macos images and is causing our tests to fail in continuous integration. We can currently generate C code that trips this warning, so for now I've disabled it as we do some other warnings related to variable usages.

chore: disable unused-but-set-variable for clang

---

core/IO.carp

This commit also makes some modifications to the source file to improve readability.
FIXES #1445

docs: cleanup core IO docs

---

docs/Memory.md

Adds some details about the internals of the memory management system.

Document the memory management system further

---

core/SDL.carp

As raised by @maacl in #1452, the "tip" in SDL.carp about putting a dynamic variable inside `profile.carp` was a little confusing. I tried to add a note to clarify.
Cheers

docs: add clarification to SDL comment

---

core/carp_pattern.h

As discussed in #1451, we’re using `sprintf` in some places. It should always be safe, but I changed it to `snprintf` anyway, just to make sure. Better safe than sorry, usually.
Cheers

chore: remove usage of sprintf

---

src/Concretize.hs

Before, the member deletion did not mangle the member name, so members named things like `default` (as is the case in https://github.com/carpentry-org/clig) would emit faulty C.
Cheers

fix: mangle member name in deletion generator
