src/assertions.h, src/obj.c
Attempts to addresses issue #20
=> Adding 'assert_or_fatal_error', obj_new now checks for failed malloc and calls

MANUAL.md
=> strike extra apostrophy

lisp/core.carp, lisp/core_macros.carp
found 3 or so tabs in lisp/*.carp, changed to spaces.
=> removing a few tabs in lisp/*.carp

lisp/boot.carp, lisp/core.carp, lisp/core_tests.carp
adding `string-contains?` function.
=> Adding string contains

lisp/core.carp, lisp/core_tests.carp
Also including commit to add some more documentation to lisp/core.carp
=> Core.any short circuit

README.md, lisp/gl.carp
The base of #56 was old (140+ commits behind)
This branch rebases onto current master, fixes merge conflicts, and squashes commit down.
I also shortened commit message a little.
Please review @paines
=> @Paines gl carp refactor, adding to contributors

CMakeLists.txt
this should fix the issue reported by @daveyarwood on #24
=> was accidentally using pkg-config for mac as well

app/Main.hs
Previously the REPL exited with an `isEOFError` and an error message when the user pressed `Ctrl-D`. This PR patches the REPL to handle this a bit more gracefully. Of course editline capabilites would be better, but this is a quick fix.
I will look at #69 and see whether we could use a ready-made Haskell solution (I’ve had great experiences with [Haskeline](https://hackage.haskell.org/package/haskeline)) to increase portability.
Cheers
=> Make REPL react to EOF

src/Emit.hs, src/Parsing.hs
This PR fixes the handling of escaped quotes, in the parser, REPL, and code emitter. It previously didn’t handle escaped quotes graciously.
Cheers
=> Fixed parsing of escaped strings

app/Main.hs
This PR adds `expand` to the list of autocompleted words.
Cheers
=> Add expand to autocompletion

app/Main.hs, core/Bool.carp, core/IO.carp, core/Int.carp, core/String.carp, core/Test.carp, core/prelude.h, examples/test.carp
This PR introduces a whole lot of stuff, most notably a test module. This is a WIP, and I’d advise against merging it at this time. It is, however, in a state in which we should be starting a conversation about it.
Introduced by this PR:
- `=` and `/=` for `Bool`
- `/=` for `Int`
- `/=` for `String`
- `from-chars` for `String`: makes a string from an array of characters (can be removed, not necessary for this PR)
- `repeat` for `String`: repeats a given string `n` times
- `string-join`: append multiple strings (TODO: naming)
- introduce the testing library
What do y’all think?
Cheers
=> Added Test module

docs/Libraries.md
This PR adds the Test and Vector modules to the Libraries listing, for the sake of documentation.
Cheers
=> Added test and vector to Libraries.md

core/Statistics.carp
This PR changes the nested `if` forms in the `Statistics` module into `cond` forms, as discussed in #83.
Cheers
=> Transform nested if into cond

core/Geometry.carp
This PR simplifies the functions in the `Geometry` module. The functions were overly complicated before—my bad.
Cheers
=> Simplify Geometry module

core/SDLHelper.h, core/core.h, src/ArrayTemplates.hs, src/Deftype.hs, src/Emit.hs
=> Length-prefixed strings

core/Macros.carp, examples/vector.carp, test/array.carp, test/double_math.carp, test/float_math.carp, test/int_math.carp, test/long_math.carp, test/safe_artihmetic.carp, test/statistics.carp, test/vector2.carp, test/vector3.carp, test/vectorn.carp
This PR introduces a `use-all` macro that expands to a list of `use` statements. It reduces the pain of using a lot of modules significantly.
I also took the liberty and changed the tests to use it so that we can actually verify it works.
Cheers
=> Introduce use-all

core/Double.carp, core/Float.carp, core/Geometry.carp, core/Interfaces.carp, docs/Presentation.md
=> Changed pi symbol to 'pi'

README.md
This PR is not my most important addition, but I wanted to add my Github handle to my name, so people can actually browse through the libraries I’ve written for and in Carp and such.
Cheers
=> Vanity: added my github handle

examples/reptile.carp
This PR fixes and updates reptile, which has been broken for a while. It now runs and is playable (and quite fun)!
Cheers
=> Fix reptile

docs/LanguageGuide.md
This PR updates the language guide a little bit, because it’s severely out of date. It still is after this PR, but it’ll be slightly better.
Cheers
=> Update language guide

core/Array.carp, test/array.carp
This PR introduces a generalization of `subarray` that takes a start and end index. It also introduces `prefix-arrary` and `suffix-array` that only take a start and end index, respectively.
I also took the liberty of adding a few test cases.
Cheers
=> Generalized subarray

README.md
- Seeds based on time so the random number isn't the same every time
- Splits out a couple of functions and variables to demonstrate def and defn
- Shows how to format with string-join
If you want this, cool. If not, no hard feelings.
Thanks for building Carp. I'm enjoying tinkering with it so far.
=> Make example a bit more friendly

core/Char.carp, core/Double.carp, core/Float.carp, core/Interfaces.carp, core/String.carp, core/Vector.carp, core/core.h, test/vector2.carp, test/vector3.carp, test/vectorn.carp
This PR began as a humble fix for some problems in Vector, but it has grown to be a bit more.
I’m adding a few functions to the Vector API, namely:
- `zero`, which will create a zero’d vector (`zero-sized` for VectorN for dimensionality)
- `random`, which will create a random unit vector (`random-sized` for VectorN for dimensionality)
- `parallel?` to check whether two Vectors are parallel
- `anti-parallel?` to check whether two Vectors are anti-parallel
- `perpendicular?` to check whether two Vectors are perpendicular
I took the liberty of adding a few interfaces, namely `mod`, `random`, and `random-between`.
I also implemented the following methods:
- `random` and `random-between` for Chars
- `random-sized` for Strings (there is no pretty way of defining …
=> Better Vector API & Random

app/Main.hs, core/Array.carp, src/ArrayTemplates.hs
This PR moves `index-of` and `elem-count` into Carp land.
Cheers
=> Rewrite index-of and elem-count in carp

app/Main.hs, core/Array.carp, docs/Todo.md, src/ArrayTemplates.hs, test/array.carp
This PR rewrites range to be a regular function. This solves a todo in `docs/Todo.md`.
Cheers
=> [DO NOT MERGE] Make range a regular function

examples/benchmark_n-body.carp, src/Deftype.hs
This increases performance for more complex structs.
=> Added setter-ref set.. to DefType (struct).

app/Main.hs, core/Int.carp, src/ArrayTemplates.hs, src/Commands.hs
Added clamp to Int too. Fixed random-between floating point exception when lower = upper.
Added Array.initialize, symbol? commands.
Also added pow for integers. This does not use math's `pow` function, as it can be **very** slow in certain cases.
=> Int.clamp/pow, random fix, Array.initialize and symbol?

bench/arithmetic.carp, bench/array_access.carp, bench/structs.carp, core/Bench.carp, core/Macros.carp
This PR addresses #101 by adding a directory called `bench`, and, for now, filling it with the very basics.
I also took the liberty of adding an `ignore` macro that takes a form and ignores its result.
Cheers
=> Add Benchmarks

core/Bench.carp
This PR fixes bench to work with the new member access API of structs.
Cheers
=> Fix bench for new member accesses

examples/reptile.carp
This PR fixes the reptile game. The new API forces us to do a few more copies.
Cheers
=> Fix reptile for new accessor functions

src/Parsing.hs
This PR adds pattern validation to the parser. This sieves out a class of bad patterns.
Cheers
=> Add pattern parser validation

core/IO.carp, core/carp_io.h
=> Read file until EOF

core/String.carp, core/carp_string.h
=> Removing String.duplicate in favour of String.copy

core/Array.carp, core/Bench.carp, core/Filepath.carp, core/Format.carp, core/Macros.carp, core/String.carp, core/Test.carp, core/carp_pattern.h, core/carp_string.h, docs/LanguageGuide.md, examples/basics.carp, test/array.carp, test/memory.carp, test/string.carp
I have some more I want to do, but this is probably a decent chunk to land in one go.
=> String library improvements

run_carp_tests.sh
=> Adding `stack install` back into run_carp_tests

core/Statistics.carp, core/Test.carp, core/Vector.carp
This PR adds documentation for the modules Test, Statistics, and Vector.
Cheers
=> Document Test, Statistics, and Vector modules

README.md
This PR removes the caveat that we don’t have lambdas, for that is not true anymore.
Cheers
=> README: we have lambdas after all

core/IO.carp
This PR adds a few more IO functions around files to IO. Maybe we should think about adding a `File` module to the standard library?
Cheers
=> Add more file IO functions

examples/life.carp
This PR fixes the game of life example we provide in the `examples` directory.
Cheers
=> Fix game of life example

core/Array.carp, docs/core/Array.html, test/array.carp
This PR adds `Array.empty?`, `Array.any?`, `Array.all?`,  and `Array.find`.
- `Array.empty? : (λ [(Ref (Array a))] Bool)` checks whether an array is empty.
-  `Array.any? : (λ [(λ [&a] Bool), (Ref (Array a))] Bool)` checks whether any of the elements in the array match a given predicate function.
-  `Array.all? : (λ [(λ [&a] Bool), (Ref (Array a))] Bool)` checks whether all of the elements in the array match a given predicate function.
- `Array.find : (λ [(λ [&a] Bool), (Ref (Array a))] a)` will find the first element in the array that matches the predicate function, or return `zero`—this will probably be a `Maybe`as soon as #315 is resolved.
Test cases are included!
Cheers
=> Add a few Array functions

core/SDL.carp, core/SDLHelper.h
This PR introduces a few more SDL functions. Those are important for picture saving, which I implemented for Anima ([this is what it looks like](https://github.com/hellerve/anima.carp/blob/master/examples/whispering_drink_picture.carp), [this is how it is implemented](https://github.com/hellerve/anima.carp/blob/master/anima.carp#L81)).
Cheers
=> core: more sdl functions

core/Int.carp, core/Map.carp, test/int_math.carp, test/map.carp
fixes #335
- add new Int.positive-mod function
- use it for Map and Set operations
- add tests
=> fix Map and Set behaviour for negative hash values

core/Heap.carp, test/heap.carp
Adding more comprehensive tests for Heaps to prevent happening again..
=> Bug #343 Fixing off-by-one in Heap parent function.

core/carp_long.h, test/long_math.carp
=> core: fix Long_copy

src/Concretize.hs
=> propagate type error instead of "Visited body isn't a defn"

core/String.carp, test/map.carp
=> prn and str for Ref Int

docs/LanguageGuide.md
This PR adds a section on patterns to the language guide, fixes #359.
Cheers
=> add section on patterns to language guide

core/Array.carp, docs/core/Array.html, examples/basics.carp, src/ArrayTemplates.hs, src/StartingEnv.hs, test/memory.carp
This PR does the work we discussed in #317. It also adds a check to `endo-filter` that resizes the array if appropriate.
Cheers
=> Add copy-filter and rename filter to endo-filter

core/Core.carp, core/Map.carp, core/Maybe.carp, core/Result.carp, core/Vector.carp, docs/core/Map.html, docs/core/VectorN.html, src/Emit.hs, test/map.carp, test/maybe.carp, test/result.carp, test/vectorn.carp
This PR extends the `Maybe` sumtype and adds support for it to `VectorN` and `Map`. It also fixes a bug in the code emission!
Cheers
=> [Sumtypes] Integrate into stdlib, fix some bugs

examples/arrays.carp, src/ArrayTemplates.hs
I'm not 100% sure about my second commit, but the first one at least fixes the issue of not being able to compile when filling arrays with functions. The second commit actually fixes a segfault when compiling and running on Windows. Apparently, Windows is pickier with branching on uninitialized values, so I added some code when allocating an array of lambdas to at least initialize the struct fields with NULLs. This appears to fix the Windows issue.
=> Fix for issue 365

src/Parsing.hs
This PR fixes the line information that is reported when multiline strings are used in a program. Prior to this PR, the linebreaks in a string did not increment the count in the parser state, such that any reporting after them was inaccurate and often unusable. This PR should fix it.
You can try it out with a program like this, for instance:
```clojure
(def ml-string "hi
i span
multiple
lines")
(defn main [] (+ 1 invalid))
```
The parser currently in master reports an error on line 3, whereas this patch makes the parser realize that the error is actually on the last line.
Cheers
=> Fix line info with multiline strings

src/Eval.hs, src/GenerateConstraints.hs, src/TypeError.hs
This PR is a preliminary to create better error messages. For now, it just rewords basically all of them, and adds the expected/actual argument count to the `WrongArgCount` error. There is a lot of room for improvement, but that’s a good first step I think!
Cheers
=> Better error messages (1/?)

core/String.carp, docs/core/String.html, test/string.carp
This PR adds `String.contains?`, which checks whether a string contains a character.
Cheers
=> Add String.contains?

core/Map.carp
they were accidentally overwriting Map.update docs
=> fix Map.update-with-default docs

src/Eval.hs
This PR changes `members` so that any arguments passed to it are first evaluated as far as possible. This is useful because then we can use it in macros.
An illustrating example:
```clojure
(defndynamic derive-eq-internal2 [ms]
(if (= (length ms) 0)
true
(list 'and (list '= (list (caar ms) 'o1) (list (caar ms) 'o2))
(derive-eq-internal2 (cdr ms)))))
(defndynamic derive-eq-internal [a] (derive-eq-internal2 (members a))) ; this would fail saying that a is not a module
(defmacro derive-eq [t]
(list 'defmodule t
(list 'defn '= (array 'o1 'o2) (derive-eq-internal t))))
```
Also, the above code implements (probably) correct deriving of `=` for arbitrary structs, ain’t that cool?!
Cheers
=> Evaluate symbols in `members`

core/carp_pattern.h, core/carp_system.h
This PR makes all asserts conditional on non-optimization.
Cheers
=> Make all asserts optional

core/SafeInt.carp, docs/Libraries.md
This PR clarifies a little bit what’s necessary for a Git-based Carp package.
Cheers
=> Clarify git loading situation in docs

src/ArrayTemplates.hs, src/Commands.hs, src/Concretize.hs, src/Constraints.hs, src/Deftype.hs, src/Emit.hs, src/Eval.hs, src/Expand.hs, src/GenerateConstraints.hs, src/InitialTypes.hs, src/Lookup.hs, src/Obj.hs, src/Qualify.hs, src/RenderDocs.hs, src/Repl.hs, src/Scoring.hs, src/StartingEnv.hs, src/StructUtils.hs, src/SumtypeCase.hs, src/Sumtypes.hs, src/ToTemplate.hs, src/TypeError.hs, src/Types.hs, src/Validate.hs
This PR applies almost all 300 proposed HLint fixes. Excluded are just a handful of `reduce code duplication` suggestions because we would have to go out of our way to make them happen.
Cheers
=> Apply hlint fixes

src/Eval.hs
This PR adds the documentation to the call to `info` if a docstring was provided.
Cheers
=> Add documentation to (info) if present

src/Eval.hs
This PR fixes #437 by adding a specific help message if `help` is entered into the REPL without any more info.
Cheers
=> Make help more helpful

core/Array.carp, docs/core/Array.html, docs/core/Map.html, docs/core/Maybe.html, docs/core/Result.html, docs/core/System.html, docs/core/Vector2.html, docs/core/Vector3.html, docs/core/VectorN.html, src/ArrayTemplates.hs, src/Deftype.hs, src/StartingEnv.hs, src/Sumtypes.hs, src/Template.hs
This PR fixes #440 by emitting automatically generated documentation for automatically generated functions, which makes sense.
Cheers
=> Generate documentation for compiler-generated functions automatically

src/Concretize.hs, src/Deftype.hs
This PR fixes #481 by emitting member deletion on the mutating setter template.
Cheers
=> Emit member deletion on destructive setter

core/Maybe.carp, docs/core/Maybe.html, test/maybe.carp
This PR adds `Maybe.or-zero` which unwraps a `Just` or calls `zero` if it encounters `Nothing`.
Cheers
=> Add `Maybe.or-zero`

core/Maybe.carp, src/StartingEnv.hs, test/maybe.carp
Used for Maybe.ptr, fixes #494.
=> Add Unsafe.coerce

core/Map.carp
This PR introduces a copy to the default in `Map.update-with-default`.
Cheers
=> Copy default in Map.update-with-default

docs/core/Maybe.html
This PR updates the documentation, reflecting the change introduced in #502. Somehow this was never added.
Cheers
=> Update docs for Maybe.ptr

README.md
This PR adds a link to 0.3.0 to the readme.
Cheers
=> readme: add link to release

core/Macros.carp
This should allow looping backwards (as long as the step is a constant) and using floating point types.
=> More generic for macro

core/carp_string.h, core/core.h, test/string.carp
The current code would break at the added test in `assert((i+lsrc-1) < linto)`.
=> Fix string assert, simpler/faster conditions.

src/Eval.hs
This PR introduces a special case to dependency management: if the dependencies were already downloaded and we’re on a tag or commit (so, in `Detached HEAD` state), we can safely proceed to inline the dependencies without redownloading them. This finally re-enables offline builds when the dependency is already there.
Cheers
=> Offline dependencies

docs/core/Dynamic.html, docs/core/IO.html, docs/core/System.html, src/Commands.hs, src/Eval.hs, src/StartingEnv.hs
Thsi PR makes `list` and `array` commands rather than special forms. They can then be used in dynamic higher order functions (relevant for #536, for instance).
Cheers
=> Make list and array commands

docs/LanguageGuide.md
Added a few short sentences and samples to document the `with` form. I don't have especially robust knowledge of the form or its implementation, so please correct/augment as needed!
=> Document `with`

core/Array.carp, core/Core.carp, core/Double.carp, core/Float.carp, core/Generics.carp, core/Geometry.carp, core/Interfaces.carp, core/Vector.carp, core/carp_double.h, core/carp_float.h, docs/core/Array.html, docs/core/Double.html, docs/core/Float.html, docs/core/Geometry.html, docs/core/Vector2.html, docs/core/Vector3.html, docs/core/VectorN.html, test/vector2.carp, test/vector3.carp, test/vectorn.carp
- Added Generics module.
- Some Geometry/Vector* functions hardcoded parameters to Double.
=> Working on generics.

core/Macros.carp, docs/core/Dynamic.html, src/Commands.hs, src/StartingEnv.hs, test/macros.carp
This PR adds a very simple version of `gensym`.
Cheers
=> Add gensym

src/Sumtypes.hs, test/maybe.carp
I tried also to simplify the code a bit, but maybe those deps were there for some future purpose...
=> Implement get-tag for sum types.

core/Dynamic.carp
This PR reimplements a few functions that we have at runtime.
Cheers
=> Add dynamic string functions tail, prefix, and suffix

core/Map.carp, core/String.carp, docs/core/String.html, test/string.carp
This PR changes `String.join?` to take a reference to a string. Fixes #562.
Cheers
=> Make String.join take ref

src/Commands.hs, src/StartingEnv.hs
This PR adds `Symbol.str` which converts a symbol to a string (which is useful for macro-writing purposes).
Cheers
=> Add Symbol.str

.clang-format, build.sh, core/SDLHelper.h, core/carp_bench.h, core/carp_bool.h, core/carp_char.h, core/carp_double.h, core/carp_float.h, core/carp_int.h, core/carp_io.h, core/carp_long.h, core/carp_memory.h, core/carp_pattern.h, core/carp_safe_int.h, core/carp_string.h, core/carp_system.h, core/core.h
This PR adds a `.clang-format` file and reformats our codebase according to it. The changes should exclusively expand or contract lines.
Cheers
=> Add .clang-format

docs/LanguageGuide.md, docs/Libraries.md, docs/Tooling.md
Not complete, lack some information for me
`with` form is a special form?
Can `match` form pattern match primitive types?
=> Update md files

core/Core.carp, core/Pointer.carp, docs/core/Array.html, docs/core/Bench.html, docs/core/Bool.html, docs/core/Char.html, docs/core/Debug.html, docs/core/Double.html, docs/core/Dynamic.html, docs/core/Float.html, docs/core/Geometry.html, docs/core/IO.html, docs/core/Int.html, docs/core/Long.html, docs/core/Map.html, docs/core/Maybe.html, docs/core/Pattern.html, docs/core/Pointer.html, docs/core/Result.html, docs/core/Statistics.html, docs/core/String.html, docs/core/System.html, docs/core/Vector2.html, docs/core/Vector3.html, docs/core/VectorN.html, docs/core/core_index.html, docs/core/generate_core_docs.carp, src/StartingEnv.hs, test/pointer.carp
This PR tries to fix #423 by adding a few pointer functions, namely:
* `Pointer.width`:  returns the size of a pointers underlying data type,
* `Pointer.add`: adds a long integer to a pointer,
* `Pointer.inc`: increments a pointer,
* `Pointer.sub`: subtracts a long integer from a pointer, and
* `Pointer.dec`: decrements a pointer.
Cheers
=> Add pointer arithmetic

core/core.h
This PR fixes #643 by reformatting `core/core.h`.
Cheers
=> core: reformat core.h

core/IO.carp, docs/core/IO.html, test/io.carp
This PR adds `IO.getenv`, which makes it possible to inquire about environment variables. It returns a `Maybe`.
Cheers
=> core: add IO.getenv

core/Maybe.carp, core/Vector.carp, docs/core/Maybe.html, test/maybe.carp
This PR changes `Maybe.apply` to take a function ref.
Test cases are updated.
Cheers
=> Make Maybe.apply take function ref

core/carp_byte.h, core/carp_string.h
This PR is another reformatting PR, similar to #644, provided by `clang-format`.
Cheers
=> Reformat carp_string and carp_byte

docs/DynamicSemantics.md
I filled this out in a question based format, which I think would be good for brainstorming purposes. Listing the related issues at the top of each section seems like a good idea too.
Sections added:
1. Scoping Rules
2. Evaluation Rules
=> Start filling out the Dynamic Semantics document

src/Eval.hs
This PR changes the semantics of `let` in an evaluated context so that later bindings can refer to prior ones, i.e. this is now possible:
```clojure
(let [x 1
y (+ x 1)]
y)
```
This was already possible in compiled code, just not when evaluating. Now this is possible as well.
Cheers
=> Make evaluated let sequencable

.github/workflows/carp.yml, test/int16.carp, test/int32.carp, test/int64.carp, test/int8.carp, test/uint16.carp, test/uint32.carp, test/uint64.carp, test/uint8.carp
This PR adds Github Actions to the repo as a mean to automatically build the Carp compiler and run tests.
Right now it only runs `./run_carp_tests.sh` as `stack test` is failling, it also skips the sdl tests as I wasn't sure what dependencies are required.
I also had to make changes the to the tests as the load call to StdInt.carp was failing on case-sensitive systems like the CI.
The CI will run on push to master and when someone raise a PR against master, unsure if the second part is alright...
=> Adds Github Actions CI to repository

core/Macros.carp
I took some time today to restrict the functionality of `map` to mapping only, since we have `zip`.
While I was at it, I added a few other utility functions too. I'll add tests tomorrow if I get a chance, but I'm opening this now for feedback!
=> Add more functional dynamic functions

core/Macros.carp, test/macros.carp
I accidentally broke `Dynamic.curry`!
I fixed it and added some much needed tests!
=> Dynamic.Curry fix and Macro Tests

core/Maybe.carp, core/Result.carp, docs/core/Maybe.html, docs/core/Result.html
This PR is for the new reference matching capability. They change the matching functions that work on refs and get rid of the copy.
Cheers
=> Change maybe and result to match on refs if possible

src/Eval.hs, src/Primitives.hs
This PR fixes #718 by making `Dynamic.or` and `Dynamic.and` primitives.
Cheers
=> Make Dynamic.or and Dynamic.and primitives

core/Core.carp, core/Macros.carp, docs/core/Dynamic.html, test/args.carp, test/macros.carp
This PR simplifies dynamics and the macro/dynamic tests by getting rid of `dynamic-and` and `dynamic-or` and adding `Dynamic.any?` and `Dynamic.all`?.
Cheers
=> Better dynamic tests

src/Constraints.hs
Looks like I forgot a tiny but important change for the polymorphic
constructor support--constraint solving!
I only found this out when refactoring an applicative <*> or 'sequence'
definition-- the definition has a polymorphic constructor with a
function argument: `(f (Fn [a] b))`.
When carp attempted to resolve this type against a type returned by lift
which has the type `[a] (f a)`, a generically lifted value, including
functions, it complained:
`can't match (r1 r2)` with type `(r3 (Fn [r4] r5))`. (numbers are
arbitrary here and just for illustration).
Sure enough, we weren't solving for such a constraint. The constraint
resolution now works as expected.
=> Solve for polymorphic constructor constraints

src/Concretize.hs
This change supports more flexible Sumtype declarations.
We used to allow a sumtype declaration such as:
`(deftype (State a) Done (Value [a]))`
Which the compiler accepts. However, concretization for this type
failed, since we didn't handle the solitary Sym case `Done` when
concretizing the type.
This commit fixes that issue, so that now the following works:
```
(deftype (State a) Done (Value [a]))
;; Omitting the type annotation here would result in the obvious
;; unresolved generic type error.
(defn emit-done [] (the (State Int) (State.Done)))
(emit-done)
;; => State.Done
```
fixes #464
=> Fix non-exhaustive patterns in concretize

src/Parsing.hs
Adds the rawstring syntax : 
```
> r"abc"
=> "abc"
> r"abc\n"
=> "abc\\n"
> (macro-log r"\n\r""abc")
\n\r"abc
```
These strings has no escapement (WYSIWYG), with a combination to add a double quote in the string : `r" "" " == " \" "` double double quotes are converted into a single double quote.
=> Rawstrings

src/Eval.hs, test/macros.carp
Make the `while` control structure to be evaluated in dynamic code.
```
> (defndynamic test [] (for [i 0 4] (macro-log "test")))
> (test)
test
test
test
test
```
=> Dynamic `while`

docs/hacking.md
This hacking doc should capture compiler lore, tips and tricks, etc. To start it off, I went ahead and tried to associate each source file with the compiler phase (thanks @hellerve for the svg!) it plays most heavily into. In reality, many of the source files have some role to play across multiple phases, but I tried to represent the functional divisions as best as I could.
Please correct me if I got anything wrong!
=> Add hacking doc

docs/hacking.md
This PR incorporates my edits for #784.
Cheers
=> Edit hacking

docs/hacking.md
Just a small walkthrough on the common steps for implementing a new primitive.
=> Add mini-guide on implementing primitives

default.nix, flamegraph.sh
Script to generate a clickable flamegraph svg.
This one also builds on top of #768.
Sample output:
[out.zip](https://github.com/carp-lang/Carp/files/4605566/out.zip)
=> Flamegraph

.github/workflows/osx.yml
This PR adds macOS testing as a GitHub workflow.
Cheers
=> Add macOS CI target

core/Pointer.carp, core/String.carp, core/carp_string.h, docs/core/Dynamic.html, docs/core/String.html, test/string.carp
This PR fixes #794 by adding `String.to-bytes`.
Cheers
=> Add String.to-bytes

.build.yml
This job needs configuring at sr.ht platform (this needs to done by the github repo owner)
1. Sign up for sourcehut.org
2. Add triggers
- for commit building: https://dispatch.sr.ht/github_commit_to_build/configure
- for building PRs: https://dispatch.sr.ht/github_pr_to_build/configure
Related to #796
=> Adds a FreeBSD 12.x CI target using builds.sr.ht

docs/LanguageGuide.md
I added the documentation for cond which was not added in the LanguageGuide.md. #
Fixes #829
=> update with cond

src/Eval.hs
This PR makes reference literals work in the REPL, similarly to what @eriksvedang and I did for externals, modules, matches, and so on.
Cheers
=> Make ref literals work in the repl

src/Parsing.hs
This PR adds base16 and base 2 literals. It only needs a parser change to work, and they work for integers and long types.
The literals:
- `0xabcd` is a literal hexadecimal integer,
- `0b1010` is a literal binary integer.
By suffixing with `l` or we can make them `Long` literals. Theoretically, they could also work for byte and float types without decimals, but currently only binary literals work with them, since the suffixes `b` and `f` are indistinguishable from hexadecimal literals. We could add additional syntax (like opting for prefixes instead of suffixes), but I don’t think that would add much value for the added complexity.
Cheers
=> Add base16 and base2 literals

src/Primitives.hs
This change makes it possible to declare auto-derived getter/setter
functions on types as implementations of interfaces, e.g. Pair.a.
The same checks for normal functions apply to the instantiations. For
example, given an interface:
```
(definterface left (Fn [(Ref (f a b))] (Ref a)))
```
`Pair.a` can implement this interface, but `Maybe.Just` cannot--since it
results in a kind mismatch.
I also realized that interfaces are currently too flexible/permissive.
For example, given an interface:
```
(definterface id (Fn [a] a))
```
Most, if not all, functions can implement this interface, even when the
implementation clearly doesn't conform. For example, `Pair.a` or even a
function with the type `([String] Int)` are both valid implementations
of this interface. This is because we currently only …
=> Allow "Instantiate" functions to implement interfaces

CarpHask.cabal, app/Main.hs, core/Dynamic.carp, core/OpenGL.carp, docs/Manual.md, src/Commands.hs, src/Emit.hs, src/Eval.hs, src/Expand.hs, src/Obj.hs, src/Primitives.hs, src/Project.hs, src/RenderDocs.hs, src/Repl.hs, src/TypeError.hs
This adds a `(Project.config "pkgconfigflag")` feature.
Notice that `(Project.get-config "pkgconfigflag")` returns an `Arr`. I did that in order to use it from `Dynamic.pkg-config`.
Also fixes #834
=> Add pkgconfigflags.

src/Emit.hs
=> Return 0 from main when the return type is unit.

docs/patterns.md
The first pattern is one I've found handy for returning some data
structure that contains the results of running two different
ownership-taking functions on some argument.
=> Add a doc capturing common patterns

src/Validate.hs
Prior to this commit, a type such as: `(deftype (Foo (f a) [bar a]))`
was rejected by the compiler. However, such a type is sensible--Foo
ranges over some container type `f`, and it is essentially Foo's job to
provide a view into `f`, granting access to `a` and whisking `f` away
via the phantom constructor.
After this change, this type definition is now valid.
Note that one often needs to wrap phantom constructor cases in `the`
unless the type can be determined by the overarching context:
```
(deftype (Foo (f a) [bar a]))
(the (Foo (Maybe Int)) (Foo.init 1))
;; => (Foo 1)
```
fixes #886
=> Allow "phantom constructors"

core/Byte.carp, core/Int.carp, core/Interfaces.carp, core/Long.carp, core/StdInt.carp
This PR makes bitwise operations interfaces.
Cheers
=> make bit-* interfaces

core/String.carp, core/carp_string.h, test/string.carp
This PR supersedes #904.
Cheers
=> Add String.from-bytes

src/StartingEnv.hs
I messed the docs when moving `directory` and `absolute` to the `Path` module.
=> Fix Path docs.

docs/LanguageGuide.md
Interfaces are now explicitly implemented using the `implements` key
word (in the past, implementation of an interface was implicit based on
matching names and function signatures).
This commit updates the language guide to account for this change and
includes an illustrative example to provide guidance on using
interfaces.
Fixes #925
=> Add docs on interfaces and `implements`

.github/workflows/osx.yml
All 3 runs of mine passed successfully. Hopefully, this passes too!!!
See https://github.com/MuhammedZakir/Carp/actions?query=workflow%3A%22MacOS+CI%22.
P.S. It is showing only 2 runs because I did "re-run jobs" for the last one.
P.S.2. Don't ask me why this is working. I don't know! 😄 Caching seems to work a bit differently for this. Maybe because of that?
Edit: I created a new PR instead of a new commit in #928, is to test whether it works here.
=> Test Mac Github actions build

src/Eval.hs
This change alters the evaluator to do two things:
* Organize lookup order using Control typclasses (alternative, monad) which makes our lookup strategies more modular, making it easy to change the order of lookups should we need to (e.g. global first then dynamic, internal first then global, etc.)
* Adds a flag to eval to let callers specify whether they prefer looking for unqualified bindings `inc` opposed to `Dynamic.inc`, in the Dynamic or Global environment first.
The behavior these changes support is that `s-expr` calls can now retrieve global or type level binding forms when these conflict with bindings in `Dynamic`--previously, Dynamic bindings were always preferred, giving `s-expr` calls no way to retrieve bindings that were actually associated to the global module.
```clojure
;; …
```
=> Add flag to determine binding lookup preferences in the evaluator

core/Tuples.carp, docs/core/Dynamic.html, docs/core/Quadruple.html
This PR implements yet another doc typo fix.
Cheers
=> Fix typo in Quadruple docs

core/String.carp
This PR fixes #956 by removing `Pointer.prn` (please verify that it actually resolves it for you as well)!
Cheers
=> remove Pointer.prn

src/Constraints.hs, src/Types.hs
This change makes refs "constructible" in the perspective of the type
system by allowing them to stand for polymorphic constructors such as
`(f a b)`. After this commit one can take an interface such as:
```
(definterface out (Fn [(f a b)] a))
```
and provide an implementation over references:
```
(defn copied [x] @x)
(implements out copied)
```
`copied` is a valid implementation of `out`, since it simply copies the
value of a reference, dropping its lifetime.
Essentially, this makes the type system slightly more flexible, allowing
one to view references as type constructors in their own right.
For a little bit of background--this enables handling copying more flexibly in certain contexts. Some functions rightly need a reference and some rightly need a value, but in certain scenarios a …
=> Allow Refs in polymorphic constructor positions

core/Random.carp, test/random.carp
This PR ensures that we call `Random.reseed` at program start to ensure randomness.
Cheers
=> Call Random.reseed at program start

docs/CInterop.md, docs/LanguageGuide.md
Started with passing around `String`s across the C boundary.
After that I was gonna do `Array`s and `deftemplate`.
Please chime in with anything that would useful to have in there.
=> Adding more documentation around C Interop

core/carp_utf8.h, src/SymPath.hs
=> Unicode fixes

docs/ReleaseChecklist.md
=> docs: Release checklist

src/Commands.hs, src/Emit.hs, src/Eval.hs, src/Obj.hs, src/Parsing.hs
An alternative to #1004 
I think I prefer this one. Look at `commandPlus` and friends, looks better in this branch IMHO.
=> Split integer/floating point number representation (second alternative)

src/Eval.hs
The `address` keyword is useful when one needs to circumvent Carp's
memory management for particular cases. However, the evaluator
previously didn't understand `address` in most contexts, so it proved
difficult to toy around with in the REPL.
This commit adds basic support for calling `address` in the REPL by
adding a case to the evaluator. This allows users to test out functions
that take `Ptr` arguments such as `Pointer.to-value`. The `address`
keyword only accepts a symbol as an argument (since getting the address
of a literal value doesn't always make sense (e.g. &2) and produces
invalid C):
(def a 1)
(address a)
=> a
(type (address a))
=> (Ptr Int)
(Pointer.to-value (address a))
=> 1
Note: one will still typically need to wrap it in a function in
higher-order contexts.
=> Eval: Add Address to eval

README.md, docs/Contributing.md
Maintaining the contributors list seemed like a chore when Github already supports that feature in such a nice way.
More ideas for what should go into Contributing.md are most welcome!
=> docs: Better credits and contribution guide

CarpHask.cabal, src/ArrayTemplates.hs, src/Commands.hs, src/Concretize.hs, src/Deftype.hs, src/Emit.hs, src/Eval.hs, src/Expand.hs, src/GenerateConstraints.hs, src/Primitives.hs, src/StructUtils.hs
This one probably requires closer inspection. I tried to leave debugging helpers commented, but maybe you prefer to leave them uncommented.
=> Address unused local bind.

docs/Contributing.md, scripts/commit-msg-hook.sh, scripts/setup-git-hooks.sh
Creates git hook to enforce Conventional Commits as well as a shell script to setup the git hook.
Mentions the setup script in the Contributing doc.
=> chore: Creates git hook to enforce Conventional Commits

README.md
Thought this would make a good first contribution :wink:
=> Fix link to Contributing.md

docs/Memory.md
This PR documents the behavior introduced in #1061, except for `blit`, since we’re still discussing that in #1079.
Cheers
=> Document delete

src/Concretize.hs
This PR removes the trace that generates `Already visited ...` messages.
Cheers
=> Remove outdated already visited trace

core/Array.carp
This is a very common idiom in Clojure that gets used a lot in reducers. It's nice to have.
=> feat: Add "rest" function to Array

src/Eval.hs
Notably, don't type check dynamic bindings (which can be set to
whatever) and eliminate a hang that resulted from not handling an error
at the end of the `set!` call. Also refactors some of the code in
efforts to make it a bit cleaner.
Also adds an error when `set!` can't find the variable one calls set!
on.
fixes #1098
=> fix: fix errors with set!

src/Primitives.hs
A misplaced type env reference caused a bug in which types could not be
placed in modules more than a single level deep. Similarly, existing
modules in the type env were always overwritten when new types were
added to modules that were not disjoint. This commit fixes both issues.
In the future, we should likely make module management functions more
general and call them to manage modules in both the value and type envs.
e.g.:
```
鲤 :i Foo
Foo : Module = {
Bar : Module = {
Baz : Module = {
Boo : Type
}
Boo : Type
}
}
Defined at line 0, column 0 in 'dummy-file'
Foo : Module = {
Bar : Module = {
Baz : Module = {
Boo : Module = {
copy : (Fn [(Ref Foo.Bar.Baz.Boo q)] Foo.Bar.Baz.Boo)
delete : (Fn [Foo.Bar.Baz.Boo] ())
get-tag : (Fn [(Ref Foo.Bar.Baz.Boo q)] Int)
prn : (Fn [(Ref Foo.Bar.Baz.Boo …
```
=> fix: manage nested modules in the type environment

core/Map.carp, test/map.carp
This PR adds `Map.merge` to the `Map` API.
Cheers
=> feat: add Map.merge

core/Platform.carp, src/Util.hs
These were the only changes I needed to make to Carp's code itself in order to get it to build and run on NetBSD/amd64 9.0.
=> feat: Recognize the NetBSD platform.

src/Eval.hs, test/macros.carp
This PR fixes #1121 by respecting `use` in dynamic lookup.
Cheers
=> Respect use in dynamic lookup

src/Env.hs
Previously, we couldn't replace qualified bindings in Envs. This change
updates envReplaceBindings to accept qualified paths and to replace the
binding denoted by the path, updating the module environments the binder
belongs to accordingly.
If the qualified path does not denote an existing module, it simply
returns the environment as is (just like the unqualified case).
=> fix: replace qualified dynamic bindings

core/Core.carp, core/Quasiquote.carp, docs/Quasiquotation.md, docs/core/generate_core_docs.carp, examples/quasiquote.carp, src/Parsing.hs, test/macros.carp, test/output/test/test-for-errors/raw-unquote.carp.output.expected, test/test-for-errors/raw-unquote.carp
This PR adds quasiquotation to the core. It’s implemented entirely in Carp, as a macro.
Test cases and documentation are included.
Cheers
=> feat: Quasiquotation

src/Eval.hs
This PR fixes a problem where previously, macros where not expanded inside dynamic closures.
Cheers
=> fix: expand macros in closure bodies

core/Binary.carp
This PR simplifies and generalizes `Maybe.zip` to a macro.
Cheers
=> refactor: make Maybe.zip a macro

docs/core/generate_core_docs.carp
This PR adds `Introspect` and `Unit` to the generated documentation.
Cheers
=> docs: add Introspect and Unit

core/Quasiquote.carp
This PR makes the implementation of `quasiquote` a little simpler and prettier, and fixes some doc typos. These are fixes that I found while working on my upcoming blog post on quasiquotation.
Cheers
=> refactor: refactor quasiquotation

src/Concretize.hs, src/Deftype.hs, src/Eval.hs, src/InitialTypes.hs, src/Lookup.hs, src/Obj.hs, src/Primitives.hs, src/Qualify.hs, src/Set.hs, src/StartingEnv.hs, src/Sumtypes.hs, src/Validate.hs, test/TestLookup.hs
This PR fixes #1128 by  refactoring `Env` to use a `Set` for used modules.
Cheers
=> refactor: use Set for used modules

core/Dynamic.carp, core/Format.carp, core/Macros.carp, docs/Format_Strings.md, src/Emit.hs, src/Parsing.hs, test/format.carp
This PR deals with #1115, at least partially. As proposed by  @scolsen, I changed the name to `fstr`.
Cheers
=> feat: add fstr

core/Macros.carp, src/Commands.hs, src/StartingEnv.hs
This PR adds the `dynamic-type` command as discussed in #1130.
Cheers
=> feat: add dynamic-type command

core/Map.carp
This PR fixes a few small oversights with dynamic maps, more specifically with growing and shrinking them.
Cheers
=> fix: fix multiple small problems with map

core/String.carp, test/macros.carp
This PR adds `Dynamic.String.to-list`.
Cheers
=> feat: add String.to-list

core/Char.carp, core/carp_char.h, test/char.carp
This PR adds `Char.to-byte` and `Char.from-byte`.
Cheers
=> feat: add Char.to-byte and Char.from-byte

src/EvalError.hs, src/Project.hs, src/Qualify.hs, src/StartingEnv.hs
This Pr applies some ormolue format changes. Somehow this seems to keep slipping.
Cheers
=> refactor: use ormolu

src/Concretize.hs
Our use of type variables in deftype forms to support parametric
polymorphism relied on precise matching between variables in the head
and the body of the form. However, this could lead to unification
failure when the concretizer encountered a type that mixed two
polymorphic types that use the same type var name:
```
(deftype (HitRecord a) [ t a ])
(deftype (CurrentHit a) [ hr (Maybe (HitRecord a)) ])
```
Concretizing this would previously attempt to bind both Maybe(HitRecord
) and just (HitRecord) to `a`.
To fix this, we temporarily rename all type variables in type
definitions during concretization. Names are preserved in place, so
there's no danger of losing a variable. The code above will now work:
```
=> (CurrentHit.init (Just (HitRecord.init 5)))
(CurrentHit (Just (HitRecord 5)))
=> …
```
=> fix: rename type variables during concretization to prevent collisions

src/Eval.hs
This PR fixes issue #659 and #1133. The examples in each issue now work:
```clojure
(defdynamic test-val (let [c (car (list 1 2 3))]
c))
> test-val
=> 1
```
```clojure
> (let [f (fn [x] (if (= x 1) x (f (dec x))))] (f 10))
=> 1
```
To support shadowing, we simply add a new lookup preference to the evaluator to prefer the local environment for certain forms like `let`. In order to reduce the performance penalties that come with introducing the additional lookups, we restrict the preference to the list of known shadows in the form (the let's bindings).
To support recursion in `let`, we use the same strategy that we use for normal functions. We add an additional environment that points to the names in the let which can be used to resolve the recursive case. 
The commit messages have further …
=> Fix: Allow shadows of global commands, allow recursion in let bindings.

src/Commands.hs, src/StartingEnv.hs
This PR adds `Dynamic.get-env` and `Dynamic.set-env` for reading and writing environment variables dynamically, as requested by @guberathome.
Cheers
=> feat: add Dynamic.get-env and Dynamic.set-env

src/Eval.hs
The previous pattern matching changes introduced a subtle error in the
evaluator's handling of function applications, we used the same Resolver
for both lists and symbols, where previously we hadn't. Restoring the
old resolution selection and adding a new clause to capture forms like
((defn f [] 2)) restores the correct functioning in the repl.
Importantly, forms such as ((defn foo [x] x) 3), should only be resolved
when the defn form is the result of expanding a symbol.
Eventually, resolving defns to anonymous functions might simplify this
case.
Fixes #1237
=> fix: fix repl function application evaluation

src/StartingEnv.hs
This PR documents the primitive `managed?`.
Cheers
=> docs: document managed? primitive

docs/Memory.md
Updates the Memory docs to discourage overriding `delete` for managed types and point people to `drop` instead.
=> docs: Updates memory docs to discourage overriding `delete`

core/String.carp, test/string.carp
added simple case conversion for ASCII characters
=> Up down case

docs/LanguageGuide.md
This PR adds some documentation on the limits of patterns, as discussed in #1264. It’s very terse, but hopefully explains enough to make sense.
Cheers
=> docs: add pattern limitations

core/Dynamic.carp
This PR adds `Dynamic.Debug.trace`, a version of `Debug.trace` that can be used in the dynamic realm.
Cheers
=> feat: add Dynamic.Debug.trace

src/Scoring.hs
Previously, there was an edge case whereby types that depended on other
types that were not scored yet and functions that in turn depended on
these types could be assigned the same score. When this happened, we'd
sometimes incorrectly emit functions before the struct types they
depended on.
Since functions are always at the bottom of a type hierarchy (they
always depend on their members), there's a simple fix: we just add 1 to
ensure functions are emitted after type declarations in all possible
cases.
fixes #1289
=> fix: Fix scoring of type and function declarations

core/Float.carp, core/carp_float.h
Just a wrapper around the c std function.
=> feat: Add Float.round

src/Polymorphism.hs
A call to sequence in our handling of polymorphics would result in
discarding legitimate interface implementation results in rare cases.
Calling rights instead fixes the issue. We also need to take the union
of the results to ensure we account for cases such as polymorphically
realized interfaces (e.g. the `prn` function for a (Maybe String), other
wise, we don't resolve to concrete polymorphics for types that have
ad hoc polymorphic members.
Fixes #1307
=> fix: ensure interface values aren't discarded

src/ArrayTemplates.hs, test/regression.carp
I'll think a bit more about this before mergeing, Ideally I could come up with something nicer than just verting my previous refactor...
=> fix: #1261

.github/workflows/windows.yml
Checking if the current Windows CI errors are related to changes in the underlying image...
=> ci: Uses older windows version for CI

core/carp_float.h, core/carp_pattern.h, src/Commands.hs, src/Env.hs, src/InitialTypes.hs, src/Memory.hs, src/Polymorphism.hs, src/Scoring.hs
This PR introduces some fixes from `ormolu` and `clang-format`.
Cheers
=> fix: run ormolu and clang-format

core/Binary.carp
Converts an array of bytes to a string of their hexadecimal
representation, for example:
```clojure
(Binary.bytes->hex-string &(String.to-bytes "string to hex :)"))
=> 73 74 72 69 6E 67 20 74 6F 20 68 65 78 20 3A 29
```
=> feat: add bytes->hex-string

src/Constraints.hs
Since solveOne was defined as `= solveOneInternal`, we can just call it directly.
=> refactor: remove unnecessary solveOneInternal function
